src/providers/storage/url.js

Return correct URL for uploaded file so image will display properly if that option was selected.  Also add JWT request header to POST.  This is useful if someone has added a route to the Formio server and is uploading files to it.

Return correct URL for uploaded file.

---

src/components/panel/fixtures/comp1.js
src/formio.wizard.js
test/wizards/condional.next.page.js
test/wizards/index.js

Manage previous page button to keep the form flow, manage submit in intermediate page with null value in nextPage function and dynamicly update the next button into a submit button.
The server `form.io` will certainly need an update without the `Form Component` that you describe in the issue https://github.com/formio/formio/issues/296 to avoid to check a bypassed page which contains required fields.

Add nextPage in panel components to allow conditional next page

---

src/components/checkbox/Checkbox.js
src/components/checkbox/Checkbox.spec.js
src/components/radio/Radio.js
src/components/radio/Radio.spec.js

After looking to better enable styling radio and checkboxes for A11y and touch screens, I made a simple change to the rendering to wrap the label textNode with a SPAN tag. I submit for your consideration.
Closes #101

Add SPAN around label text for better styling hooks

---

src/utils/index.js

ng-formio FormioUtils factory refers to jsonLogic in formio.js version but it's not set.
Can cause problems when needed to evaluate things like JSON Next Page.

Share jsonLogic with ng-formio factory

---

src/components/base/Base.js

The custom layout, where the user can add margins to the component, was ignored.

Fixed the custom layout

---

src/providers/storage/base64.js
src/providers/storage/index.js

File contents will be base64 encoded in submission object. This is useful for cases where multipart/form-data is not an option for form submission.
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsDataURL), IE 10 is required for `readAsDataURL` to work. I'm not sure what browsers Form.io targets, but that would be a constraint of using this upload type.
I need this for a project our company is working on because the enterprise system that we're interfacing with has a convoluted way of dealing with `multipart/form-data` forms, to the point that I have not been able to successfully get a single form to process. I recognize that it likely won't be a common upload type, but hopefully it will be useful for someone else at some point.
Please let me know if …

Add base64 file upload type

---

src/components/select/Select.js
src/formio.form.js

I'm using the Chrome browser on Windows 10.
My form contains a resource component followed by some text components.
Using code like this to render form with existing submission...
Formio.setBaseUrl('http://localhost:3001');
var form = new FormioForm(document.getElementById('formio'));
form.src = 'http://localhost:3001/form/59259f9614746b2a8819866c/submission/59774528acdba937887da5e7';
Code which populates resource component and code which sets submissions resource value are both trying to access instance of 'choices' at the same time and things go haywire.  Following component values do not get set with submission data.
Fix is to load submission after loading of form as in Formio.createForm.
Also fix select dropdown duplication caused by different instances of the same resource.
Also emit …

Wait for form to load before loading submission

---

src/components/base/Base.js

In `destroy` we were accessing an undefined property `handler.event`. Correct property to access is `handler.type`.

Use handler.type instead of undefined handler.event property

---

src/components/file/File.js

At least some versions of IE were not displaying the file browser dialog. The problem was fixed by adding the file input element into the DOM as a hidden item (apparently display: none is not ok but opacity: 0 is fine). Also made the element positioned absolutely to not create empty space anywhere.

Added file input to DOM as a hidden item to fix issue with IE

---

src/components/select/Select.js

Some of our forms appear high on the page and if it is a small form with
select boxes, were opening upwards and off the page. In all cases, we
think opening downwards provides a much better experience.
I added the [documented option](https://github.com/jshjohnson/Choices#position) `position:bottom` to force always opening downwards.

Allow dropdowns to open only downwards

---

src/components/select/Select.js
src/components/select/Select.spec.js
src/components/select/fixtures/comp2.js
src/components/select/fixtures/index.js
test/harness.js

Tab Indexes are being overwritten after creating a new Choice. This will fix that and allow for users to tab in order.

Respect tab index

---

src/components/select/Select.js

Take 2...
This change provides support for url methods other than Get for the selector dataSrc.
It has two new json attributes, method and body.
If not found method defaults to get.
If the method isn't post the body is set to null.
This is needed as GraphQL implementations are not restful and are often post only.

Add method and body parameters for URL option for Select Component

---

src/formio.wizard.js

Support for making the pagination non-clickable
Adds new class to disable clicking, and doesn't add the even listener.

Adding Optional "BreadcrumbSettings" to options

---

src/components/file/File.js

Added base components "this.shouldDisable" to the remove buttons ternary statement. Since the item is in a read only statement "this.disabled" isn't fired and the component renders as a result.

Fixed file upload read only button

---

app/examples/stripe.md
src/contrib/index.js
src/contrib/stripe/stripe/Stripe.js
src/contrib/stripe/stripe/Stripe.spec.js
src/contrib/stripe/stripe/fixtures/comp1.js
src/contrib/stripe/stripe/fixtures/index.js
src/i18n.js

Hi,
This is a another stripe component. This component provides a card input field and optionally a pay button (Apple Pay, Android Pay, Payment request API). Like the other component, Stripe will return a token.
There are 3 cases:
- With a card input field, the validation to stripe will be done before submission with `beforeSubmit()` method
- With a card input field and a button to Authorize the payment, the call to Stripe will be done when the user clicks on the button
- With the pay button, the authorization will be done when the user validates the popup for payment
@travist I created a parameter `componentsMapping` to allow injection of the value from other fields into the request to Stripe for card validation. But I saw your nice example on …

Add stripe component: card input field/Pay button

---

src/utils/index.js

Create a component with simple conditional where,
This component should Display: is false,
When the form component: is some other Text component with no default value,
Has the value: is any non-empty string.
View form and refresh browser.
Component will not display even though Text component referred to is empty (null).
FOR-400 returns false for null values regardless of setting of `component.conditional.show`.
Better to convert null value to empty string so normal logic can precede which takes into account setting of `component.conditional.show`.

Fix FOR-400 for false conditionals and null values

---

src/components/Validator.js
src/components/textarea/TextArea.js

Added placeholder and addressed the error that was causing core WYSIWYG component to fail preventing several items form working.
[Resolved] FOR-976 Placeholders do not work with wysiwyg textarea.
[Resolved] FOR-977 The tab key into the text area captures the buttons of the editor.
[Resolved] FOR-998 WYSIWYG submitted while it is still in “focus” then the data isn’t saved.
[Resolved] FOR-1006 Core Renderer - Unable to backspace using the WYSIWYG component.

WYSIWYG Update - placeholder, backspace, etc.

---

src/components/textarea/TextArea.js

The Event listener inside the Quill object could fail if the WYSIWYG configuration  were changed to exclude certain modules. This would prevent WYSIWYG data from updating field values correctly. 
FOR-990
Video Before & After fix (For Testing)
https://www.screencast.com/t/PBEAfe3Vn41P

Event listener no longer fires unintentionally.

---

src/components/radio/Radio.js

Radio button lacked input-group class causing the container to break. Added the class which is inline with how ngFormio handles the radio button grouping. 
ngFormio Expected:
https://www.screencast.com/t/EUiYBUJwq9
Formio.js - Broken:
https://www.screencast.com/t/mUhYRPNYQo 
Formio.js - With Fix:
https://www.screencast.com/t/ZXcAhJqK

Fixed radio button wrapping issue

---

src/components/button/Button.js

"this.events.emit" should be "this.emit" otherwise customEvents set in portal will not call their named function when used in an application. 
https://www.screencast.com/t/WY8aMXlza46

Fixed custom Events not firing

---

src/formio.js

Instead of throwing an error we should send a rejected promise. Some libraries override the default promise handler and catch the error weird. By returning a rejected promise we ensure things catch in the promise libraries.

Fix issue with the way server errors are resolved.

---

package.json
src/components/file/File.js

This is to enhance my previous fix regarding downloading base64 file. The previous solution was working only on Chrome. However, I found [this library](https://github.com/rndme/download) which already handles downloading files (raw, base64, html,..). Moreover, the library supports most major browsers. I tested the code in Chrome, IE 12 and Firefox.

Enhance downloading base64 file such as it works on all major browser (Chrome, IE, Edge)

---

lib/utils/index.js
src/utils/index.js

ie10 rounds up number to 12345.68 thus the decimalSeparator is not set and the browser console is spoiled by message: '"Unable to get property '1' of undefined or null reference" '.

ie10 issue: "Unable to get property '1' of undefined or null reference"

---

src/components/base/Base.js
src/components/base/editForm/Base.edit.display.js
src/components/panel/Panel.js

This commit will add a checkbox in the form builder settings section and will add a property in the component object called dataGridLabel. 
When a Panel component is added into a Datagrid component the title or property key is shown in the Datagrid header.
[image - 1](http://take.ms/1CNm9)

feature(components): Add property dataGridLabel to components and add setting to form builder

---

src/components/datagrid/DataGrid.js

Force rebuild rows if provided value and current dataValue are
different references.

FOR-1693: Update datagrid setValue method.

---

src/Webform.js

When custom error messages are set, they do not highlight associated components and disappear on the first change.
This PR makes the following changes:
1. Highlight any components listed in {component: 'mykey'} in the error message.
2. Persist error messages associated with specific fields until that field has a change event.

Highlight and persist custom error messages.

---

src/WebformBuilder.js

If one drops component in the builder, the language settings is lost.

language is lost when WebForm is created

---

src/components/select/Select.js
src/components/tags/Tags.js
src/sass/formio.form.scss

Added `dir` attribute to component's input element to provide Choices.js RTL support (see issue https://github.com/formio/formio.js/issues/847)

added-choices-rtl-support

---

src/components/base/Base.js

I have added interpolation for tooltips in order to use `instance.t()` to provide translation support for tooltips.
I have prioritized `this.interpolate()` above `this.t()` as it would be a challenge to deal with line breaks as this are not usually used when managing translations (and thus should be treated as if it where an html component content).

Added component tooltip interpolation

---

src/components/select/Select.js

As of now, only the 'Type to search' label is translatable. This patch allows translating also 'No results found' and 'No choices to choose from'.

Allow translating other Choice.js labels.

---

src/components/select/Select.spec.js

Add `SelectComponent.setValue` tests to ensure that
input value and component value get cleared when
`setValue` called with empty value.

Add tests for Select component

---

src/components/day/Day.js
src/components/day/Day.spec.js
src/components/day/fixtures/comp2.js
src/components/day/fixtures/index.js

- In `monthInput.onchange` expected that dayInput.value
and maxDate will be `Numbers` but got `String`.
- `Dat.getInputValue` fixed.
- Day validation fixed.

Fix bug with day adjustment when switching months

---

src/components/number/Number.js
src/components/number/Number.spec.js
src/components/number/fixtures/comp3.js
src/components/number/fixtures/comp4.js
src/components/number/fixtures/index.js
test/harness.js

Move blur attachment logic from `build` to `createInput`, because it
gets called from both `build` and `buildRows` methods, and independent
from `multiple` option, inputs react on `blur`.
Also switch value source from `event.target.value` to
`this.getValueAt`, because `getValueAt` utilize `parseNumber` and
don't corrupt the value.

FOR-1964: Fix bug with delimiter setting in Number

---

src/WebformBuilder.js

a fix to prevent edit form default options mutation.
When editing fields in Form builder options passed with constructor are being overwritten by options options merged from previous edit form.
STR:
1. Run webformbuilder with custom editform options configuration for two fields (button, textfield).
2. Add button to the form area.
3. Add textfield to the form area.
4. Open button editform.
5. Save changes.
6. Open textfield editform.
Actual result: 
textfeld editform includes button editform elements.
Expected result:
textfeld editform contains only textfield editform.

fix: fix webformbuilder default editform options mutation.

---

src/components/select/Select.js
src/components/select/editForm/Select.edit.data.js

This is useful if you want to override some default options without having to change the code. For example, the select's search result is limited to 4 items.
You can do this to override this default value:

 SELECT: Added option in Data tab to specify custom options that will be used in the Choices JS library

---

src/Formio.js

_There are some problems with references when formio library getting values from cache. Let's assume scenario - in first view you use form in read and view only mode but after click on edit button you render the same form but without read only flags. What is unexpected that submit button is hidden. Why? Because in the first view - formio library hide submit button due to read only mode. It will be proper if not the fact that formio library works on reference so it change original value. When we go to the second view - hidden flag is set because we get this changed definition from cache._
_In proposed solution We assume that cache should work as immutable object so when we get or put values we need to use cloneDeep to remove linking reference. Without that - in app we will be using still …

cut reference for values stored in cache

---

src/components/base/Base.js

Previously the custom default value would calculate and set the default value on the form definition. This would then hard code the value in component.defaultValue and prevent component.customDefaultValue from ever firing again. This makes the following changes:
1. If component.customDefaultValue is set, it will override the component.defaultValue setting.
2. component.customDefaultValue is NOT evaluated in webform builder default preview so it will not automatically set.

Custom default value

---

src/components/select/Select.js

This allows custom components to control the Fuse search behavior, and not only the search threshold, and it's backward-compatible.

Allow custom components to control the Fuse search behavior

---

src/components/checkbox/Checkbox.js
src/components/checkbox/Checkbox.spec.js
src/components/radio/Radio.spec.js

I'm making use of the `radio-selected` class to do some styling and I'd like to do the same thing for checkboxes however I noticed that no class is set on the component/wrapper div (in the checkbox case, the div with class formio-component-checkbox) when the checkbox is checked.
I did these things:

Update Checkbox to add checkbox-checked class like Radio adds radio-selected class

---

src/components/file/File.js
src/sass/formio.form.scss

Pull request for issue #1085 .
> As large file uploads take time, form submissions probably should be prevented when file uploads are still in progress.
> 
> Here is a partial solution that prevents accidental mouse clicks on a submit button in this case,
> [and the] corresponding CSS for disabling the accidental click on submit.
> As noted e.g. [here](https://bitsofco.de/theres-no-reason-to-use-pointer-events-for-html-elements/#disablinginteractiveelements), to prevent activating the submit button via keyboard, it needs to be properly disabled, so instead of using a CSS class and styling this should actually set disabled="disabled" on the button (and find a way to return to the original state once all uploads have finished). Probably best to integrate with other conditions causing the …

#1085 Disable submit button while file uploads in progress.

---

src/Formio.js

the OktaAuth TokenManager get() will return a promise. Without this, the subsequent call will always have the accessToken as being undefined. It is also unnecessary to create a new OktaAuth object at this point. Just use the one that is provided.

Fixing Okta SSO get AccessToken error

---

src/utils/utils.js

`_.cloneDeep()` against the whole form is expensive, and since it's done for every component with a custom conditional via `FormioUtils.evaluate()`, performance degradation on forms that make heavy use of custom conditionals approaches `O(n^2)`.
Since we don't really need to do this unless the custom conditional makes use of the `form` variable, we can do a quick check and skip over it if it looks like we don't need it, which dramatically improves performance of `FormioUtils.evaluate()`. This has some limitations (e.g. it won't catch things like `eval("fo"+"rm").components`), but I think it's a reasonable tradeoff.

Skip supplying `form` during FormioUtils.evaluate() unless we need it

---

src/components/resource/editForm/Resource.edit.display.js
src/components/select/Select.js

Continuation of #1254.
regarding Select.js: It turns out that for Choices.searchFields to understand SelectComponent.searchField, it needs a 'value.' prefix.
regarding: Resource Config UI: This patch makes existing configuration available for both variants of search (local client-side search in Choices, and web-request-based search queries). The latter might still be buggy, e.g.
- In multiple-selection components, previously added items sometimes disappear. (And sometimes these gone-missing items show up again when the search "finds" them.)
- Once a search query has been done, even removing the entire search input via backspace key does not bring back the full list of resources to select from.
(Those bugs were observed in a version derived from 3.19.4.)

Cleanup Choices.searchFields & add config for search in Resource components

---

src/components/resource/Resource.js

When a user adds a new resource via button from within a
multiple-values select component, any previously selected
options must be preserved.

Fix adding new resource from within multiple-values select.

---

src/components/select/Select.js

Added check to see if change event was fired from remove item in Choices.js. And event value was equal to previous selected item.
Video with issue: https://www.screencast.com/t/iL2rdqtRJdM

Added same value check on select

---

src/PDF.js
src/PDFBuilder.js
src/Webform.js

1. Fix issue with `message` event listener deserializing too aggressively
2. Fix issue with transposed parameters in `PDFBuilder.addComponentTo` signature (now matches parent class function `WebformBuilder.addComponentTo`)
3. Fix issue with PDFBuilder's form destruction preventing `iframe-ready` and subsequent cross-frame communication

Misc fixes for pdf builder

---

src/templates/semantic/cssClasses.js
src/templates/semantic/index.js
src/templates/semantic/wizard/builder.hbs
src/templates/semantic/wizard/form.hbs
src/templates/semantic/wizard/index.js

Attempt at adding semantic ui for wizard. 
Wizard steps should look:
and buttons should look:

semantic-ui wizard

---

src/templates/semantic/wizard/form.hbs

The buttons still have the ul bullet points so updated to use div with class. 
The only issue is the margin between the steps, components and buttons.  Trying to avoid inline css so I'm not sure what the right approach should be here to create a gap between each. @randallknutson happy to get some feedback on the approach.

Bugfix: updated ul to use div for lists for semantic ui wizard

---

src/templates/semantic/builderWizard/form.hbs
src/templates/semantic/builderWizard/index.js
src/templates/semantic/index.js

Should look like above. Slightly difficult to work how to test this locally. Any pointers would be appreciated.

fixing wizard builder layout semantic ui

---

src/templates/semantic/field/form.hbs

Renamed tooltip to title to be consistent.

fixing title for tooltip

---

src/sass/formio.form.builder.scss

Disable pointer events on the iframe container while the dropzone is active; iframe container was intercepting pointer events.

Fix issue with drop events not firing

---

src/PDF.js
src/PDFBuilder.js

A submit button component is automatically added during the initial `PDFBuilder.setForm()` call when the form has not yet been saved.
The submit button can still be removed in Form builder mode, and PDF mode will honor it per FOR-1803.
PDF rendering will now honor the "hidden" setting when rendering the Submit button, ensuring that nested PDF forms will have their submit button hidden (consistent with regular nested forms), and accommodating users who might want to simply hide the Submit button rather than remove it altogether.

Add a submit button on forms that are initially created via PDF builder

---

src/PDF.js

Resolves pass-by-reference issue with `PDF.setForm`'s input being modified (component IDs stripped out) by the time it was posted to the iframe, causing component IDs to desync across parent and child.

Force PDF.setForm to push supplied form to iframe

---

src/components/base/Base.js

Confirmed [formio/ckeditor5-build-classic](https://github.com/formio/ckeditor5-build-classic) rebuild on `master` is sufficient. **This PR assumes availability of a new 12.3 version once that is done.**

Update CKE to 12.3, enable image support

---

src/sass/formio.form.scss

Resolves FOR-2417.
Needs to be propagated to formio-viewer and formio-files-core.

Fix CSS rule for white-space:pre-wrap

---

src/PDFBuilder.js
src/components/file/File.js

Increased default PDF overlay size of the file component from 100x20 to 200x200 so the default sizing can at least render the file picker and/or the storage provider error message.
Builder only, no update propagation needed.

Increase default size of file component PDF overlay

---

src/PDFBuilder.js

Resolves FOR-2415.
Builder-only change, no update propagation needed.

Set file component to image mode by default when added via PDF builder

---

src/components/form/Form.js

Loading promises on hidden subforms were being left unresolved (since loading was never requested), which propagated up to root level and caused all forms with hidden subforms to hit the rendering timeout during PDF generation, even if the form state had fully settled.
This check allows hidden subforms of fully loaded read-only parents to mark themselves as ready, so that the parent form(s) aren't left with unresolved loading promises.
Needs to be propagated to `formio-viewer`. Should coincide with formio/formio-viewer#16.

Allow ready promise on hidden subforms to be resolved

---

src/components/select/Select.js

The argument to `setValue` is not passed to `getFlags` any more, so
`true` as second argument is never translated to `noUpdateEvent:
true`.
With this change, the described behaviour in #1652 is resolved.

Select: do not trigger an update when setting a provided value (#1652)

---

src/components/select/Select.js

If select component uses a static type of data source a loading option shouldn't appear

Fixed issue with appearance of unnecessary loading option

---

src/components/file/File.js
src/providers/storage/url.js

Currently attach and download file can be overridden by passing in fileService into the options configuration. However delete is being handled not in the same way. This PR enables the option to override the delete file by using fileService.  Happy to discuss this further. Our use case means we need to configure our fileService to do some pre processing.

enabling users to override fileService and delete a file

---

src/components/_classes/component/Component.form.js

You can see this by editing a form.
1. Open a a textfield component. You will see "Allow multiple masks"
2. Close and open a number component. You will not see "Allow multiple masks"
3. Close and re-open the textfield component. You will no longer see "Allow multiple masks"

Stop different component editforms from mutating each other.

---

src/templates/bootstrap/builderEditForm/form.ejs
src/templates/bootstrap/builderPlaceholder/form.ejs
src/templates/bootstrap/builderSidebarGroup/form.ejs
src/templates/bootstrap/datagrid/form.ejs
src/templates/bootstrap/file/form.ejs
src/templates/bootstrap/multiValueTable/form.ejs
src/templates/bootstrap/pdf/form.ejs
src/templates/bootstrap/pdfBuilderUpload/form.ejs
src/templates/bootstrap/sketchpad/form.ejs
src/templates/bootstrap3/builderPlaceholder/form.ejs
src/templates/bootstrap3/builderSidebarGroup/form.ejs
src/templates/bootstrap3/datagrid/form.ejs
src/templates/bootstrap3/file/form.ejs
src/templates/bootstrap3/multiValueTable/form.ejs
src/templates/bootstrap3/pdf/form.ejs
src/templates/semantic/builderSidebarGroup/form.ejs
src/templates/semantic/datagrid/form.ejs
src/templates/semantic/file/form.ejs
src/templates/semantic/multiValueTable/form.ejs
src/templates/semantic/webform/builder.ejs

This is related to #520 and #1639. The localisation
strategy using i18next which is described in
https://github.com/formio/formio.js/wiki/Translations
can only work if the text is actually passed to
i18next.t(). This change sends some additional
user-visible strings to i18next.t() for localisation.

Send user-visible text in templates through i18next.t() function

---

src/components/base/Base.js

When action type is "property", function applyActions does not update the "changed" variable.
Therefore, in the function attachLogic(), applyActions does not return true when action type is property and component is not redraw.

Fix apply actions when action type is property

---

gulpfile.js

Fixing the "Unable to find a readme for formiojs@4.2.5" message on the npm page

Release readme

---

src/WebformBuilder.js

The angular-formio lib reads the form definition from `instance.schema` on events, but after moving a field (with drag&drop) it read the previous definition since the event was emitted before the actual update of `instance.schema`.
You can test the issue at https://formio.github.io/angular-demo/#/forms/builder

Fix emit event on drop

---

src/Wizard.js

Moved the check if breadcrumb is clickable to the top nav instead of the buttons (next, previous). The option breadcrumbSettings.clickable doesn't related to the buttons (in my opinion). If you set the value as true then the top breadcrumb header is clickable but the buttons became un-clickable. 
Also passing the option into the template context so people can override the look at feel of the breadcrumb with that option

is breadcrumb clickable moved to top nav instead of buttons

---

src/WebformBuilder.js
src/components/_classes/component/Component.js

Passing attributes to the modal allows for CSS namespacing on the modal div. Necessary for including formio in a site which doesn't use bootstrap as the CSS framework.

Allow attributes to be passed to modal creation in the form builder

---

src/components/_classes/component/Component.js

This allows a user to use the form options to set the source url and default settings for third-party editors.

Allow editor source url and settings to be provided in form options

---

src/components/select/Select.js

Currently if a **Select Component** with the multiple flag set to `true` and no `defaultValue` set, it defaults to an empty string triggering a nonarray validation error.  This pull request sets an empty array as default value if no `defaultValue` is set.

Fixed Select default value when multiple is true

---

src/Wizard.js

Currently wizard checkData function performs validation checks before checking data, thus failing even when calculateValue is defined.  The order should be reversed and first check the component wizard data (thus triggering data evaluations) and then check the data's validity.

Fixed Wizard checkData validation order

---

src/components/number/Number.js

Fixes #2191 .
Typical delimiter or decimalSeparator characters for numbers (e.g. dot and comma) can occur directly in `[`...`]` character classes in regexps without problems.

Fix #2191: invalid identity escape in numberPattern.

---

src/components/editgrid/EditGrid.js

Related to https://github.com/formio/formio.js/issues/2024
When restoring a row data context, it sets the context global data. Unfortunately, on nested components it does not sets the values of its components.  This pull request sets the component's value if it is present in the row context, thus correctly initializing nested component's components.

Fixed EditGrid not setting Nested Components values on edit

---

app/examples/custombuilder.md

<div> tag should be terminated with </div> tag, not </formio>

Fix invalid html in example

---

src/components/form/Form.js

Not sure about side-effects, but this appears to fix the problematic behavior.  Fixes #1953 .

Fix github #1953: Override .defaultValue of subcomponents.

---

src/utils/utils.js

Flatpickr uses `U` for timestamps, but it doesn't get formatted in the submission object, since moment.js uses `X`.
https://github.com/formio/formio.js/issues/2242

Convert Flatpickr Timestamp `U` to Moment.js `X`

---

src/templates/bootstrap/builderEditForm/form.ejs

Move text outside of `<i class"fa"></i>` icon declaration

Fix Display of Help Link

---

src/components/select/Select.js

Fixed presence of selected value in options when search result is empty in lazy-load select with search query name

Selected value is in select options when query result is empty fix

---

src/Wizard.js

When wizard uses advanced logic to make pages conditional, the buttons don't update when the page shown.
this.currentNextPage is updated inside redrawHeader. The following comparison is always false
Issue can be seen here:
https://codesandbox.io/s/vigilant-panini-d6999
Select option A in combobox
-> Page 2 is added to wizard
-> Buttons are not updated

fix: wizard changing next page doesn't update buttons

---

src/components/select/Select.js

Init first api call for lazy-loading select if the initial value is provided to make it display a template with a correct label instead of initial value

Fix - Default value of selects are displaying IDs rather than the label

---

src/Webform.js

If set pristine of the Webform after checkData was called, when clearOnHide is called, rootPristine would be false and then the value would not be deleted
This also fix an issue with not working clearOnHide inside dataGrid

Fix clearOnHide while updating submission

---

src/Formio.js

The following methods have been added to interact with the project role endpoint:
- loadRoles
- loadRole
- saveRole
- deleteRole
The following properties are also registered:
- rolesUrl
- roleUrl (only when full role url is passed as path)
- roleId (only when full role url is passed as path)
Finally, changed a string regex search with a regex test method which is more efficient.

Added Role API methods

---

src/components/currency/Currency.js

Reverts formio/formio.js#2449
This breaks the currency tests. Please run them locally (since circleci is not working atm) to see yourself.

Revert "Fixed currency trailing zeros issue in currancy component"

---

types/formio.d.ts

To fix: 
error TS2339: Property 'use' does not exist on type 'typeof Formio'.

Add use(plugin) method for typescript

---

src/Webform.js

Labels are not currently translated when displayed at the top of the form

Fixed unstranslated component label in Webform

---

src/components/file/File.js

If webcam video stream is active and the component is destroyed, the video stream does not stop (see issue https://github.com/formio/formio.js/issues/2633).  
This is a simple fix which calls `stopVideo` when the component is destroyed just to make sure to stop any active video stream.

stop video stream on destroy

---

src/components/select/Select.js

This reverts a change in commit 2ebcb4fcf67e332c2ab81f9e03d16f21710ca91e which replaces items in a select menu when adding new items. We've found this causes a problem with one of our menus ever since this commit, whereby it does not populate as expected.
I have tested, and this remedies the issue, but please note I was not able to get unit tests to run (I was getting `Error: Not supported at requireOrImport`) - hopefully my suggestion here does not have any unwanted side effects :)

Don't replace choices when adding not found values

---

src/components/_classes/component/Component.js

This reverts a change made in https://github.com/formio/formio.js/commit/129e5c8fcc81195dd5318fd726cbb2b680d14444 and is a fix for https://github.com/formio/formio.js/issues/2613.

Don't skip validation for disabled components

---

src/PDF.js
src/Webform.js

Presence of this role in error section means screenreader announcements will get interrupted by error section announcement every time error section is redrawn, which should not be happening.

VPAT-314 Removed role alert from error messages container

---

src/Formio.js

This adds url encoding to request made to an API. By encoding url, users will be able to enter any character in Unicode and not have to be limited to just ASCII, as `atob` and `btoa` methods throws a DOMException if the parameter passed to it is not valid base64 (so any character not matched with this regex [A-Za-z0-9+/=] will throw error). Encoding the url will escape any character not valid in  base64 with its base64 counterpart. 
Fix #2732

Encode uri before a request

---

src/Webform.js

Fix (Webform): reset button click didn't hide validation error messages

FJS-908 Cancel action on button does not clear out the validation warning

---

src/components/_classes/component/editForm/utils.js
src/components/_classes/component/editForm/utils.spec.js

Ignore editForm api key validation? [#2280](https://github.com/formio/formio.js/issues/2280)
Now we can pass a overrideEditForm flag in options. example:
```
const options = {
builder: {
data: false,
premium: false,
},
editForm: {
textfield: [
{
key: 'api',
ignore: false,
components: [
{
key: 'key',
overrideEditForm: true,
validate:{}
}
]
}
]
}
};
```

Improve(editFormUtils): add option to override editForm builder options

---

src/Webform.js

We need to split metadata setter to separate method because customers sometimes need to set metadata without calling ``submitForm`` method.

split metadata setter into separate method

---

types/formio.d.ts

Found when using the bootstrap3 plugin.

use() method should be static

---

src/components/file/File.js

Set blob.name to file.name so that the original naming convention is used.
Removed unused "evt" param'.
Removed unnecessary console.log().

Correct image names on S3 upload

---

src/components/file/File.js

Resolve issue with formio/formio.js#2874 whereby this.upload couldn't be invoked due to incorrect scoping. 
- Changed syntax to arrow function to ensure correct binding of 'this', allowing the upload function to be called from within reader.onloadend.
- Declare 'reader' and 'blob' as block scoped variables.

Update File.js for S3 image uploads

---

src/components/file/File.js

When file component is set up to use private download (i.e. when using [formio/formio-upload](https://github.com/formio/formio-upload)), if the component is set to display file as image, the image does not load as the private property in `fileInfo` is not set (thus setting an invalid file url in the image src).
When displaying file as image, the image `src` attribute is set here:
https://github.com/formio/formio.js/blob/54b34f234ee5948592986decebd4eb09b161d643/src/components/file/File.js#L441-L443
Which in turn calls the `loadImage` method.  This pull request adds a private download check so that the component's file service returns the correct file download url.

Added private download check for image load

---

src/Element.js

Manually tested on all the components. Does not seem to break anything, the classes are set and removed correctly for every component.

Fix (Element): methods for adding and removing classes caused error for angular FormControl

---

src/Webform.js
src/Webform.unit.js

We've been trying to render multiple instances of the same form in different languages, but after digging around I discovered that Webform mutates the imported `i18next` module in a bunch of places rather than using its own instance (`this.i18next`), which can be passed in via `options.i18next`.
This adds a test for mutation of the imported `i18next` when Webform gets `options.i18next`, and updates the Webform class to always refer to its own instance.

Use this.i18next instance instead of imported module

---

src/templates/bootstrap/input/form.ejs

My team discovered recently that they were adding localizations for field prefixes and suffixes but not seeing them translated. Turns out that the `input` template wasn't wrapping the prefix and suffix text in `ctx.t()`, so they're un-localizable!
Here's a fix. ❤️

Enable localization of field prefix and suffix

---

src/Formio.js

Currently `Formio.setToken` returns either void or a Promise, making it bothersome and having to wrap the setToken call in a promise in order to make it consistent.
This makes sure to always return a Promise and return either `null` (if token has been deleted) or the current user, always updating if the current user is `null`.
Other small fixes includes:
* `static get token()`: code refactoring
* `static set token(token)`: removed return value

added consistent return for setToken

---

src/Element.js
src/Webform.js
src/Webform.unit.js
src/components/_classes/component/Component.js
src/i18n.js

This adds a new `alertMessage` localization string for the messages listed in the alert element displayed when validations fail:
The default value was `{{label}}. {{message}}`, but I've swapped out the period for a colon (`{{label}}: {{message}}`) since it sounds like [the period was a typo](https://github.com/formio/formio.js/issues/2627#issuecomment-630862768) anyway. The string gets `label` and `message` placeholder values (which can easily be added to [here](https://github.com/shawnbot/formio.js/blob/4574491b6eab9ef2d112ac667686447fb4570c3b/src/Webform.js#L1185)). I've included a test that localizes it as just `{{message}}` so that the text is just the validation message without the redundant component label, which I believe addresses @darabi's suggestion in …

Localize alert messages, simplify t() methods

---

src/PDFBuilder.js
src/WebformBuilder.js

Add this flag to the predefined components to skip the modal popup.
Referring to the example:
https://formio.github.io/formio.js/app/examples/custombuilder.html
components: {
firstName: {
title: 'First Name',
key: 'firstName',
icon: 'terminal',
schema: {
label: 'First Name',
type: 'textfield',
key: 'firstName',
input: true,
**noNewModal: true**
}
},...
The components under the custom group can have the property noNewModal = true if you want to skip the modal.
Any other component that doesn't have the flag (ex. basic, data, etc) keep their regular behavior (modal popup when dragged/dropped on the form)

noNewModal = true to skip new component modal

---

src/WizardBuilder.js

Reverts formio/formio.js#2776
This caused an issue where wizard pages would override the first page if the panels have the same key (legacy wizards such as https://humanresources.form.io/benefits)

Revert "Fix (Wizard): page title in navigation is not updated"

---

README.md

The example that was provided use the wrong script file, causing errors.

Fixed the Javascript SDK example

---

src/WebformBuilder.js

When you create a [custom builder](https://formio.github.io/formio.js/app/examples/custombuilder.html) with predefined components, you want to preserve their key. When they are dropped in the form, their key is regenerated.
This PR adds a line to retain the key if provided

Retain key if provided when drag/dropping an element

---

src/components/datetime/DateTime.js

Flatpickr doesn't do anything with the `language` option passed here:
https://github.com/formio/formio.js/blob/60a9cb2c7a7107c1f2a83ed4f93766e9d95dde91/src/components/datetime/DateTime.js#L93
It does, however, [respect the `locale` option](https://flatpickr.js.org/localization/).
Fixes #3130.

Pass "locale" (not "language") Flatpickr setting

---

src/components/select/Select.js

Fix check for nested fields regex (positive lookbehind is not supported and throws a syntax error in IE)

Fix formio.js file not loading in IE

---

src/templates/bootstrap/field/align.ejs

I think this must be a typo. The class "filed-content" is used nowhere.

Fix typo in class name in align.ejs.

---

src/components/_classes/component/Component.js

Hi!
I think labelWidth and labelMargin should allow 0 as a value. At least labelMargin should work with 0.
~~My changes also constrain the properties to a number because a string compared to a number ("..." >= 0) will always be false.~~
Edit: actually never mind, because of implicit conversion "2" >= 0 gives true.
What do you think? :)

Allow 0 for labelWidth and labelMargin.

---

src/components/_classes/componentModal/ComponentModal.js
src/components/editgrid/EditGrid.js

Clicking on the button "Yes, delete it" will drop all changes not persisted. I think this should be a btn-danger rather than a btn-primary.
For your consideration.

Style button to delete data in confirmation dialog as btn-danger

---

src/Formio.js

This PR enables override of URL & Method from the `staticRequest` hook. The very same change could be done to the `request` hook if desired.
See #3565

Allow override of url & method in staticRequest hook

---

src/components/tabs/Tabs.js
src/sass/formio.form.scss

@travist for now made this way, it looks more distinguish to me.
When the tab with error gets active, the color becomes more red.
But can make it the way you proposed, with an asterisk.

Tabs: indicate some of components on tab is invalid

---

src/WebformBuilder.js

Fixing FormIO React [item #334](https://github.com/formio/react-formio/issues/334)
Added 'askForComponentsRemoval' parameter to FormBuilder options. When set, there's always a question asked before removing any component from the FormBuilder.
Otherwise, it behaves like previously, so only asking when removing "grouping" containers (columns etc.).

Asking for components removal (React FormIO #334)

---

src/Webform.js
src/Webform.unit.js

The Webform class lacks a `language` getter to complement the setter. This adds one!
Because the language setter is asynchronous—which seems [sketchy](https://github.com/tc39/proposal-async-await/issues/82), IMO—I figured it's better to have the getter return `this.options.language` rather than `this.i18next.language`, which may not reflect the value provided until `changeLanguage()` resolves.
One case that this doesn't account for is if you've provided your own `i18next` instance in the form options. In that case, `this.options.language` may not equal `this.i18next.language`. So maybe, if [i18next.changeLanguage()](https://www.i18next.com/overview/api#changelanguage) sets the internal value used in the [language getter](https://www.i18next.com/overview/api#language) immediately, it might …

Add Webform language getter

---

src/components/selectboxes/SelectBoxes.js
src/components/selectboxes/SelectBoxes.unit.js

The selectboxes component has some hard-coded validation messages for `minSelectedCount` and `maxSelectedCount`. This change wraps both the hard-coded messages and the custom validation messages (`minSelectedCountMessage` and `maxSelectedCountMessage`) in `this.t()` so that they're passed through the localization layer. This should make it possible to localize them like so:
```js
Formio.createForm({
components: [
{
type: 'selectboxes',
values: [
{ label: 'Option 1', value: 1 },
{ label: 'Option 2', value: 2 },
{ label: 'Option 3', value: 3 },
{ label: 'Option 4', value: 4 }
],
validate: { maxItemCount: 2 }
}
]
}, {
i18n: {
'You can only select up to {{maxCount}} items.': 'Please select {{maxCount}} items or fewer.'
}
})
```
I've added tests for both the default messages and the custom …

Localize selectboxes validation messages

---

src/Formio.js

Should have been included in https://github.com/formio/formio.js/pull/3578 but here goes.
This PR enables override of URL & Method from the request hook.

Allow override of url & method in request hook

---

src/components/_classes/component/Component.js

Select component throws an error in some cases because it declares its triggerUpdate method which is used in visible setter during init().

Fixed an error occurred when trying to add Logic row

---

src/components/select/Select.js
src/components/select/editForm/Select.edit.display.js

Reverts formio/formio.js#3059
Found out that now the style related to table `overflow` (also mentioned [here](https://github.com/formio/formio.js/pull/3617)) fixes the issue related to the work I've done for that ticket.
So, no more need in this changes.

Revert "Feat/uip 239 select options overlayed"

---

src/WebformBuilder.js

This changes the the “Edit JSON” dialog so it uses the compact `schema` value
without all the default settings.

Use schema instead of component for Builder Edit JSON dialog

---

src/Element.js

Reverts formio/formio.js#3577
This one is about converting lodash to object with only methods listed in jsonlogic/operators in order to be supported with protected-eval plugin.
Moving this functionality from formio.js to protected-eval itself.

Revert "Element: convert lodash to object in evalContext"

---

src/Element.js

Method`.off()` of `Element` is removing all listeners for a single event, and we need a way to remove a single listener for a single event as the exact opposite to `.on()`, so that we added `.offOne()`.
The reason behind it is that we want to attach a listener to a single event, and remove it when cleanup of one part without removing all other listeners.
This is particularly important when using `form.io` with `React` -- we want to attach and detach event listeners in `useEffect()` according to the changes of the dependency array.
The example code looks like below:
```jsx
const MyComponent = ({ form, prop }) => {
useEffect(() => {
const doOnChange = () => {
// Do something according to prop
};
form.on("change", doOnChange);
// Clean up
return () => {
form.offOne("change", doOnChange);
}; …
```

Add .offOne method to remove one listener for a certain event

---

src/components/select/Select.js

Since thriggerUpdate() uses debounce  (I assume, that it is for handling user's input), when setValue() is called, this.itemsLoaded is equal to the initial promise which was created while init(). Changing this.triggerUpdate() to this.updateItems() fixes that issue and this.itemsLoaded is equal to the promise created inside updateItems()

FIO-1391: Fixes an issue where value of lazy loading Select is not shown on the Edit tab

---

src/components/select/Select.js

Fixes 2 issues: 
1. When add Advanced logic and in Actions select Type = Property, Set State = False, then save Actions row and Logic row, reopen both rows and see that Set State is empty 
2. When create a Select component with values like {label: False, value: false} and set 'false' as a default value, the default value is not shown.

FJS-837: Fixes an issue where 0 and false are considered as empty values for Select 

---

src/components/form/Form.js
src/components/form/editForm/Form.edit.form.js

That issue appears in cases when form was imported or deployed from the older version of builder where revision of the Nested Form was specified using 'formRevision' property. 
Forms that has 'formRevision' property set to any number and 'revision' set to '' (which is default and means to load the current revision), the current version of the form is loaded on the front-end side and the one which 'formRevision' property refers to is loaded on the server-side (eg, for validation)

FIO-1068: Fixes an issue where revision of the Nested Form loaded on the front-end side differs from the one which loaded on the server-side

---

src/WebformBuilder.js

This leads to the next issues:
1) When you have Select Boxes with Max Checked validation and select the max amount in Form Builder component's Preview, the rest of the select boxes are disabled, but if you click on the label of the option, you can select the value.
2) Sometimes when you change the value inside preview (Select Boxes, Checkbox, Radio), the Default Value is also changed.

FIO-1501: Fixes an issue where Preview component and Default Value component in Builder have the same ids

---

src/components/editgrid/fixtures/comp9.js
src/utils/formUtils.js

Probably, a long time ago only **Layout** components included **components** property. But now there are a lot of components which are **input components** and include **components** property as well (EditGrid, DataGrid, Address, Container, DynamicWizard, Tagpad, etc.). And eachComponent does **not call a callback** function with such components if there is not 'includeAll' flag, because it considers them **as layout components** which is not true.

FIO-2694: Fixes an issue where eachComponent considers nested components as layout components

---

src/components/_classes/component/Component.js
src/components/editgrid/EditGrid.js
src/components/editgrid/templates/header.ejs

Fix edit grid not translated column labels. Bind translation function to any interpolated string.

Fix edit grid not translated column labels. Bind translation function to any interpolated string context.

---

src/components/_classes/component/editForm/Component.edit.validation.js

It would be nice to be able to set this in the builder. I decided for a simple JSON input, as I didn't want to hunt for all possible options you can set here and then forget some. Also this won't create any additional noise in the `schema`, whereas a `container` with a `textfield` for every option would.

Add option for errors to builder

---

src/Webform.js

#3666 made `resetValue` call `rebuild` in `Webform.js`, however this is still not enough as a rebuild does not cause elements with calculated values to be recalculated. In the worst case if the user clicks on a reset button and then immediately submits the form this will result in fields which are always supposed to be calculated being submitted uncalculated. In other cases this may still leave the form in an inconsistent state after a reset. Introducing a `onChange` here fixes this and intuitively makes sense, since a reset does indeed cause a change in the form.
It should be noted however, that `resetValue` in `Component.js` explicitly does not cause a change event:
https://github.com/formio/formio.js/blob/f6d2e2177992b6e6ee8561ea75c7efc8b3f6416e/src/components/_classes/component/Compone …

Call onChange on resetValue in Webform

---

src/components/editgrid/EditGrid.js

Add aria-label attributes to make validators happy.
I'm not sure if this is the only place where the template needs to be modified.
Also is interpolating with `${this.t('Edit row')}` correct, or should it rather be `{{ t('Edit row') }}`?

Add aria labels to edit/remove row buttons.

---

src/components/_classes/component/Component.js

It's impossible to define custom "modules" settings if it's always overwritten by `{table: true}`.

Override instead of overwrite modules setting for Quill.

---

.eslintrc.json
.mocharc.js
package.json
src/Webform.unit.js
src/components/_classes/component/Component.js
src/widgets/CalendarWidget.js

This PR improves the accessibility of _most_ form inputs by updating the `aria-invalid` attribute to `true` or `false` whenever the `is-invalid` class is added or removed. This called for a new Component method, `setElementInvalid()`, which adds or removes the `is-invalid` class and sets `aria-invalid` in one go.
The only mention of the `is-invalid` class I could find in the tests was for the calendar widget, so I've updated those tests to also assert the correct value of `aria-invalid`. Ideally there would be invalid state tests for every component, but I think it's safe to say that if `is-invalid` is working as a style hook for invalid elements (and I've fixed this in all of the right places) all of the cases should be covered.
I've also introduced a Mocha config file in `.mocharc.js` …

Add aria-invalid attribute, improve test ergonomics

---

src/components/select/editForm/Select.edit.data.js

This PR resolves issue #4236, where the ClearOnRefresh and RefreshOn elements are not present for SelectsCustom Data Source Type.
I added 'custom' data type to the list of allowed data sources in the condition of when these options should be shown.

FIO-4236: ClearOnRefresh and RefreshOn for Custom Data Source Select Elements

---

src/components/_classes/component/Component.js

Fix for issue https://github.com/formio/formio.js/issues/4190

Fixed tooltip not escaping double quotes

---

src/components/select/Select.js
src/components/select/Select.unit.js
src/components/select/editForm/Select.edit.data.js

When querying endpoints for select options and we have server side filtering enabled (searchField is defined), the requests are not debounced which results in spamming the endpoints.
This PR introduces a new builder option to set a debounce timeout value, between 0 and 1s.

Select component - debounce option for server side filtering

---

src/components/button/Button.js

Steps to replicate:
1. Create a form
2. Add multiple nested forms to it
3. Make sure that at least one component in each form has a validation (e.g. Required)
4. Make sure that the Submit button of the parent form has a Disable on Invalid checked
5. Go to the Use tab
6. Fill all the fields of the first child form to make the valid
(Fields of the second nested forms are still not filled and invalid)
AR: Submit becomes enabled as soon as you fill the first form with valid values
ER: Submit should stay disabled until all the fields and nested forms of the parent form are filled with correct values.

fix(Button): disableOnInvalid does not work when have multiple nested forms and make one of them valid

---

src/components/button/Button.js

Reverts formio/formio.js#4228
This breaks the test @ https://github.com/formio/formio.js/blob/master/src/components/editgrid/EditGrid.unit.js#L561

Revert "fix(Button): disableOnInvalid does not work when have multiple nested forms and make one of them valid"

---

src/utils/utils.js

An HTML component with <svg ...><path .../></svg> content broke the whole form.

FIO-3713: fix(Utils): an error occurs if HTML comp has an SVG tag with PATH tag inside it

---

src/Embed.js

When a document is asynchronously rendered, a document.write() from a different source (eg a script) is ignored and results into following warning. 
Also the embedding of the form fails with an error `Uncaught TypeError: p is null`.
Warning: `A call to document.write() from an asynchronously-loaded external script was ignored.`

Fix form embedding in async DOM (replace document.write() by DOM insert)

---

src/components/select/Select.js

It's another approach to fix 4364, because part of previous fix in formio-pdf broke Signature submission edit on pdf.
Removing that failing part here: https://github.com/formio/formio-pdf/pull/138

FIO-4595 | 4364: Fixes Select with URL keeping default value on pdf submission

---

src/components/_classes/multivalue/Multivalue.js

- Surrounded saveCaretPosition function in try/catch as Safari throws an exception during this method.

FIO-4419: Time fields in Safari

---

src/components/editgrid/EditGrid.js

In #3580 `invalidRowError`, `invalidRowsError` and `unsavedRowsError` have been made translatable, but it should also be possible to customize them on a per component basis.

Allow customization of edit grid error messages

---

.gitignore
src/components/button/Button.js

On the submit button, the loader icon is removed at an unexpected event. This fix would solve the issue

fix button loader icon removal at an unexpected event

---

src/Wizard.unit.js
src/components/_classes/nested/NestedComponent.js
src/components/container/Container.js
test/forms/wizardTestFormWithNestedComponents.js

https://formio.atlassian.net/browse/FIO-5511
Previously, forms with nested components (in particular, a container component) would conditionally show correctly based on a contextual `row` property but would not validate. This was due to the `row` property not being properly tied to a container component's context. This PR attempts to alleviate this problem by setting `row` to the component's `dataValue` property (or, in other words, keys into the submission data by its own property key) so it can be validated correctly if it has custom conditionals.
Although I'm fairly certain this is a minor change, this is my first renderer ticket, so I'm nervous about "unknown unknowns" here - I've requested a review from @TanyaGashtold to make …

FIO-5511: ensure contextual row data is validated correctly for nested components

---

src/components/_classes/input/Input.js
src/components/password/Password.js

https://formio.atlassian.net/browse/FIO-5853
Added ability to disable autocomplete form using form settings
https://github.com/formio/formio-app/pull/1343
manually

FIO-5853 added setting to disable autocomplete

---

src/components/select/Select.js

https://formio.atlassian.net/browse/FIO-5963
Preset select component submission value with value property setting to improve pdf generation and do not wait until request will be executed.
Not possible created automated tests because issue only reproducible on pdf download and not reproducible on formio-viewer. So created several forms with select component with different configuration on local env and verified correct rendering.

FIO-5963: Preset submission value with value property before request for pdf

---

src/components/select/Select.js
src/components/select/Select.unit.js

https://formio.atlassian.net/browse/FIO-5685
Previously, Data in Select with Value Property as {Entire Object} was set as a string. This PR replaces this behavior by removing JSON.stringify method for value. Added the ability to use data in Select Component   with Value Property as {Entire Object} as an object, for example in Calculated Value.
I added automated tests, including tests for Select Component with Value Property as {Entire Object}

FIO-5685 Data in Select with Entire Object is set as an object

---

src/CDN.js
src/CDN.unit.js

https://formio.atlassian.net/browse/FIO-6220
*Previously, CDN class lack some methods to override CDN ursl for a specific library. This PR adds that method as well as methods to set specific library version and remove overrides.*
*This PR doest not depend on any PRs.*
*I added automated tests to cover all cases.*

FIO-6220: added some new methods to CDN class

---

src/Formio.js

https://formio.atlassian.net/browse/FIO-6621
*Previously, formio.js had CDN url set to https://cdn.form.io by default and that didn't depend on version. With this PR CDN url will be https://cdn.test-form.io if the version is rc*
*This PR doesn't depend on any PRs.*
- [] New and existing unit/integration tests pass locally with my changes

FIO-6621: added rc version determination for cdn url

---

src/components/textfield/TextField.js

https://formio.atlassian.net/browse/FIO-6229
Previously, if  html string was entered into the TextFIeld Component with Input Type 'plain', then the value for this input was displayed as html in the Data tab . Example below
After the changes, if the TextField Component has property Input Type = 'plain' , then this component will be displayed as a string in the Data tab. The same as on the View tab. Example below
*no*
*manually, all automated tests were passed locally*

FIO-6229 fixed displaying html value on Data tab for inputFormat plain

---

src/Webform.js

https://formio.atlassian.net/browse/FIO-6148
added event that allows to catch loaded submission before it is set. Event is needed for premium to set correctly esign data.
https://github.com/formio/premium/pull/218
very small change, tested manually

FIO-6148: fixed an issue where boxsign returns an error when editing submission

---

src/Formio.js
src/Formio.unit.js

If the url request starts with a '/' it can be assumed that it should go to the base url.
If the url request starts with a '/' it can be assumed that it should go to the base url.
None
I added automated tests to cover all cases

Ensure that url requests to relative root should prepend the base url.

---

src/components/file/File.js

https://formio.atlassian.net/browse/FIO-6339
originalFileName is included to the template direclty, so we need to escape </> symbols, to prevent adding additional HTML code to the form

FIO-6339: Fixes an issue where self-XSS is possible through the File upload component

---

src/Embed.js

https://formio.atlassian.net/browse/FIO-6431
*Changed Quick Inline Embed link for hosted. Now, when using the Quick Inline Embed link, Premium Components are displayed and work as in the portal*
*https://github.com/formio/formio-app/pull/1399*
*manually*

FIO-6431 fixed display of premium components using Quick Inline Embed link

---

src/displays/webform/Webform.js

With our components that aren't using a debounced onChange when an existing submission is edited we're getting an onChange the sets it to empty values. I found it was because `submission` was defaulting to an empty data.

init() Submission with Existing Data

---

src/components/day/Day.js
src/components/day/Day.unit.js

https://formio.atlassian.net/jira/software/c/projects/FIO/issues/FIO-6468
Fixed issue with default value in the day component
I added automated tests to cover all cases

FIO-6468-Custom_validation_on_Day_component_confusing_Day_and_Year

---

src/PDFBuilder.js

https://formio.atlassian.net/browse/FIO-6512
*fixed drag and drop functionality on PDF first form when using Mac and Chrome browser. If "drop" event is not emitted in the overlay above the iframe, "dragEnd" event is used instead*
*manually*

Fio 6512 cannot drag and drop components on to pdf first forms using mac

---

src/components/checkbox/Checkbox.js
src/components/checkbox/Checkbox.unit.js
src/components/checkbox/fixtures/comp4.js
src/components/checkbox/fixtures/index.js

https://formio.atlassian.net/browse/FIO-6009
*If the checkbox is set as a radio and there is a corresponding content field which should display conditionally, then after clicking on the checkbox,  the conditional content field shows. And this is the correct behavior. But after deselect the same checkbox, the content field was not hidden. This has been fixed and now when checkbox is deselected, the corresponding component is hidden according to Advanced Conditions logic*
*no*
*added automated tests*

FIO-6009 When checkboxes set as radio, conditional logic is triggered upon deselect

---

src/components/radio/Radio.js
src/components/radio/Radio.unit.js

https://formio.atlassian.net/browse/FIO-5318
Earlier radio attributes were showed incorrect during performance. This PR fixes this behavior.  
no dependencies.
I added automated test to cover failing case

FIO-5318: Fixes wrong attributes appearing for Radio component during performance

---

src/components/_classes/component/editForm/Component.edit.conditional.js
src/components/_classes/component/editForm/Component.edit.data.js
src/components/_classes/component/editForm/Component.edit.validation.js
src/components/_classes/component/editForm/utils.js
src/components/datetime/editForm/DateTime.edit.date.js
src/components/datetime/editForm/DateTime.edit.display.js
src/components/form/editForm/Form.edit.data.js
src/components/unknown/editForm/Unknown.edit.display.js
src/templates/bootstrap/builderEditForm/form.ejs
src/templates/bootstrap5/builderEditForm/form.ejs

https://formio.atlassian.net/jira/software/c/projects/FIO/issues/FIO-6345
Added attribute rel="noopener noreferrer" to docs/external links
The **noopener** is needed to enhance the security of your website and prevent other websites from gaining access to your page (through the browser session). The **noreferrer** is used to protect referral information from being passed to the target website and this also hides referral traffic in Google analytics
Tested locally

FIO-6345: Add rel=noopener to Portal Application Links to Docs / External Links

---

src/components/textarea/TextArea.js
src/components/textarea/TextArea.unit.js

https://formio.atlassian.net/browse/FIO-6582
When `textarea` components have the `autofocus` param enabled, the renderer will wait for the `render` event to emit and focus the element by keying in on `this.component.editors[0]`. However, `textarea` components have an additional asynchronous initialize step, all of which are stored in the `this.editorsReady` array. This PR modifies the `textarea` component to wait for the editor to be ready before it attempts to focus it.
n/a
added an automated test around the focus() instance method and tested manually
__My local tests are not passing, but a look at the last 5-6 PRs for this repo make me think they haven't been passing for a while. I'm going to look into this next and fix them, but IMHO we need to make sure they're passing on every PR__

FIO-6582: 

---

src/components/radio/Radio.js
src/components/radio/editForm/Radio.edit.data.js

https://formio.atlassian.net/browse/FIO-6761
*The 'Storage type' parameter has been removed from the Radio component settings*
*no*
*All automated tests were passed locally*

FIO-6761 removed Storage Type setting for Radio

---

src/Webform.unit.js
src/WebformBuilder.js
src/WebformBuilder.unit.js
src/Wizard.unit.js
src/WizardBuilder.js
src/WizardBuilder.unit.js
test/forms/formWithFormController.js

https://formio.atlassian.net/browse/FIO-4232
Before we did not pass form controller when creating the wizard form in builder mode. I have added it.
Manually + unit tests are added.
No new tests fail, except those that fail on the master branch.
https://github.com/formio/formio-app/pull/1434

FIO-4232: fixed an issue where form controller does not work for wizard forms in builder

---

Changelog.md
src/sass/formio.form.builder.scss

https://formio.atlassian.net/jira/software/c/projects/FIO/issues/FIO-6800
Fixed issue where select dropdowns go behind the component settings modal
I chose this solution because after investigating the issue I realized that we use the overflow property for parents blocks and this hides our dropdown selector and we cannot refuse to use property overflow
Tested locally 
Attached video https://formio.atlassian.net/browse/FIO-6800?focusedCommentId=46024

FIO-6800: fixed issue where select dropdowns go behind the component settings modal

---

src/components/_classes/nested/NestedComponent.js

https://formio.atlassian.net/browse/FIO-6600
*Previously, after drop a new component, modal window with component settings for the PDF first form did not open. The issue has been fixed. Now when User adds or clicks on a component, a modal window opens.*
*no*

FIO-6600 fixed opening of the settings window

---

src/components/editgrid/EditGrid.js

https://formio.atlassian.net/browse/FIO-6654
*Fixed UI issue related to Tab with Settings for  Simple condition with Checkbox or Select condition. Previously, the value for simple conditions was saved, but the edit row was reopened. Now the value for simple conditions are saved and the window opens only after click the edit button*
*no*

FIO-6654 fixed UI issue with Checkbox condition

---

src/components/select/Select.js
src/components/select/Select.unit.js

https://formio.atlassian.net/browse/FIO-5398
This PR adds escape for RegExp special characters in Select component search field.
None
I've added unit test + manually

FIO-5398: Fixes special characters not escaped in regex is Select search field

---

src/components/textarea/TextArea.js
src/components/textarea/TextArea.unit.js

https://formio.atlassian.net/browse/FIO-6582
My previous PR (#5128) didn't take into account that readOnly forms will not bother to instantiate the editors, so we should check for the value to be populated with a promise before execution
n/a
Added a test to cover readOnly forms

FIO 6582 - fix bug in auto-focused TextArea components

---

src/Webform.unit.js
src/components/_classes/component/Component.js
test/forms/calculateValueOnServerForEditGrid.js

https://formio.atlassian.net/browse/FIO-6862
There was a problem that for some form configurations `dataValue` would never match `calculatedValue`, so that `calculateComponentValue` would go in loop assuming that component value has changed.
This PR adds changes that make `dataValue` be eventually set to equal `calculatedValue`, preventing loop calls.
1) When any component is created, the Component.js constructor checks if it has the value and should either set default value or maintain current `dataValue`. Howewer, the check inside `hasValue` method didn't take into account that we might have `undefined` value set for component. So if this situation happened, not the default value would be set and eventually the whole key-value …

FIO-6862: Fixes some cases when component value is calculated in loop causing stack overflow

---

package.json
test/forms/helpers/testBasicComponentSettings/tests.js

https://formio.atlassian.net/browse/FIO-6895
https://formio.atlassian.net/browse/FIO-6894
*Changed the version of i18next. After adding deepFind function (v22.14.13) to the i18next library, there is an issue with incorrect interpolation for falsy values. When using a version of i18next library higher than 22.14.12 (not related to the formio.js version), different results are received for interpolation with the same condition. Example below:*
```
i18next.init({
lng: 'en',
keySeparator: '.|.',
resources: {
en: {
translation: {
'key': 'Label {{data.number}}'
}
}
}
})
const res1 = i18next.t('key', {data: {number: 0}})
const res2 = i18next.t('key', {data: {number: 5}})
console.log(res1, ' - res1')
console.log(res2, ' - res2')
```
*Before version 22.14.12, interpolation works as expected*
*no* …

FIO-6895 fixed interpolation for falsy values

---

src/Wizard.js

https://formio.atlassian.net/browse/FIO-4809
Since we started using native formiojs validation on the server side, the values of suffix/prefix components were cleared during it because we don't use fromSubmission flag when set value to the form for validation on the server side. 
I created a separate PR with tests to the formio library, since it is related to the server-side  https://github.com/formio/formio/pull/1571

FIO-4809: Fixes an issue where value of Wizard suffix/prefix components will be deleted during validation on server

---

src/WizardBuilder.js
src/WizardBuilder.unit.js
src/sass/formio.form.builder.scss
src/templates/bootstrap/builderWizard/form.ejs
src/templates/bootstrap5/builderWizard/form.ejs

https://formio.atlassian.net/browse/FIO-7030
When we added an ability to change pages order by dragging them, we put Add Page button to a separate flex container to prevent it from being drugged/prevent dropping other pages after Add Page button, but that caused visial issues. I returned the layout back and prevented Add Page from being dragged/other pages from being dropped after it by moves/accepts functions passed to the dragula options.
For now only manually, cuase this feature does not have any tests yet and I need to figure out how to write tests with dragula.

FIO-7030: Fixes an issue where Wizard pages are displayed in one line in the for builder

---

src/components/textarea/TextArea.js

https://formio.atlassian.net/browse/FIO-7049
*Previously, when adding a component to the form, the component settings filled in via ACE editor were filled with the default value. For example:*
```
"errors" : "\"\"",
"validate" : {
"json" : "\"\""
},
"conditional" : {
"json" : "\"\""
},
```
*This led to incorrect behavior of the component. This PR replaces this behavior by adding an additional check for the builder mode*
*no*

FIO-7049 fixed data populating in the Data Table

---

src/components/textarea/TextArea.js
src/components/textarea/TextArea.unit.js
src/components/textarea/fixtures/comp4.js
src/components/textarea/fixtures/index.js

https://formio.atlassian.net/browse/FIO-7049
Also its a replacement for the https://formio.atlassian.net/browse/FIO-7049 original fix (cause the original fix works only in builder)
Previouly, we had an issue where on the 'Reset' event, textareas  with rich text editors were not cleared. The dataValue property was empty, but HTML elements of the rich text editors were keeping the value. This issue was fixed by adding a condition _|| (value === '')_ to the setValue method, but this caused another issue where empty value ("") was stringified (which results in "/"/"") inside setConvertedValue method for ACE editor with saveAs JSON setting. That caused some issues like the conditional function of the page panel settings giving the wrong false result and an issue with Data Table. So I replaced …

FIO-7054: Fixes an issue where after saving Wizard Panel settings, some of them disappear

---

src/components/file/File.js

Resolve Gatsby SSR build error.
"navigator" is not available during server side rendering.

Resolve Gatsby SSR build error.

---

src/components/resource/Resource.js
src/components/resource/editForm/Resource.edit.display.js
src/components/tree/Tree.form.js
src/components/tree/Tree.js
src/components/tree/editForm/Tree.edit.display.js

https://formio.atlassian.net/browse/FIO-6659
*Tree and Resource components are hidden from builder. Added deprecation warning- If a user clicks edit on an existing Tree or Resource component*
*no*
*manually*

FIO-6659 added warnings for Tree and Resource

---

test/forms/conditionalDataGridWithTableAndRadio.js

https://formio.atlassian.net/browse/FIO-6950
*Fixed a warning that appeared when running tests for Webform.unit.js. CustomConditional for inspectionDataGrid was remuved because there is no component with key reliabilityAndMaintenanceForms. Now the test works as expected, all checks pass and no warnings appear*
*no*

FIO-6950 fixed test

---

src/components/file/File.js
src/components/file/editForm/File.edit.file.js
src/templates/bootstrap/file/form.ejs

This adds a new `capture` option to file fields, which allows a mobile device to open the camera or microphone directly in [capture mode](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/capture). This offers more flexibility over the current `webcam` setting as it lets the user configure which device to launch (camera, video, microphone- based on `filePattern`) and specify front or rear device, on supported platforms (iOS). Capture can be used alongside webcam and is ignored on desktop.
While working on this, I also tried to tidy up the file input a bit, removing the "Drop files to attach" label on mobile and adding some icons to the link buttons.
```js
{
type: "file",
label: "My Photos",
key: "photos",
storage: "base64",
image: true,
capture: "environment",
filePattern: …
```

Add capture option to file fields

---

src/components/_classes/multivalue/Multivalue.js

#1662 Additional fix for the error "The input element's type ('email') does not support selectionStart"
Fix for Chrome 49.

#1662 Additional fix "The input element's type ('email') does not support selectionStart"

---

src/providers/storage/indexeddb.js

The indexedDb storage provided is hardcoded to require version 3 of a database. 
Removed the optional version parameter to allow the storage provider to write to any version of an indexedDb database

remove pinning of db version

---

src/components/button/Button.js

interpolate redirectURI in oauth settings so it could construct the redirectURI dynamically.
for example, redirect to different subdomain but having the same folder path in different project stages.
eg. {{window.location.origin}}/test/
another example is constructing the redirectURI using data object.
eg. {{data.myUrl}}

interpolate redirectURI in button oauth config

---

src/Webform.js

When the form submission request results in a 4xx or 5xx response, showErrors() is invoked with a message string. This is no longer supported and results in an exception, causing script abortion without any feedback to the user.
This PR removes the showErrors() call as it seems to be a leftover from a previous implementation that supported string arguments. The message is still displayed via setAlert().
I also cleaned up the error handling code by deduplicating the message composition code.

Fix and cleanup form submission api error handling

---

src/components/select/Select.js
src/components/select/Select.unit.js

Fixing a bug where the choices.js's removeItemButton (the x button in the screen shot) is being shown for the placeholder option.
According to the [choices.js readme](https://github.com/Choices-js/Choices#placeholder). The value of the placeholder option should be set to `''`. When the value is set to `''` the remove button is hidden.

Hide removeItemButton on choicesjs select when the placeholder is selected

---

src/utils/utils.js

Currency can be an empty string value as seen in #4494 
Changed to provide a default value when passed falsy value

fix: falsy currency defaults to USD

---

src/components/signature/Signature.js

https://formio.atlassian.net/browse/FIO-3448
Only manual testing, since it is only for PDF forms

FIO-3448: Fixed an issue where Keep overlay aspect ratio feature of the Signature component in PDF form does not work

---

src/components/datagrid/DataGrid.js

https://formio.atlassian.net/browse/FIO-3884
https://github.com/formio/formio.js/pull/4497
I have updated how we compare columns to determine if the datagrid needs to be updated.
The previous comparison would compare every field including the auto-generated "id" field.
Through debugging, I've found that the datagrid was being re-drawn unnecessarily because the only field in the columns that were different were the "id"s.
I've updated the logic to ignore the id field when comparing.
I kept the majority of the previous solution, simply skipping the comparison of the id to avoid unnecessary rebuilding of the datagrids.
I tested it locally with my use case and this reduced the re-drawing of the grid.

FIO-3884 Improved column comparison by excluding the id.

---

src/components/datetime/DateTime.js
src/components/datetime/DateTime.unit.js

https://formio.atlassian.net/jira/software/c/projects/FIO/issues/FIO-6807
Fixed an issue with date time format after using enableDate or enableTime checkboxes
I added automated tests to cover these cases
And also tested locally https://formio.atlassian.net/browse/FIO-6807?focusedCommentId=46137

FIO-6807:fixed an issue with date time format after using enableDate or enableTime checkboxes

---

src/components/file/File.js
src/providers/storage/azure.js
src/providers/storage/googleDrive.js
src/providers/storage/s3.js

https://formio.atlassian.net/browse/FIO-3820
*Ability to delete files that are removed from the form and to delete the files also inside the Storage Services.*
*Previously, files were deleted only from the portal, but not from the file storage*
*This PR depends on the PR for the formio server that I attached in the ticket.*
*I have not added automated tests. All tests pass locally with my changes*
- [ x] My changes generate no new warnings
- [ x] New and existing unit/integration tests pass locally with my changes

FIO-3820: Ability to delete files inside the Storage Services

---

src/components/checkbox/Checkbox.js

https://formio.atlassian.net/browse/FIO-6906
*Previously, submissions that are created before adding the checkbox had the value "no" in the Checkbox column of the Data table. This PR replaces this behavior and now submissions that are created before adding the checkbox have a blank value in the Checkbox column of the Data table*
*no.*

FIO-6906 fixed value for Checkbox submission in Data Tab

---

src/components/_classes/list/ListComponent.js
src/components/radio/Radio.js
src/components/radio/Radio.unit.js
src/components/select/Select.js
src/components/selectboxes/SelectBoxes.js
src/components/selectboxes/SelectBoxes.unit.js

https://formio.atlassian.net/browse/FIO-7040
*The concept of selectData has been implemented for all List Based components (Radio Component and SelecBoxes Component). After the changes, the templateData for the selected items is provided in the metadata.selectData value, and the templateData for items is provided in metadata.listData. This allows not to make an additional request to the Data Source URL for readOnly mode if the value shouldLoad === false.*
*no*
*Automated tests have been added. All tests passed locally*

FIO-7040 Enabled selectData for all List Based Components

---

src/WebformBuilder.js
src/sass/formio.form.builder.scss

https://formio.atlassian.net/browse/FIO-6933
Fixed the following issues:
1) Double call of attachComponent when WebformBuilder was initialized
2) Fixed focus trap when a component was selected to move
3) Changed the way the component is presented when selected to move, also made the outline to not disappear when the component lost focus
4) Fixed event listeners piling up when using the Move many times
5) Fixed a crash when trying to move a component, when another one was selected previously.
Tested on the local environment

FIO-6933 Fixes for the formbuilder with keyboard actions

---

src/WebformBuilder.js

https://formio.atlassian.net/browse/FIO-7035
https://formio.atlassian.net/browse/FIO-7036
Changed logic to verify if component is coming from resource fields in first order. We can have case when resource field has the same key as basic component.
Manual

FIO-7035, FIO-7036: fixed issue with dragging layout resource component

---

src/WebformBuilder.js

https://formio.atlassian.net/browse/FIO-7043
This is a dependency PR for https://github.com/formio/premium/pull/259
When user clicks Edit on the component in Form Builder, it creates an instance of that component to get all of it properties and their default values which are not contained in the minified JSON schema. When this component is created, its init() method is called, the same happens to the DataSource component and inside it it calls refresh() method causing to try to fetch data and resolve the headers. We don't want that and don't need that because that instance is created only for grabbing the full component's schema. I added new option called inFormBuilder (previously, those components were created without passign any additional options, so there were no way to figure out …

FIO-7043: Fixes an issue where {{}} values in DataSource headers are resolved in the form builder

---

src/components/_classes/component/Component.js
src/components/_classes/field/Field.js
src/components/_classes/multivalue/Multivalue.js
src/components/day/Day.js
src/components/day/Day.unit.js
src/components/day/fixtures/comp6.js
src/components/day/fixtures/index.js

https://formio.atlassian.net/browse/FIO-6578
Because Day component has three inputs (Day, month and year), formiojs was not able to properly restore focus on it after redrawing, so I adjusted saveCaretPosition function and focus funtion, now it saves field name (day, month or year) instead of input index for Day component and Day component accepts it as an argument to focus a specific field instead of the first one. 
This fix is for restoring focus properly on the Day component after redraw, but this issue also was happenning because unneccessary redraws were happenning (Even when nothing has changed after logic ccheck). That was caused by assigning min and maxDate properties to this.component inside get validationValue(). Since it was assigned to the component's schema after constructor …

FIO-6578: Fixes an issue with losing focus on Year field when Day component has advanced logic

---

src/components/radio/Radio.js
src/components/radio/Radio.unit.js

https://formio.atlassian.net/browse/FIO-7209
*If Value Property doesn't set for Radio Component with DataSrc url, the User will be able to submit the form. The item itself is used as value property.*
*https://github.com/formio/bootstrap/pull/74*
*All tests pass locally. Automated tests have been updated*

FIO-7209 Radio works without ValueProperty set

---

src/components/selectboxes/SelectBoxes.js
src/components/selectboxes/SelectBoxes.unit.js
src/components/selectboxes/fixtures/comp7.js
src/components/selectboxes/fixtures/index.js

https://formio.atlassian.net/browse/FIO-6970
Originally, this feature was requested for the Select and Radio component to prevent saving submission with unexisting values by direct request to the server. But since SelectBoxes extend Radio component, it inherited this setting as well and it was not working properly due to the different value structures. I override the method executing the check for this validation for SelectBoxes vomponent, so now it works properly and fails only if component value contains keys that it should not. 
Manually and I also added an automated test

FIO-6970: Fixes an issue where SelectBoxes Only Available Items validation always fails

---

src/Wizard.js
src/Wizard.unit.js

https://formio.atlassian.net/browse/FIO-7074
The issue: wizardInstace.submission = {...} will set data only for the first Wizard page, because Wizard's setValue method assigns submission.data to the _data property conditionally only when it is in readOnly or edit mode or if there is a submission id and it has suffix/prefix components.The parent's Webform's method almost always assigns submission.data to the _data property, but using _.mergeWith.
I beleive that this is done conditionally in Wizard because without those conditions hide/show logic won't work properly in Use mode, cause we calle setNestedValue for all the pages after merging/not merging data. Ans setNestedValue returns changed variable which value is determined based on the values passed to the method and the value is the …

FIO-7074: Fixes an issue where setting submission to the Wizard from the form controller will not set values for all the pages

---

src/components/datagrid/DataGrid.js

Avoid passing 'undefined' to function getFocusableElements in DataGrid
- Passing 'undefined' leads to an error (TypeError: Cannot read properties of undefined (reading 'querySelectorAll')) shown in console.
Previoulsy, an error was shown in the Browser console log when clicking the 'Add column' button in the Columns component.
Steps to reproduce: 
- In developer portal, drag new columns component into a new form 
- In the 'edit' modal, on the 'Display' tab, under 'Column Properties', press the 'Add column' button 
- Observe an error log in the Browser console
Error:
TypeError: Cannot read properties of undefined (reading '0')
at scripts.js:2:7858764
at c.$emit (scripts.js:2:4250942)
at f.<anonymous> (scripts.js:2:6932320)
at …

Avoid passing 'undefined' to function getFocusableElements in DataGrid

---

src/WebformBuilder.js
src/Wizard.js
src/components/panel/Panel.unit.js
src/components/panel/editForm/Panel.edit.display.js

https://formio.atlassian.net/browse/FIO-7082
Removed Condensed type cause it does nothing from the time when the feature was added. Breadcrumbs type select dropdown is moved to the form settings page instead. For the old forms that have breadcrumb type set per page everything will work the same. 
I also had to pass form schema from the form builder to the evalContext of the editForm to prevent showing settings that should not be available when breadcrumbs type is 'hidden'.
https://github.com/formio/formio-app/pull/1494
Manually

FIO-7082: Moved Wizard Breadcrumbs Type to form settings

---

src/providers/storage/s3.js

https://formio.atlassian.net/browse/FIO-6859
Loops over the headers that have been sent from server at src/storage/s3/aws.js signed.presigned()
These headers are coming directly from the `presigned.headers` WITH the presignedUrl from the server that should be necessary to make the request.
- https://github.com/formio/formio-server/pull/1336
Refer to https://github.com/formio/formio-server/pull/1336, I had made this small change to the formio.js node_modules in formio-app when running the portal locally.

FIO-6859: update-s3-to-accept-headers-from-signer-presign

---

package.json
src/providers/storage/s3.js
yarn.lock

https://formio.atlassian.net/browse/FIO-7239
In #5356 there is possibly a need to support older browsers, so this PR lazily imports a polyfill. Additionally, it includes the Form.io token when making multipart `complete` and `abort` requests.
n/a
n/a

FIO-7239: add polyfill and include token in abort and complete requests for multipart upload

---

src/Wizard.js
src/Wizard.unit.js

Reverts formio/formio.js#5351 as a result of Brendan's investigation below.
Brendan:
It looks to me like the Sasha's solution for FIO-7074 (https://github.com/formio/formio.js/pull/5351) and Hanna's solution for FIO-7351 (https://github.com/formio/formio/pull/1634) are conflicting: when the submission reaches the server, we almost always pass the sanitize flag, which has been added to the insanely long conditional check that decides whether or not to call the `mergeData()` method in Wizard's `setValue()` method. This results in mergeData() not being called, and the submission coming back mutated and saved to the database incorrectly.

Revert "Fio 7074 setting submission on wizard does not update data"

---

src/components/columns/editForm/Columns.edit.display.js

https://formio.atlassian.net/browse/FIO-7429
Previously, formio.js Columns component had width, offset, push and pull bootstrap classes adjustments through component settings. This PR leaves only the width property adjustable, leaving ability to configure all the classes through component JSON schema.
[@formio/bootstrap:80](https://github.com/formio/bootstrap/pull/80)
Manually through formio-app UI

FIO-7429: Remove columns component settings(pull, offset, push)

---

src/components/select/Select.js

https://formio.atlassian.net/browse/FIO-7355
Removed handler that called update() function for HTML5 select on focus, because there is no mechanisms to change Select options data after the element was already initialized, and any custom/url and other dynamic data gets set on init
Tested locally

FIO-7355 Fixed issue with HTML5 select flickering on initial click

---

src/utils/utils.js

With this modification we CAN make Formio render SVG and MathML by including the below under options in sandbox:
```
{
"sanitizeConfig": {
"useProfiles": {
"mathMl": true,
"svg": true
}
}
}
```
SVG and MathML in an HTML element are now rendered as expected.
No Jira ticket - but issue reported in GitHub:
https://github.com/formio/formio.js/issues/4224
Previously, formio.js did not allow rendering svg and mathml.
This PR replaces this behavior by allowing to add additional sanitize profiles through options.
See GitHub issue.
Fits in the way tags and attributes are added.
None.
Manually in a local sandbox in FireFox and Chrome.
In JSFiddle with code below:
```js
let sanitizeOptions = {
ADD_ATTR: ['ref', 'target'],
USE_PROFILES: { html: …
```

Add capability for adding sanitize profiles through sanitizeConfig in options

---

src/components/select/Select.js

https://formio.atlassian.net/browse/FIO-7530
added ability to pass onSetItems component setting as a string (needed for DataTable builder mode)
https://github.com/formio/premium/pull/275
manually

FIO-7530: added ability to pass onSetItems component setting as a string (needed for builder mode)

---

src/components/_classes/component/Component.js

This reverts commit 3a8d7d6be224dac2bfc0e0b1dc31ddd2f89075a3.
https://formio.atlassian.net/browse/FIO-7528
There is a "shouldSkipValidation" function that checks for, among other things, whether or not the following conditions are satisfied:
(A) there is a custom validation
(B) the dataValue of the component is truthy
(C) the component is required
if A && !B && !C, the component will skip validating. In this case, since the value of an un-blurred select component is "", it is falsy and satisfies A && !B && !C. I'm not sure why this was introduced (I imagine to ensure that empty values that aren't required don't get validated) but we may need to reexamine our thinking behind this. In the meantime, the only workaround I can think of is to both set the field to `required` and maintain the …

Revert FIO-4405: fixed an issue where walidation error displays with empty value even if it is not required (#4746)

---

src/components/_classes/nested/NestedComponent.js
src/components/container/Container.unit.js
src/components/container/fixtures/comp4.js
src/components/container/fixtures/index.js
src/components/select/Select.unit.js

…bmission
https://formio.atlassian.net/browse/FIO-7547
An automated test was added

FIO-7547: Container hidden with conditional logic still appears in submission

---

gulpfile.js

https://formio.atlassian.net/browse/FIO-7550
formio.full.css caused project compile error. The original commit (already applied to 4.18.x and 4.17.x updated gulp.task('styles-form') and gulp.task('styles-builder'). The added commit also applies it to gulp.task('styles-full')

FIO-7550: Fixing choices css issue

---

src/components/_classes/component/Component.js
src/components/textfield/TextField.js

https://formio.atlassian.net/browse/FIO-7112
TextField component should inherit the widget settings of the original form component in new simple conditionals ui.
Base value component in new simple conditionals ui should always has input widget.
https://github.com/formio/premium/pull/279
manually

FIO-7112: fixed issues with calendar widget display for value components in new simple conditionals ui

---

src/components/textarea/TextArea.js

https://formio.atlassian.net/browse/FIO-7406
Previously, all types of Textarea inputs were interpolated by default in readonly mode (i.e. submission view). This change disables interpolating when custom editors are not used.
Tested locally

FIO-7406 Fixed plain Textarea interpolating data in readonly mode

---

src/providers/storage/xhr.js

https://formio.atlassian.net/browse/FIO-7481
Added condition to check response status for file upload requests. More information about 504 status from the service worker can be found on angular documentation [Service worker requests when the server can't be reached](https://angular.io/guide/service-worker-devops#service-worker-requests-when-the-server-cant-be-reached).
Although there were many potential solutions:
1. Check by 504 status code
2. Include 'ngsw-bypass' header in a specific request to let the service worker know that he should skip this request and allow to do it directly to the server. (I don't think it's the best idea to include specific header for angular in our core library)
3. Extend our 'fix-sw' gulp task in the form manager to check the request URL and skip service …

FIO-7481: handle 504 response from service worker in offline mode for file request

---

src/components/editgrid/EditGrid.js

Fixing issue opened here: https://github.com/formio/formio.js/issues/5420
Revert to adding events in read only mode and only removing them in pdf rendering mode, which seems to have been the intention in the original MR: https://github.com/formio/formio.js/pull/4850 
This solution ensures backward compatibility.
Although there were other solutions, such as:
* Firing a different event for viewing the grid row (eg: viewRow instead of editRow).

Fix edit grid events in read only mode

---

src/components/select/Select.js
src/components/select/Select.unit.js
src/components/survey/Survey.js
test/forms/helpers/testBasicComponentSettings/values.js
test/renders/component-bootstrap-survey-string-value1.html
test/renders/component-bootstrap-survey-string-value2.html
test/updateRenders.js

https://formio.atlassian.net/browse/FIO-7588
- before string value for Survey looked like stringified object, changed it so that it looks like as string with question and answer labels separated by ";" 
Before:  {"quest1":"b","quest2":"a"}
Now: 'Question 1: B;  Question 2: A'
- modified asString method of select component, so that in case of csv option, it returns plain text without HTML
- fixed updateRenders method as before it does not update all renders due to wrong directory.
- added/modified tests
https://github.com/formio/reporting/pull/13
Manually + tests
All tests passed locally!!!

FIO-7588: fixed string value for Survey and Select

---

src/components/radio/Radio.js
src/components/radio/Radio.unit.js
src/components/radio/fixtures/comp10.js
src/components/radio/fixtures/index.js

https://formio.atlassian.net/browse/FIO-7602
*Fixed submission data for Radio component values starting with 0*
*no*
*Automated tests have been added.*

FIO-7602 fixed submission data for 0s values

---

src/components/recaptcha/ReCaptcha.js

https://formio.atlassian.net/browse/FIO-7577
Recaptcha components were appearing in the "submission" macro when emails were rendered "dynamically" (using formiojs). By adding the `skipInEmail` instance property, they will no longer render in that macro.
n/a
n/a

FIO-7577: add skipInEmail comp property to recaptcha

---

src/Element.js
src/components/select/Select.js

https://formio.atlassian.net/browse/FIO-7548
The choices dropdown does not overlap the datagrid and causes vertical scroll because our datagrid component has overflow-x  set to auto so that the horizontal scroll appears when it has many child components that dees not fit the screen width. 
When overflow-x is set to any value except 'visible', the overflow-y gets value 'auto' even if we set it to 'visible' by css that causes vertical scroll when select dropdown is open. In other words, if we are using visible for either overflow-x or overflow-y and something other than visible for the other, the visible value is interpreted as auto.
The workaround for it is to position the dropdown against any element outside the container with overflow-x. 
So, this PR sets position …

FIO-7548: fixed an issue where select dropdown does not overlap the datagrid and causes vertical scroll

---

src/components/html/HTML.js
src/components/html/HTML.unit.js
src/components/html/fixtures/comp3.js
src/components/html/fixtures/index.js

https://formio.atlassian.net/browse/FIO-7544
Previously, formio.js was sanitizing the HTML component's content at the end of get content(), but since interpolate() method uses translateHTMLTemplate utility function that creates a DOM element and sets a content inside it, we need to sanitize the content before it goes there. 

FIO-7544: Fixes an issue where scripts inside HTML component will be executed during interpolation

---

src/components/form/Form.js

https://formio.atlassian.net/browse/FIO-7637
A customer had an urgent production issue - their servers were crashing with unhandled promise exceptions. Upon investigation, the server-side formio.js renderer is attempting to load subform submissions from a baseUrl that is not set, ending in a "Invalid Alias" error. Since [Formio.request](https://github.com/formio/core/blob/a60896ce96c7a7b4d759a4a3bae5ad28a6b2f003/src/sdk/Formio.ts#L1561) rejects on 4xx responses, the server will crash because NodeJS expects you to handle uncaught Promise exceptions.
An alternative might have been to examine why Formio.request rejects on 4xx responses rather than delegating handling non network errors to the caller (a lá the fetch web api), but due to the urgency of this ticket for the customer in question …

FIO-7637: add catch block to subform submission loading

---

src/components/_classes/component/Component.js
src/components/_classes/component/fixtures/comp5.js
src/utils/utils.js

https://formio.atlassian.net/browse/FIO-7466
Now Tooltips will show non-rendered HTML

FIO-7466: Make tooltips show non-rendered HTML

---

package.json
src/components/_classes/component/Component.js
src/components/_classes/multivalue/Multivalue.js
src/components/textfield/TextField.js
src/components/textfield/TextField.unit.js
src/validator/Validator.js
yarn.lock

https://formio.atlassian.net/browse/FIO-4242
*The InputMask for the TextField component has been updated and works according to the [documentation](https://github.com/RobinHerbots/Inputmask). After the changes, the inputmask supports dynamic syntax:*
- *9{1,4} meant to mean that it accepts one, two, three or four numbers*
- *9[99] meant to mean that it accepts one number and two additional optional numbers*
*Also according to the [documentation](https://github.com/RobinHerbots/Inputmask), "a" allows to enter lowercase and uppercase letters, and "A" allows to enter only uppercase letters*
*no*
*Tests have been added and updated*

FIO-4242 updated input mask for TextField

---

src/components/select/Select.js
src/components/select/Select.unit.js
src/components/select/fixtures/comp20.js
src/components/select/fixtures/index.js

https://formio.atlassian.net/browse/FIO-7724
*Fixed incorrect metadata selectData setting for the Select component with multiple values*
*no*
*Automated tests have been added*

FIO-7724 fixed metadata for multiple select

---

src/sass/formio.form.scss

https://formio.atlassian.net/browse/FIO-7591
Replace break-all CSS value to auto-phrase
It was changed to break-all which breaks no event the errors, the labels were breaking on word too.
None
None 
Locally and manually

FIO-7591: Error messages wrapping on letter instead of on word

---

src/components/datagrid/DataGrid.js

https://formio.atlassian.net/browse/FIO-7786
Added null flag conditional 
NA
NA
NA
Manually

FIO-7786: Fixing Datagrid issue in Settings JSON

---

src/utils/utils.js

https://formio.atlassian.net/browse/FIO-7809
*Fixed Timeout error for PDF download page. In the process of manually integrating changes from 5.x, it turned out that [import](https://github.com/formio/formio.js/blob/4.19.x/src/utils/utils.js#L6) and [export](https://github.com/formio/formio.js/blob/4.19.x/src/utils/utils.js#L40) are different, which is the reason for the Timeout Error when download the PDF page*
*no*

FIO-7809 fixed pdf submission download error

---

.circleci/config.yml

https://formio.atlassian.net/browse/FIO-7146
Adds a workflow that disables all jobs in the config from running.
Leaves the CircleCI pipeline intact just adds a config for disabling the workflow from running

FIO-7146: disable circleci jobs

---

src/components/file/File.js

Support filePatterns that include exclusions such as `'!.exe'`.
Looks like this refactor broke it:
https://github.com/formio/formio.js/commit/1c3fe1f8ee776fec12e89dee563023c646d7eb66#diff-88fcc2d2f31515efb91047d6564cc78e83922d7d795e776c2523d7c94f844e6dL450
The previous refactor added a negation to these results so any exclusion pattern will always fail.
The exclusion regular expressions are a negative lookahead for the exclusion.
Each exclusion pattern matches a string that does not contain the exclusion.
**Screenshot**
Example of it currently broken:

Fix broken file exclusion patterns

---

src/providers/storage/url.js

*Previously, formio.js did not pass http request options to the `deleteFile` method for file components with URL storage.  This PR replaces this behavior by passing the options to the `deleteFile` method, allowing users to better secure their files by requiring authorization headers.*

Pass options to the deleteFile method for file components with URL storage

---

src/Wizard.js
src/Wizard.unit.js

N/A
When rendering a form with display 'wizard' the current page will now be kept after language is changed.
After upgrading to the most recent version of formio.js we saw that when a form was rendered with display 'wizard' the current page was reset to zero after changing the language. Prior to https://github.com/formio/formio.js/pull/5176 (which changed the implementation of 'set language' to invoke rebuild instead of redraw) this did not happen.
This is a breaking change if someone expects the form with display 'wizard' to reset current page to zero when the form is rebuilt.
N/A
Unit test, and in my team's application using formio.js.

Wizard: Keep current page after language is changed

---

src/Webform.js
src/Webform.unit.js
test/forms/formWithValidation.js

https://formio.atlassian.net/browse/FIO-7580
This PR:
-  reverts changes made by PR https://github.com/formio/formio.js/commit/00435311d94d45646b9b1be8070f2c86b261a8e6 (FIO-6475). Those change prevented the emission of error event on submit of invalid form;
- fixes the original issue (FIO-6475) where server errors (that are not related to the server validation of the component) are not persistent in ui;
- adds an argument for the submitError event in case when submission is failed due to front-end validation
Manually + added tests

FIO-7580,6475: fixed error events issues and an issue where general server errors quickly disappear from ui

---

src/providers/storage/s3.js

n/a
At some point a change was made [on the client](https://github.com/formio/formio.js/commit/640ffd74e6907f53619cfc93b2fd6e11c20144d6) and [on the server](https://github.com/formio/formio-server/commit/227ec27fc02ccbaf3893ae491ec75a0a34eefdb5) which added a `headers` object to the Enterprise Server's presigned url response to S3 upload requests. These changes didn't account for older deployments, which may not include the headers object, which results in a TypeError on newer clients that are connected to older server environments (see #5475 e.g.). This PR adds a simple conditional which should skip the new client logic if the headers object does not exist.
n/a
n/a
n/a

add conditional to check for new headers object

---

src/components/file/editForm/File.edit.file.js

https://formio.atlassian.net/browse/FIO-7764
Removed an extra quotation from File Template Name placeholder

FIO-7764: Fixes a typo in File component settings

---

src/components/editgrid/EditGrid.js
src/components/editgrid/EditGrid.unit.js
test/forms/editGridOpenWhenEmpty.js

https://formio.atlassian.net/browse/FIO-7603
Added check for openWhenEmpty on submission to allow empty rows.
Previous code did not allow form submission on empty rows even when openWhenEmpty flag is enabled.
None
None
Tested manually and with unit tests.

FIO 7603 Edit Grid With Empty Rows Not Submitting Form

---

src/components/_classes/component/Component.js
src/components/_classes/nested/NestedComponent.js
src/components/datagrid/DataGrid.js
src/components/datagrid/DataGrid.unit.js
src/components/datagrid/fixtures/index.js
src/components/datagrid/fixtures/two-comp-with-allow-calculate-override.js

https://formio.atlassian.net/browse/FIO-4871
In this PR fixes for several issues:
1. DataGrid with the 'Initialize Empty' setting doesn't add calculated rows to the form so DataGrid is always empty.
2. Only the first component inside NestedComponent can recalculate value.
3. DataGrid can restore calculations after values have been changed manually by resetting values to the previous calculated value.
4. EditGrid trigger calculate value in builder mode.
Unit testing, manual testing.

FIO-4871 fixed calculated value issues

---

src/Webform.unit.js
src/components/editgrid/EditGrid.js
src/components/editgrid/EditGrid.unit.js
src/components/editgrid/fixtures/formsWithEditGridAndConditions.js

https://formio.atlassian.net/browse/FIO-7808
When the validator is run on the server side, the server option is passed for the form and the setValue is called. 
When the server option is passed, the clearOnHide method unsets the components values once the conditions check defines that the component is not conditionally visible. The setValue method of editGrid can potentially trigger the conditions check 4 times and it can appear that the values are unset for the editGrid before the other form values are set and the conditions check on the form level is triggered . This PR allows only the conditions check that comes from the form level for the hidden editGrid with server option.
Since this kind of issue is reported for editGrid …

FIO-7808: fixed an issue where conditional editGrid loses the value after submission

---

src/Webform.js
src/Webform.unit.js
src/translations/en.js
yarn.lock

https://formio.atlassian.net/browse/FIO-7899
- call restoreDraft once the form is ready, as restoreDraft requires the formio instance to be attached
- added errors handling for saveDraft and restoreDraft
All tests passed locally + added test for my fix

FIO-7899: fixed an issue where saveDraft option does not work and added errors handling for the save draft and restore draft functionality

---

src/components/address/fixtures/comp3.js
src/components/datagrid/fixtures/comp6.js
test/formtest/settingErrors.json

https://formio.atlassian.net/browse/FIO-7675
Previously formio.js had a hardcoded api key set in a few places. Removed them due to it being a public repository.
No other criteria were stated on the ticket and clear that they should not be in a public repo.
n/a
Ran tests locally

FIO-7675: Remove maps key from repo

---

src/Webform.unit.js
src/utils/conditionOperators/IsEqualTo.js
test/forms/formsWithNewSimpleConditions.js

https://formio.atlassian.net/browse/FIO-7956
Parse the string compared value in case when the compared value type differs from the type of actual component value
Manually + tests added + all existing test are passed locally

FIO-7956: fixed an issue where simple condition based on stringified checkbox value is not executed correctly

---

src/WebformBuilder.js
src/components/datagrid/DataGrid.js

https://formio.atlassian.net/browse/FIO-7933
*Added PDF Document Designer for Webform PDF Output. Changed the display of json change buttons for components on the form designer, added a warning about unique component keys when trying to add two identical components on the PDF designer*
*https://github.com/formio/formio-app/pull/1551*
*https://github.com/formio/formio/pull/1722*
*https://github.com/formio/pdf-server/pull/332*
*https://github.com/formio/bootstrap/pull/89*
*manually with using pdf download*

FIO-7933 added PDF Document Designer

---

src/Form.js
src/Formio.unit.js
src/components/form/Form.js

https://formio.atlassian.net/browse/FIO-7395
Fixed the issue using embedded form URL with nested form when using subdirectories path
Unit tests

FIO-7395: Fixed the issue with loading nested form

---

src/components/radio/Radio.js

https://formio.atlassian.net/browse/FIO-7334
The static method providing Value Component for each component of the form was not implmented for the Radio omponent

FIO-7334: Fixes an issue where Radio values do not appear for Action Conditions settings

---

src/sass/formio.form.scss

https://formio.atlassian.net/browse/FIO-8009
*Fixed the display of the required asterisk for Radio and SelectBoxes Components with Inline Layout, Hidden label, and required = true*
*no*
*manually*

FIO-8009 fixed  display of the required asterisk

---

src/Webform.js
src/components/form/Form.js

https://formio.atlassian.net/browse/FIO-8109
*Previously, the Save Draft was not triggered for Nested Form components unless the additional properties form.draftEnabled and form.savingDraft were set. This has been fixed. Now Save Draft is triggered without form.draftEnabled and form.savingDraft for Nested forms*
*no.*
*Manually with using jsFiddle.*

FIO-8109 fixed save draft triggering for nested components

---

src/components/_classes/nestedarray/NestedArrayComponent.js
src/components/_classes/nesteddata/NestedDataComponent.js
src/components/_classes/nesteddata/NestedDataComponent.unit.js
test/forms/nestedDataWithModalViewAndLayoutComponents
test/forms/nestedDataWithModalViewAndLayoutComponents.json

https://formio.atlassian.net/browse/FIO-3703
NestedDataComponent was not iterating through layout components to render the values of the components inside them. Also, getComponents method was checking only in rowIndex is undefined, but it also could be null because inside everyComponent method it is set to null if not provided. 

FIO-3703: Fixes an issue where NestedData components with modal view do not render values inside Layout components in modal preview table

---

src/components/radio/Radio.js
src/components/radio/Radio.unit.js
src/components/radio/editForm/Radio.edit.data.js
src/components/radio/fixtures/comp11.js
src/components/radio/fixtures/index.js

https://formio.atlassian.net/browse/FIO-8074
*Added Storage Type to Radio Components. It is possible to select the data type*
*no*
*Automatic tests have been added*

FIO-8074 Added Storage Type to Radio Components

---

.eslintrc.json
src/providers/storage/s3.js

https://formio.atlassian.net/browse/FIO-7733
Next.js, the [now de-facto standard React framework](https://react.dev/learn/start-a-new-react-project#nextjs-pages-router), incorporates both a server-side rendering phase along with a client-side rendering phase. This requires dependencies to be relatively isomorphic, or at least to account for globals like `window` possibly not being present in the runtime environment. 
This PR makes such a change by conditionally importing the AbortController polyfill only when it's needed and only if the browser runtime does not support it.
n/a
n/a
Existing tests around multi-part upload (where AbortController appears) continue to pass

FIO 7733: move polyfill to conditional lazy import

---

src/Form.js

https://formio.atlassian.net/browse/FIO-7733
In certain development circumstances, there was a javascript error in which the loader was no longer a child element of the main FJS element. This change merely checks that the loader is still a child before nullifying and removing the loader element.
Shouldn't be an issue, merely prevents a runtime error.
n/a
n/a

FIO-7733: conditionally offload loader

---

src/components/checkbox/Checkbox.js
src/components/checkbox/Checkbox.unit.js
src/components/checkbox/fixtures/comp5.js
src/components/checkbox/fixtures/index.js

https://formio.atlassian.net/browse/FIO-7595
*Fixed the issue of saving the true value for the checkbox component with simple conditions and set before the component they are based on. Previously, if the checkbox component with simple conditions was set before the component on which the checkbox display depends, then the value for this checkbox was not saved when submit data. This has been fixed by using super.setValue method*
*no*
*automated tests have been added*

FIO-7595 fixed incorrect value for conditionally hidden Checkbox

---

src/components/form/Form.js
src/components/form/Form.unit.js
src/components/form/fixtures/comp7.js
src/components/form/fixtures/comp8.js
src/components/form/fixtures/index.js

https://formio.atlassian.net/browse/FIO-8240
*Fixed restore data for nested form if skipDraftRestore is set as true for the parent form *
*no*
*automated tests have been added*

FIO-8240 fixed skipDraftRestore effect for the nested Forms

---

src/Webform.js

https://formio.atlassian.net/browse/FIO-8342
*Fixed triggering saveDraft after submitting the form. Added check of submitting before saving draft*
*no*
*Locally, all tests have passed. New automated tests have not been added, as the issue is reproduced only in the customer's angular sandbox*

FIO-8342 fixed triggering saveDraft after submitting the form

---

src/Webform.unit.js
src/components/radio/Radio.js
src/components/select/Select.js
src/components/selectboxes/SelectBoxes.js
test/forms/selectRadioUrlDataSource.js

https://formio.atlassian.net/browse/FIO-7195
The value for the modal preview is taken as a result of getValueAsString execution with modalPreview option passed, so I just added the missing part 
Mannually + automated tests were added

FIO-7195: Fixes an issue where Select, Radio and SelectBoxes components with URL DataSource show values instead of labels in modal preview

---

src/components/_classes/component/Component.js
src/utils/utils.js

https://formio.atlassian.net/browse/FIO-8302
The requireLibrary function in Formio.js now ignores any properties in the window object that are the type HTMLElement. Previously the window.property was unexpectedly being set by HTMLElements with an id attribute. This caused requireLibrary to pull in the HTMLElement instead of the expected object from <script src='...'>. A function was added to only get a window.property if it is not of the type HTMLElement
Manual testing

FIO-8302 Fixed issue with wizard api key overriding window.property objects 

---

src/components/recaptcha/editForm/ReCaptcha.edit.display.js

https://formio.atlassian.net/browse/FIO-8326
Changed recaptcha to require the **type of event** radio button to be selected in its edit form. This change was made because if you submit a form without selecting one of the radio buttons then the form will throw a **token is not specified in submission** error
N/A
Manually tested using formio.js form builder

FIO-8326: Recaptcha now requires type of event to be selected

---

src/components/select/Select.js
src/components/select/Select.unit.js
src/components/select/fixtures/comp23.js
src/components/select/fixtures/index.js

https://formio.atlassian.net/browse/FIO-8234
In the read only mode we are not fetching data from remote sources like URL and resource, so the Select components renders value, so I made use saved select metadata to render the labels properly

FIO-8234: Fixes an issue where Select with Resource data source renders values instead of labels in the read only mode

---

src/Webform.js
src/WebformBuilder.js
src/components/button/Button.js
src/components/recaptcha/ReCaptcha.form.js
src/components/recaptcha/ReCaptcha.js
src/components/recaptcha/editForm/ReCaptcha.edit.display.js

https://formio.atlassian.net/browse/FIO-8027
*Added new Captcha Component (premium). The ReСaptcha Сomponent has been removed from the FormBuilder and a warning about using the Captcha component instead of ReCaptcha component has been added to the modal edit window. All previous forms with the ReCaptcha component continue to work as expected.*
*https://github.com/formio/premium/pull/290*
*https://github.com/formio/formio/pull/1737*
*https://github.com/formio/formio-server/pull/1474*
*https://github.com/formio/core/pull/99*
*https://github.com/formio/formio-app/pull/1557*
*locally with using Cloudflare Turnstile provider*

FIO-8027 added new Captcha provider

---

src/sass/formio.form.scss

Currently this file includes invalid CSS which fails to parse on some of the modern tooling like lightningcss.dev.
Since IE7 is severely outdated I don't think this property is needed nowadays, given that even IE11 is fully deprecated.
Details on the Next.js repo: https://github.com/vercel/next.js/issues/66394

Remove *zoom (IE7 hack)

---

src/components/_classes/component/Component.js
src/components/select/Select.js
src/utils/utils.js
src/utils/utils.unit.js

https://formio.atlassian.net/browse/FIO-8395
Previously, formio.js would remove the html tags from error messages. This PR replaces this behavior by removing the code that causes the removal of the html tags. This PR also updates the unescapeHTML function in utils to stop removing the html tags from the string. This PR also adds a new removeHTML function that removes html from a string. I added this to replace areas of the code that used unescapeHTML because the actual functionality that is needed is to remove html not unescape characters.
I choose this solution because it allows for other areas of the code to now utilize unescapeHTML without the unexpected behavior of removing html tags.
N/A
Manually tested and added tests

FIO-8395: html in error message not evaluating

---

src/Webform.unit.js
src/components/_classes/component/Component.js

https://formio.atlassian.net/browse/FIO-8402
The issue was caused by calculated values, form load use onChange method that performs calculation and set pristine flag to false even if form wasn't initialized and user hasn't made any changes. Choose adding check for form initialization. 
n/a
Tested manually, all unit/integration tests pass locally

FIO-8402: fixed an issue where Validation Triggering on initial Form load

---

src/components/form/Form.js

https://formio.atlassian.net/browse/FIO-8493
This PR addresses an issue in the 4.x versions of formio.js where `this.root` is `undefined` when the edit button of the form component is clicked in builder mode. This issue does not occur in the master branch, as it was resolved by [this commit](https://github.com/formio/formio.js/commit/715ab01afae255f52af07a34ffb6a575c45f7d77)
The fix involves adding additional null checks to the root of the form component to prevent errors when  `this.root` is `undefined`. This ensures that the builder mode operates as expected across all versions of the library.
This fix has been tested by cherry-picking the commit onto the 4.19.x branch

FIO-8493: Added null check for this.root in builder mode

---

src/components/file/File.js
src/components/file/File.unit.js

https://formio.atlassian.net/browse/FIO-8420
Previously, formio.js would error on a file upload if the noDefaults option in Formio.createForm function was set to true. This PR replaces this behavior by validating that this.dataValue exists before calling the .some function on it.
Although there were many potential solutions my solution was best because it does not cause any new errors/bugs to appear in the code and allows the next couple of lines of code to work without modification.
N/A

FIO-8420: file component no defaults causes error

---

src/Webform.js
src/components/form/Form.unit.js
test/forms/helpers/testBasicComponentSettings/tests.js

https://formio.atlassian.net/browse/FIO-8510
A customer uses a combination of `saveDraft` and `skipDraftRestore` to automatically save but manually load draft submissions in their application. However, change events from nested forms bubble up to the parent with `modified: false`, ensuring that a change in the child form will not trigger a call to `saveDraft` in the parent. In other words, when manually loading the parent form's submissions, the nested forms will always come back empty.
This PR ensures that, when a Webform is nested, it will pass it's change metadata up to its parent form with the `modified` flag set to `true`. That way, changes in the child form will be seen by the parent so that the call to `saveDraft()` will be made both in the parent and the child. This is consistent …

FIO-8510: update webform change event to bubble, 4.19.x 

---

src/Wizard.unit.js
src/components/datagrid/DataGrid.unit.js
src/components/datagrid/fixtures/comp-with-checkboxes.js
src/components/datagrid/fixtures/index.js
src/components/radio/Radio.js
test/forms/index.js
test/forms/wizardWithCheckboxes.js

https://formio.atlassian.net/browse/FIO-8438
Previously, formio.js would clear radio components with the option inputType: checkbox when a new row was added to the datagrid.  This PR replaces this behavior by retaining the state of the checkbox when data grid adds a new row
Although there were many potential solutions, my solution was best because it adds a check to see if the element property on the component has the property checked to true to verify that the component is checked. It also does not remove value[input.value] to allow for reverse compatibility. 
N/A
I added automated tests to cover checkbox when checked and checkbox when unchecked cases. I also verified that removing my change from this PR will break these tests to …

FIO-8438: fix datagrid addrow clearing checkbox

---

src/utils/ChoicesWrapper.js

https://formio.atlassian.net/browse/FIO-8445
Previously, formio.js would unfocus the search bar when navigating the select component with the up and down keyboard arrows. This PR replaces this behavior by modifying the selectHighlightedChoice function to use the addItem choicesjs function instead of the handleChoiceAction choicesjs function. This allows the selectHighlightedChoices function to behave more like a highlighting choices instead of selecting choices when navigating using arrow keys.
*Although there were many potential solutions my solution was best because it introduces no new errors or bugs
N/A
manual testing

FIO-8445: Fixed searchbar not focusing when navigating using up and down arrows

---

src/components/_classes/input/Input.js
src/components/textarea/TextArea.unit.js
src/translations/en.js

https://formio.atlassian.net/browse/FIO-7936
Previously, formio.js did not translate the counter message when you had showCharCount and showWordCount enabled. This PR replaces this behavior by adding a translations for showCharCount and showWordCount.
This allows for users to override the the translation by adding the typeRemaining and typeCount to the i18n options.
N/A
I added automated tests to test translation and manually tested

FIO-7936: showCounter messages not translating

---

src/components/_classes/component/Component.js
src/components/_classes/component/Component.unit.js
src/components/_classes/component/fixtures/comp6.js
src/components/_classes/component/fixtures/index.js

https://formio.atlassian.net/browse/FIO-7775
Previously, formio.js reset value event would reset all components values to an empty value. This PR replaces this behavior by setting the value to the components default value, else if the component does not have a default value fall back to the empty value. 
Although there were many potential solutions my solution was best because it allows all components to reset their values to the default value and will fallback to empty value if the component has no default value
N/A

FIO-7775: reset value event resets component values to their default values

---

src/components/day/Day.js
src/components/day/Day.unit.js
src/components/day/fixtures/comp7.js
src/components/day/fixtures/index.js

https://formio.atlassian.net/browse/FIO-6710
Previously, formio.js did not translate the placeholder for the day component. This PR replaces this behavior by wrapping the placeholder text with this.t().
N/A
I added automated tests to cover translations and also manually tested

FIO-6710: added translation for day component placeholder

---

src/components/number/Number.js
src/components/number/Number.unit.js
src/components/number/fixtures/comp8.js
src/components/number/fixtures/index.js

https://formio.atlassian.net/browse/FIO-8570
Previously, formio.js would strip the decimal symbol and numbers after the decimal symbol when the decimalSymbol property was set on the number component JSON. This PR replaces this behavior by setting the decimalSeparator instance variable in the number class to the component decimalSymbol property if given else falling back on previous decimal separator options.
Although there were many potential solutions my solution was best because it integrates with the current ways decimal separators are set and does not require any change of functions.
N/A

FIO-8570: fixed decimal symbol property on number component

---

src/components/_classes/multivalue/Multivalue.js
src/components/phonenumber/PhoneNumber.unit.js
src/components/phonenumber/fixtures/comp2.js
src/components/phonenumber/fixtures/index.js

https://formio.atlassian.net/browse/FIO-8304
Previously, formio.js would keep the original input mask when switching from a input mask to a blank input mask in a multivalue input mask component. This PR replaces this behavior by removing the previous input mask if a blank input mask is given
N/A

FIO-8304: allow for multivalue masks to have blank input mask option

---

src/Webform.unit.js
src/components/select/Select.js
src/components/select/Select.unit.js

https://formio.atlassian.net/browse/FIO-8126
Previously, formio.js select component would trigger a blur event upon clicking the select. This PR replaces this behavior by adding the blur event listener to the choicesjs input element 
The choicesjs input element is focused upon clicking the select element. So adding the blur event listener to the input element fixes this issue
N/A
manual testing

FIO-8126: Fixed select component emitting blur on click

---

src/Formio.js

With the introduction of the new Embed system, there is a new promise called "formioReady" which will resolve to the full Formio class once it is lazy loaded into place. This allows you to do something like...
```js
import { Formio } from '@formio/js/embed';
Formio.formioReady.then(function() {
// Do something ONLY when the full code has been loaded.
});
```
The problem is that if you were to import Formio from the full source it would never resolve like so...
```js
import { Formio } from '@formio/js';
Formio.formioReady.then(function() {
// Without this PR, this would never resolve!
});
```

Fixing the formioReady promise to always resolve if you load it from the full source instead of the embed code.

---

src/components/_classes/component/editForm/Component.edit.display.js

https://formio.atlassian.net/browse/FIO-8659
Previously, formio.js had the modal checkbox removed by [Adding JSDocs and fixes for the 5x Renderer Version.](https://github.com/formio/formio.js/commit/95760937e01133b1428bd253751536814dee5f92) This PR replaces this behavior by adding the modal checkbox option back to the component edit display json
N/A
manually tested

FIO-8659: no modal edit in display tab

---

src/providers/address/GoogleAddressProvider.js

https://formio.atlassian.net/browse/FIO-8575
**Issue**: When integrating the Google Maps provider into the address component, the script for Google Maps is loaded with the URL including the API key. However, during the creation of an address component with the Google Maps provider, the library is loaded without an API key due to the preview modal executing the code to load the library. This results in the Google Maps library being loaded without the API key, and subsequent updates to the API key do not affect the already loaded library. Consequently, Google Maps continues to operate without the API key across web pages, unless a full page reload is performed.
**Solution**: The solution involves a method to verify if the Google Maps library has already been loaded by inspecting the src …

 FIO-8575: Added ability to reload google maps library with correct API key

---

src/components/_classes/component/Component.js
src/components/_classes/component/Component.unit.js
src/components/_classes/component/fixtures/comp7.js
src/components/_classes/component/fixtures/index.js

https://formio.atlassian.net/browse/FIO-8270
Previously, formio.js would revert back to the original component schema if a logic event action changed the hidden state of the component and any component triggered its change event. This PR replaces this behavior by allowing logic event listeners to update the original component hidden property so that it does not get reverted back when an input is made on the form.
Although there were many potential solutions, my solution was best because it allows all the tests to pass
N/A

FIO-8270: panel component closing on logic event trigger

---

src/components/datagrid/DataGrid.js
src/components/datagrid/DataGrid.unit.js

https://formio.atlassian.net/browse/FIO-8457
Previously, formio.js would not set the forms pristine property to false when the datagrid rows were reordered. This PR replaces this behavior by setting the forms pristine property to false when the datagrid rows are reordered.
N/A

FIO-8457: set pristine flag when datagrid reorders rows

---

src/components/editgrid/EditGrid.js

https://formio.atlassian.net/browse/FIO-8633
*Fixed the display of the row edit button icon for the Edit Grid Component*
*n/a*
*locally*

FIO-8633 fixed icon name for Edit Grid

---

src/components/datagrid/DataGrid.js
src/components/datagrid/DataGrid.unit.js
src/components/datagrid/fixtures/comp-with-reorder.js
src/components/datagrid/fixtures/index.js

https://formio.atlassian.net/browse/FIO-7478
Reorder submission selectData when the dataGrid rows are reordered

4.x - FIO-7478: fixed an issue where select component displays incorrect label after datagrid rows reorder

---

src/Webform.js

https://formio.atlassian.net/browse/FIO-8688
*Fixed an error that prevented FMG and FVP applications from running. The trigger of the error was importing the dragula library, which used the custom-event library and the global variable. The error has been fixed, now the applications run without errors*
*n/a*
*locally using FMG*

FIO-8688 fixed 'global is not defined' error message

---

src/components/day/Day.unit.js
src/components/day/fixtures/comp8.js
src/components/day/fixtures/index.js
src/translations/en.js

https://formio.atlassian.net/browse/FIO-8645
Previously, formio.js did not have the requiredDayField translation key in the en.js file which caused the required validation to not display correctly. This PR replaces this behavior by adding requiredDayField translation key to the translation file
N/A

FIO-8645: day component required validation error not correct

---

src/components/checkbox/Checkbox.js
src/components/checkbox/Checkbox.unit.js
src/components/checkbox/fixtures/comp6.js
src/components/checkbox/fixtures/index.js
src/components/textfield/TextField.unit.js

https://formio.atlassian.net/browse/FIO-8461
Previously, Checkbox with input type 'radio' and key + value set wasn't present in submission if left empty. This PR fixes this behavior by making specified key be present in submission.
I've made it to work same way as if you check -> uncheck the checkbox. In this case it was set to the submission object with empty string value ("").
None
I added automated test to cover the buggy case

FIO-8461: Fixes checkbox with radio input type not present in submission on 5.x renderer

---

src/components/address/Address.js
src/components/address/editForm/Address.edit.provider.js

https://formio.atlassian.net/browse/FIO-8639
*The Subscription Key field key was the reason for the error when adding the address component, because it included characters that are invalid for the key field. This has been fixed and the key has been replaced with the correct one, followed by the use of the appropriate parameter of provider options for Azure maps*
*https://github.com/formio/core/pull/118*
*tests have been added to the core lib. All tests pass locally*

FIO-8639 fixed error when adding address component

---

src/sass/formio.form.scss

https://formio.atlassian.net/browse/FIO-7733
Removes a 7 year old `min-heigh` CSS rule from forms.
n/a
n/a

FIO-7733 remove form min height

---

src/components/number/Number.js
src/components/number/Number.unit.js
src/components/number/fixtures/comp9.js
src/components/number/fixtures/index.js

https://formio.atlassian.net/browse/FIO-8570
this.delimiter can now be set by thousandsSeparator component JSON property. 
I choose this solution because it creates a single source of truth for what the delimiter is.
N/A
I have added automated tests and manually tested

FIO-8570: fixed thousandSeparator problem and decimal symbol problem

---

src/Webform.unit.js
src/utils/conditionOperators/IsEmptyValue.js
src/utils/utils.js
test/forms/formsWithNewSimpleConditions.js

**!!! PR for 4.19.x branch, there's a separate for 5.x branch** 
https://formio.atlassian.net/browse/FIO-8389
https://formio.atlassian.net/browse/FIO-8403
https://formio.atlassian.net/browse/FIO-8414
Previously, formio.js conditionals were failing with error / not working in scenarios when conditions were applied to array data structure components (Edit Grid, Data Grid, etc.). This PR fixes this behavior.
Tried different solutions, but since this logic never really worked fine, ended up writing a recursive function that would generate array of components paths with indexes, which are later iterated one by one to perform conditional checks.
None
I added automated tests to cover both tickets cases, also performed a good batch of …

FIO-8389 | FIO-8403 | FIO-8414: Fixes 4.x validations and conditionals for array data components

---

src/Webform.js
src/Webform.unit.js
test/forms/formWithEditGrid.js

https://formio.atlassian.net/browse/FIO-8647
https://formio.atlassian.net/browse/FIO-8721
Error messages for different rows are the same so they was deleted by _.uniqBy, this pr changes function so it considers not only message but path and id.
n/a
Added test.

FIO-8647,8721: validation not triggered for each row after the first one in data and edit grid

---

src/components/radio/Radio.js
src/components/radio/fixtures/comp12.js
src/components/radio/fixtures/index.js
src/components/selectboxes/SelectBoxes.unit.js

https://formio.atlassian.net/browse/FIO-8714
Debugged an issue on a customer call where they couldn't use paths as valueProperties (e.g. pointing a Select Boxes component at a Form.io Resource URL and having a valueProperty of data.firstName). This PR works but needs to be evaluated for thoroughness and tested.
n/a
Automated tests

Bugfix: allow paths for `valueProperty`

---

src/WebformBuilder.js

https://formio.atlassian.net/browse/FIO-8752
If the keyboard actions is given as a string then it needs to be coerced to a Boolean value else something like 
`this.options.properties?.keyboardBuilder = 'false'`
might evaluate to true in an expression like
`this.options.properties?.keyboardBuilder ? true : false => true`
This PR depends on https://github.com/formio/bootstrap/pull/99
manually tested

FIO-8752: coerced keyboard actions to a boolean value

---

src/WebformBuilder.js
src/WebformBuilder.unit.js

https://formio.atlassian.net/browse/FIO-8759
*Fixed a behavior where it was not possible to add Day component with required field add to the form  due to the validation of default value Field*
*n/a*
*n/a*
*automated tests have been added. all tests pass locally*

FIO-8759 fixed validation for the default value component

---

src/Form.js

https://formio.atlassian.net/browse/FIO-8809
`setUrl` is a Webform method, so it won't exist when rendering a builder with a string form argument (e.g. `Formio.builder(element, 'https://examples.form.io/example');` and will result in a runtime error.
n/a
n/a
n/a

Bugfix: fix runtime error in setForm when passing string argument to Formio.builder

---

src/PDF.js

https://formio.atlassian.net/browse/FIO-8684
Fixed the issue when PDF form was fully remounted to DOM on every component add. This caused a behavior when iframe ref was lost and only one component could be added to the PDF form.
Manually. Tried different approaches on writing an automated test for it, but ran into many issues and wasn't been able to complete it.

FIO-8684: Fixes cannot attach more than one component to the PDF form

---

src/WebformBuilder.js

https://formio.atlassian.net/browse/FIO-8668
Added additional filter param for the existing resources request that excludes resources with tag 'noBuilderResource' from the existing resources available in builder.
This solution is universal and can be applied to any form that we want to exclude from the existing recourses section.
https://github.com/formio/formio-server/pull/1539
https://github.com/formio/reporting/pull/39
Manually

FIO-8668: fixed an issue where reportingUI form is available is the existing resources in builder

---

src/templates/Templates.js

https://formio.atlassian.net/browse/FIO-8729
We use bootstrap templates as default templates. If someone does not use default framework and the template is missed in the used framework, we make a rollback to the default templates (bootstrap). But when a formio module (like premium, reporting, esignature) is included in the app, the bootstrap templates of those modules are not added to the default templates becouse default templates and bootstrap templates are referred to different objects. For that reason the fallback does not work for modules templates. This PR made it so that default templates refers and bootstrap templates refer to the same object.
https://github.com/formio/pro.formview.io/pull/118
https://github.com/formio/vpat/pull/183 …

FIO-8729: fixed an issue where the rollback to default templates does not work correctly and unknown template message is shown

---

src/WebformBuilder.unit.js
src/components/day/Day.js
src/components/day/Day.unit.js
src/translations/en.js
test/renders/component-bootstrap-day-html-value0.html

https://formio.atlassian.net/browse/FIO-8797
The empty value for the day component has been changed from '00/00/0000' to empty string ('').
The changes were made because the previous empty day value violated the logic of the form actions.
The empty value for the day component has been changed from '00/00/0000' to empty string ('').
auto tests

FIO-8797: set empty day component value to the empty string

---

src/components/signature/editForm/Signature.edit.display.js

https://formio.atlassian.net/browse/FIO-7524
Returned aspect ratio option to Signature so the Signature field size can be configured manually.
Tested locally.

FIO-7524 Added back aspect ratio option to Signature

---

src/components/time/Time.js

https://formio.atlassian.net/browse/FIO-8874
Before time field was used a value field for time component in the simple conditional UI. But time field has required input mask and does not allow to enter partial time value. I have changed it so that textfield is used as a value field in condition with time.
https://github.com/formio/premium/pull/323
https://github.com/formio/formio/pull/1788
Manually

FIO-8874: fixed conditional value field for time component

---

package.json
src/components/_classes/nested/NestedComponent.js
src/components/container/Container.unit.js
src/components/container/fixtures/editGridWithChildContainer.js
src/components/container/fixtures/index.js
src/components/textfield/TextField.unit.js
yarn.lock

https://formio.atlassian.net/browse/FIO-7779
When a nested component is created, the parent's options are passed down with it. For example, an edit grid component that contains a child container component will have a `options.row` parameter passed down and added to the child container component. This causes a problem with pathing - we previously didn't account for container components and naively added a row index to the pathing parameter (via the function `calculateComponentPath`) if the component had a row parameter. This means that the path for any resulting child components of the container would be pathed as 
```editGrid[0].container[0].textField```
rather than
```editGrid[0].container.textField```.
This PR updates the `calculateComponentPath` function to account …

FIO-7779: update pathing for nested container components and add test

---

src/PDFBuilder.js

https://formio.atlassian.net/browse/FIO-8921
When any component is dropped in the new PDF form (not saved), we uniquify the component API key. The uniquify method calls eachComponent function inside that assigns the **not enumerable** 'path' property to each component. 
Before, in pdf builder, we passed the array with a form as a first arg to the uniquify method and the eachComponent method made the form 'path' property not enumerable. That means that 'path' property can not be copied or spread like { ... form}. So, on saveForm, the server got the form without path and returned the validation error. This PR passes form components (this is what the uniquify method expects) as an arg for the uniquify method.
Manually

FIO-8921: fixed an issue where newly created PDF-form cannot be saved in builder after adding some components in it

---

src/components/address/Address.js
src/components/address/Address.unit.js

https://formio.atlassian.net/browse/FIO-8900
https://formio.atlassian.net/browse/FIO-8899
- made only isEmpty and isNotEmpty operators available in simple conditionals for address component
- fixed an issue where address empty value set inside 'address' property of the dataValue that causes the isEmpty method to return false even when the value is empty.
https://github.com/formio/formio/pull/1793
https://github.com/formio/premium/pull/328
manually + test

FIO-8900-8899: made only 2 operators available for address component in conditionals ui and fixed setting an empty value for address

---

src/validator/Validator.js

https://formio.atlassian.net/browse/FIO-8660
**Note:** The issue is not reproducible on the 5.x version of the renderer because the 5.x renderer uses the core validator. However, as decided, the fix should be added to the 4.x renderer as well.
**Issue:** When the component has the `unique` setting, it causes the validator [to assign](https://github.com/formio/formio.js/blob/v4.21.0/src/validator/Validator.js#L1110) a `unique` value to the `validate` object of the component before running the `checkValidity` method. On the next change, the component [will check](https://github.com/formio/formio.js/blob/v4.21.0/src/components/_classes/component/Component.js#L1924) both the current and original components and will find a unique change, triggering a redraw of the component. This redraw …

[4.x] FIO-8660: Fixed email component re-rendering with unique setting option

---

src/utils/utils.js

https://formio.atlassian.net/browse/FIO-8990
We exported the moment lib from utils like this: 
_export * as moment from 'moment-timezone/moment-timezone'._
The asterisk imports ALL exports from the package and the default export (that is the main moment instance) is available only when calling Utils.moment.default('someDate'). But the reporting module (maybe also some other our libraries ) expects that moment instance is available directly from Utils (Utils.moment('someDate')) like it was before (in 4.x).
This PR exports the moment library that was imported on the top of the file like:
_import moment from 'moment-timezone/moment-timezone';_
This type of import imports only default export and the moment instance becomes available directly from the Utils.

FIO-8990: fixed incorrect moment export

---

src/Webform.js
src/components/_classes/component/Component.js

https://formio.atlassian.net/browse/FIO-8914
We should always validate the submission that comes from the iframe, when the form  is submitted, to control the validation errors (add/remove them from the errors list).
Also this PR fixes the portal console error when editing the form with errors list as not all errors have component prop.
Manually with PDF forms

FIO-8914: fixed an issue where errors list doesnot appear when submitting a PDF form

---

.github/workflows/ci.yml
src/components/html/HTML.js
test/renders/component-bootstrap-htmlelement-multiple.html
test/renders/component-bootstrap-htmlelement-readOnly.html
test/renders/component-bootstrap-htmlelement-required.html
test/renders/component-bootstrap-htmlelement.html

https://formio.atlassian.net/browse/FIO-8423
The default parent tag for the HTML Component is `<p />`. However, the HTML spec [doesn't allow block-level elements](https://html.spec.whatwg.org/multipage/grouping-content.html#the-p-element) within a `<p />` tag, resulting in the browser closing the tag and the component's content, on first render, being rendered as a sibling (in other words, outside of the element's formio reference). 
After discussion, we decided that opting into the HTML Component means taking responsibility for valid HTML. I've changed the default parent tag to `<div />` for forms going forward, but this will be a 5.x change only (see below for backwards compatibility issues).
Since we don't store the parent tag in the database (in other words, the previous default of …

FIO-8423: change default parent tag from p to div

---

src/Webform.js
src/Webform.unit.js
test/forms/webformWIthNestedWizard.js

https://formio.atlassian.net/browse/FIO-8920
*Fixed an issue where  nested wizard form  validation errors were not included in the error list after clicking on the submit button*
*n/a*
*n/a*
*Automated tests have been added. All tests pass locally*

FIO-8920 fixed errors list for the form with nested wizard

---

src/components/select/Select.js
src/components/select/Select.unit.js

https://formio.atlassian.net/browse/FIO-8938
*Previously  the label of an item of a multiple Select component with dataSrc as resource could be displayed as undefined if the item value has type number or boolean. It has been fixed by adding normalizeSingleValue method*
*n/a*
*n/a*

FIO-8938 fixed label display for multiple select with dataSrc resource

---

src/components/_classes/multivalue/Multivalue.js
src/components/hidden/Hidden.unit.js

https://formio.atlassian.net/browse/FIO-9010
*The root of the issue with disappearance components inside the Column component is the incorrect setting of the value for the Hidden component. Previously, if the value of the Hidden Component was an array with nested arrays inside, then after normalization of the value, the first element of the array became the value. This was fixed by an additional check in the normalizeValue method*
*n/a*
*n/a*
*Automated tests have been added. All tests pass locally*

FIO-9010 fixed disappearance of components inside Columns after editing

---

src/components/_classes/component/Component.js
src/components/_classes/multivalue/Multivalue.js

https://formio.atlassian.net/browse/FIO-9010
This PR further utilizes @formio/core's model types to cover the case of "any" - so hidden components, custom components, and anything else with an unknown data model type at runtime. It also removes redundant `multiple` normalization from the base Component class.
n/a
n/a
The tests written for the original solution pass!

FIO-9010: tighten up multivalue normalization by covering 'any' type models

---

src/components/day/Day.js
test/unit/Day.unit.js

https://formio.atlassian.net/browse/FIO-8986
*Fixed a behavior where it was impossible to set the default value for the Day component if the day and month fields are hidden*
*n/a*
- *https://github.com/formio/formio.js/pull/5797*
- *https://github.com/formio/core/pull/149*
- *https://github.com/formio/core/pull/151*
*Automated test has been added/ All tests pass locally*

FIO-8986 fixed setting default value for day ,component with hidden day and month

---

src/components/_classes/list/ListComponent.js
src/components/radio/Radio.js
src/components/select/Select.js
test/unit/Radio.unit.js
test/unit/SelectBoxes.unit.js
test/unit/fixtures/radio/comp13.js
test/unit/fixtures/radio/index.js
test/unit/fixtures/selectboxes/comp8.js
test/unit/fixtures/selectboxes/index.js

https://formio.atlassian.net/browse/FIO-8948
https://formio.atlassian.net/browse/FIO-8950
Issues that this PR fixed:
- when it takes long time to load options for radio/selectboxes with url type, nothing indicates that the options are being loaded, the component displays just component label and not options. This PR adds the loader so that user could understand that it needs to wait.
- it was possible to submit the form even when radio/selectboxes options are not loaded. Because of it, the metadata related to the options was not included in the submission object. That caused issues with options display in  readOnly and pdf download. This PR adds the beforeSubmit handler that allows to submit the form only after the options are loaded.
- if the radio/selectboxes with url …

FIO-8948-8950: fixed an issue where radio and select boxes with url type do not display in PDF download

---

src/Wizard.js
test/unit/Wizard.unit.js

https://formio.atlassian.net/browse/FIO-9097
*Previously, when clicking on the error list links for a wizard form that includes a child wizard forum, focusing did not work for components of the parent form; and for components from the child form, after going to the corresponding page, some of the errors from the list disappeared. This has been fixed, now navigation via links from the error list works for both components from the parent wizard form and from the child wizard form.*
*n/a*
*n/a*

FIO-9097 fixed navigation through the errors list

---

src/Webform.js
test/forms/formWithUniqueValidation.js
test/unit/Webform.unit.js

https://formio.atlassian.net/browse/FIO-9075
The issue: when the form has server errors, the submit btn is disabled and the form cannot be resubmitted.
When the form has only server errors, we should not consider it as invalid as we cannot know if the values become valid after changes until resubmit it.
Tests

FIO-9075: fixed an issue where the form cannot be resubmitted if it has server errors

---

src/components/Components.js
test/forms/formWithCheckboxRadioTypeAndValidation.js
test/unit/NestedComponent.unit.js
test/unit/Webform.unit.js
test/unit/fixtures/nested/comp4.js
test/unit/fixtures/nested/index.js

https://formio.atlassian.net/browse/FIO-9080
A while back, core was updated to use the component `name` property as the `key` for checkbox components with an `inputType` of `'radio'`. `name`, in turn, was then used instead of `key` to generate the component `path`. formio.js was never updated to use `name` instead of `key`, so checkbox–radio components could not be validated. 
This change updates formio.js to use the same helper function that core uses to get the component `key`.
It made sense to plug into core's functionality instead of duplicating the logic; the helper function from core was already imported into formio.js. This also aligns with the desire to move business logic from formio.js to core.
I'm not sure–– are the …

FIO-9080 checkbox radio validation error

---

src/components/address/Address.js
test/unit/WebformBuilder.unit.js

https://formio.atlassian.net/browse/FIO-9056
Added sttter and getter for dataValue in Address component, since when enabling multiple values, the data structure wasn't changing to array, causing validation error to appear when trying to save the component.
None
Automated test was added

FIO-9056: Fix enabling multiple values for address component

---

src/components/_classes/list/ListComponent.js

https://formio.atlassian.net/browse/FIO-8914
need to trim url that comes from the component settings before to add query parameters to it, so that url works as expected.

FIO-8914: fixed an issue where select url does not work properly when url value has whitespaces at the end

---

src/components/_classes/component/Component.js
test/unit/Password.unit.js

https://formio.atlassian.net/browse/FIO-9158
Password component is protected, so in edit submission page it shows as "" that triggers validation error. Added condition to make sure error isn't shown if this component wasn't changed in edit page.
n/a
n/a
tested manually, added automated test

FIO-9158: fixed an issue where Password component error message persists to displayed in Edit page

---

src/components/radio/Radio.js
test/unit/Radio.unit.js

https://formio.atlassian.net/browse/FIO-9120
Added own version of `resetValue` method to the Radio component, since the inherited one was setting `defaultValue` instead of `emptyValue`, this made impossible unchecking all Radio values
None
Automated test is added

FIO-9120: Fix issue with unchecking radio default value

---

src/components/day/Day.js
test/unit/Day.unit.js

https://formio.atlassian.net/browse/FIO-9126
*Fixed the display of the Day component dataValue with hidden fields in the Data tab*
*n/a*
*n/a*

FIO-9126 fixed display of value for Day component with hidden fields

---

src/components/day/Day.js
test/forms/helpers/testBasicComponentSettings/form.js
test/unit/Day.unit.js

https://formio.atlassian.net/browse/FIO-9127
*Fixed the issue of saving an empty value for the Day component after deleting values from each of the fields (month, day and year). Previously, the last deleted field was not left empty, so after editing it was impossible to set an empty value for the day component. The issue of setting an empty value for the Day component with the default value has also been fixed*
*n/a*
*n/a*
*Automated test have been added. Al test pass locally*

FIO-9127 fixed saving an empty value for day component after deleting values

---

src/components/Components.js

https://formio.atlassian.net/browse/FIO-9153
After changes made in core by https://github.com/formio/core/pull/157, there was inconsistency in path calculation for tagpad that causes the validation for tagpad child components to be skipped. This PR fixes the path calculation.
Manually

FIO-9153: fixed an issue where tagpad components skip front-end validation before submission

---

src/components/day/Day.js
test/unit/Day.unit.js

https://formio.atlassian.net/browse/FIO-9196
**Issue**: The DataTable is calling the method `getValueAsString` to get the string representation of a value from the submission. The `getValueAsString` method internally calls the `getDate` method, which uses the default value of the component if the value is empty. This results in the DataTable showing the default value instead of a blank.
**Solution**: Add a check to see if the value is not set. If the value is not set, return an empty string without calling the internal method getDate.
Unit tests and manually

FIO-9196: Fixed issue with getting default value instead of requested value in Day component

---

src/components/day/Day.js

https://formio.atlassian.net/browse/FIO-9196
**Issue**: The 5.x renderer changed the emptyValue for the day component. The formio-viewer wasn't updated to use the 5.x renderer and is still using the 4.x version. As a result, the PDF server, which relies on formio-viewer to generate PDFs, encounters a small inconsistency. When the 4.x renderer encounters a 5.x emptyValue, it cannot handle it and uses the default value. This causes the PDF server to generate a default value for the 5.x empty value.
**Solution**: Add a check for an empty string, which is the emptyValue for the 5.x renderer, and use the emptyValue from the 4.x renderer instead.
Manually

[4.21.x] FIO-9196: Fixed the issue with empty value in Day component

---

src/components/_classes/component/Component.js
test/unit/Number.unit.js
test/unit/fixtures/number/comp11.js
test/unit/fixtures/number/index.js

https://formio.atlassian.net/browse/FIO-9144
There's a function called `restoreCaretPosition` in `Component.js` that restores the position of the input caret after a refresh. However, in this case, it was not taking the input value's delimiter's into account. It might have to do with the time it takes to update the input mask. This PR changes `restoreCaretPosition` to use the length of the input value instead of `root.currentSelection` so that delimiters are included in the `setSelection()` call.
The input value was already within the scope of the function; this solution doesn't mutate `root.currentSelection`.
n/a
n/a
Added test for number component that asserts the correct input selection start (caret/cursor) position after calling …

FIO-9144 Fix cursor jump in number component

---

src/components/_classes/component/editForm/Component.edit.conditional.js
src/components/_classes/component/editForm/Component.edit.data.js
src/components/_classes/component/editForm/utils.js
src/components/form/editForm/Form.edit.data.js

https://formio.atlassian.net/browse/FIO-9208
Changed all the urls that are referencing the github help page to go to help.form.io where we better maintain documentation.
None.
None.

FIO-9208: Changing the links to go to help.form.io instead of github page.

---

src/components/_classes/component/Component.js
src/components/editgrid/EditGrid.js
test/unit/Component.unit.js
test/unit/EditGrid.unit.js
test/unit/SelectBoxes.unit.js
test/unit/TextField.unit.js
test/unit/Webform.unit.js
test/unit/Wizard.unit.js

https://formio.atlassian.net/browse/FIO-9072
Removed the dirty flag being set to true on submission. This also required test changes because some tests set submissions and then check for visible errors using class names or message containers
This solution removes the root cause of errors unexpectedly occurring on form load by removing set submission causing components to become dirty
This PR goes directly against a previous test that I changed to should not show errors on ...
- it('Should show errors on setSubmission when providing explicit data values.')
N/A
One of the automated tests I changed makes sure that set submission does not create visible errors. I also manually tested

FIO-9072: removed setting dirty flag to true on set submission and changed tests

---

package.json
src/utils/conditionOperators/IsEqualTo.js
src/utils/formUtils.js
src/utils/utils.js
yarn.lock

https://formio.atlassian.net/browse/FIO-9189
Some methods have been moved to the core to prevent repetition of the logic.
https://github.com/formio/core/pull/174

FIO-9189: moved some methods to core

---

src/components/_classes/list/ListComponent.js
src/components/radio/Radio.js
src/components/selectboxes/SelectBoxes.js
src/components/textarea/TextArea.js

…tead of labels on View tab and in DataTable
https://formio.atlassian.net/browse/FIO-7195
Implemented changes required to force SelectBoxes/Radio components to use saved selectData when loaded options are not available (View tab/DataTable)

FIO-7195: Fixes an issue where Radio/SelectBoxes will show values instead of labels on View tab and in DataTable

---

src/components/day/Day.js
test/unit/Day.unit.js
test/unit/fixtures/day/comp5.js

https://formio.atlassian.net/browse/FIO-9197
Made a check to count before 9.3.x '00/00/0000' value as empty. Added convertion to an empty string if this value is met.
Checked against such scenarios, haven't noticed any issues
1) application that uses 4.x renderer works with 9.3.x server validations.
2) application that uses 5.x renderer works with 8.x server validations.
3) application that uses 5.x renderer works with 9.2.x server validations.
4) application that uses 5.x renderer works with 9.3.x server validations.
None
Automated test added

FIO-9197: Fix Day component triggered required validation when loading form

---

src/Wizard.js
src/components/form/Form.js
test/unit/Wizard.unit.js

https://formio.atlassian.net/browse/FIO-9259
*Previously, the parent wizard form displayed all the errors of the child wizard form when clicking the Next button. The issue became relevant after correcting the incorrect order of arguments for the `checkValidity` method. The problem has been fixed by adding an additional check for the embedded child form*
*n/a*
*n/a*

FIO-9259 fixed errors list for parent wizard with nested wizard

---

src/components/_classes/nested/NestedComponent.js
src/components/editgrid/EditGrid.unit.js

https://formio.atlassian.net/browse/FIO-9176
The problem was caused by the absence of instance.component.path for components inside rows of components such as edit grid. So in the validation processor for nested components, the instance.component.path is updated with current data from component.path (obtained from eachComponentData (core)).
This allows to get full path to components inside components such as edit grid and avoid an error when there are components with same key inside and outside edit grid component. Which ensures correct access to the component via the reference in the validation error.
-
-
autotests
manually

FIO-9176: updated instance.component.path

---

src/Webform.js
test/unit/Form.unit.js

https://formio.atlassian.net/browse/FIO-9246
*Fixed the behavior of the Save as draft functionality, in which a request was sent to save a draft for a child form when the reference property was set to false. Now, if the reference property is set to false, then the draft is saved only for the parent form*
*n/a*
*n/a*

FIO-9246 fixed saving draft for form with nested form and reference false

---

src/components/select/Select.js

https://formio.atlassian.net/browse/FIO-9205
Changed set metadata condition to prevent setting wrong labels.
n/a
https://github.com/formio/formio.js/pull/5863
manually

FIO-9205: fixed labels in select filter feature

---

src/components/selectboxes/SelectBoxes.js

https://formio.atlassian.net/browse/FIO-9280
*Added value property validation for the Select Boxes component in the form builder. Now, when trying to save a component, the value property validation is triggered. If the value property is invalid, an error appears and the selectboxes component is not saved.*
*n/a*
*https://github.com/formio/core/pull/185*
*locally, automated tests have been added*

FIO-9280 fixed value property validation

---

src/components/radio/Radio.js
test/unit/Radio.unit.js

https://formio.atlassian.net/browse/FIO-9290
Always redraw the radio/selectboxes after request promise is resolved/rejected to remove the loader.
Manually + tests

FIO-9290: fixed an issue where infinite loader is shown when radio/selectboxes with url type is failed to load options

---

src/components/radio/Radio.js

https://formio.atlassian.net/browse/FIO-9280
*Fixed an issue where validation was triggered with the correct value for items of the SelectBoxes component if Value Property was not set*
*n/a*
https://github.com/formio/core/pull/185
https://github.com/formio/formio.js/pull/5894 
*locally. Automated test have been added previously *

FIO-9280 fixed validation for select boxes with valid values and when value property is not set

---

src/components/_classes/component/Component.js
test/unit/TextField.unit.js

https://formio.atlassian.net/browse/FIO-9217
When attempting to populate a text field component with a calendar widget with a custom default value that is a moment.js datetime the value eventually renders as empty string after initially rendering as the correct value. For some reason the default mask in component.js was being set to an empty array in this scenario. 
Check for empty array in component.js to avoid erroneously setting the default value to an empty string. 
It was minimally invasive and is a check that should be in place already. If we don't have any masks in the default masks array, we don't want to treat it like we do have a mask. Empty arrays in JS evaluate as true, but we only want to execute the code if we actually …

FIO-9217 Fix: allow moment.js datetime custom default values in calendar widget-text field components

---

src/components/signature/Signature.js

https://formio.atlassian.net/browse/FIO-8677
showCanvas(true) should be never called if component is disabled since it will make it drawable (which should not happen in disabled state) 

FIO-8677: Fixes an issue where its possible to draweon Signature on the View tab of PDF form

---

src/components/_classes/component/editForm/Component.edit.validation.js

https://formio.atlassian.net/browse/FIO-9329
Updated the tooltip for the `validateWhenHidden` parameter.
n/a
n/a
n/a

FIO-9329: update tooltip for validateWhenHidden

---

src/WebformBuilder.js

https://formio.atlassian.net/browse/FIO-8518
*Fixed an issue when Checkbox (Radio type) Component can be added more than one time to the PDF Designer page. The code was upgraded and the duplication was removed*
*n/a*
*n/a*
*all test pass locally*

FIO-8518 fixed adding checkbox with radio type to pdf design page

---

src/components/hidden/Hidden.js
src/components/select/editForm/Select.edit.data.js

https://formio.atlassian.net/browse/FIO-9314
Changed the selectData property to be a hidden component and made hidden components empty values be null
The selectData property is a property that needs to be on the select component in certain cases but does not need to be shown or modified directly by a user. Making it a hidden component removes it from the edit form and making the hidden component have a empty value of null allows tests to pass. The reason why I thought it was ok to change the hidden component empty value to null is because the hidden component is usually used to store some kind of meta data in the form. This means the hidden component can be used to store any type of data such as Strings, Numbers, Objects, etc. It …

FIO-9314: made select data property a hidden component and changed hidden component empty value to null

---

src/Wizard.js
src/components/form/Form.js
test/unit/Wizard.unit.js

https://formio.atlassian.net/browse/FIO-9360
This PR reverts:
* #5884 
* #5830 
to consolidate validation of Wizard components into one simple rule: on change, only validate and show the current page's validation errors unless you've already attempted to submit the form.
Technically this is a breaking change - previously, the renderer would validate all components (much like it does with forms) and selectively display them based on the UI's context. However, this proves to be tricky with nested forms, and it's easiest to just only validate the currently displayed components when it comes to wizards.
n/a
All tests pass. Added a few automated tests to ensure that Wizards will only validate currently displayed components.

FIO-9360: validate current page only on wizard change

---

src/WebformBuilder.js

https://formio.atlassian.net/browse/FIO-9386
Removed logic from the default value settings in the component builder settings as the advanced logic can add properties (e.g. hidden, required) or values that cause issues with setting/saving the default value.
Manually

FIO-9386: fixed an issue where configured logic prevents the component settings saving because of validation configured in logic

---

src/Wizard.js
test/forms/simpleWizardWithRequiredFields.js
test/unit/Wizard.unit.js

https://formio.atlassian.net/browse/FIO-9350
- Updated `setPage()` to display form errors if the form has failed to submit. `setPage()` is called when a user clicks 
directly on a Wizard nav link/button, but `onChange()` is not (this bug was fixed for `onChange()` by [FIO-9360](https://github.com/formio/formio.js/pull/5920)). 
- Updated `nextPage()` to check for failed submission; if there has been, display all the form errors. This is necessary for when a user clicks the "next" button without having resolved the error for that page. It causes validation to trigger for the current page only and wipes the other form errors. 
- Updated `get errors()` a.k.a. `this.errors` to grab the form-level errors if the form previously failed to submit. While `this.showErrors()` …

FIO-9350 Wizard: Show form-level errors after failed submission on subsequent form interaction when current page has no errors

---

src/components/_classes/component/Component.js

https://formio.atlassian.net/browse/FIO-9027
*Fixed the display of overridden calculated component values on pdf download page. This case was tested locally and it turned out that the issue is relevant not only for the Checkbox component, but also for other components (Text Field, Text Area, Select, etc.). When the `allowCalculateOverride` property is set to `true` and the calculateValue is set, Components saved as empty values are displayed as calculated on the pdf download page. This was fixed by adding a case where the calculation should not be fired.*
*n/a*
*n/a*
*locally using pdf-server*

FIO-9027 fixed display of the overridden values on download page

---

src/components/number/Number.js
src/components/number/Number.unit.js
src/components/number/fixtures/scientificNotation.js

https://formio.atlassian.net/browse/FIO-9271
Adding Scientific notation to the number component 
We needed to identify and show scientific notation in the component
NA
@formio/text-mask-addons
Unit Tests

FIO-9271: Scientific notation in number component.

---

src/components/editgrid/EditGrid.js

https://formio.atlassian.net/browse/FIO-9418
We previously used to show the "wrapper" error around the EditGrid component when a value inside the EditGrid is invalid. This was recently changed to where we only show the error around the component that has the problem. This works fine until that component is "hidden" to where you don't see any visual feedback if your row is invalid. This change ensures that we add the "wrapper" error around the EditGrid when a row error occurs which always gives the user a visual feedback if an EditGrid component is invalid.
This does re-introduce the error "wrapper" around the EditGrid, even if the error in the row is visually seen. Some may see this as "to many" visual indications of an error, but this also goes back to the way it used to work.
None …

FIO-9418: Fixed the edit grid errors to show the outer error wrapper if any fields in the edit grid are invalid.

---

src/components/form/Form.js

https://formio.atlassian.net/browse/FIO-8195
**Issue**: PDF generation can use the `viewer:show` tag to display hidden components. However, the `isHidden` method in the Form component does not consider the `options.show` property (which checks the `viewer:show` tag). As a result, the subform is not loading at all.
**Solution**: Update the `isHidden` method to take into account the `options.show` property.
Manually

[4.21.x] FIO-8195: Fixed visibility of nested form in pdf with viewer:show tag

---

src/WebformBuilder.js

https://formio.atlassian.net/browse/FIO-9339
This PR fixes an issue where the preview shows an error instead of the component when the component settings are opened in the JSON mode. When the component is edited in JSON mode, the component settings are stored not on the top level of the edit form submission data, but inside the componentJson property of the data. This PR add this case.

FIO-9339: fixed an issue where preview shows an error when editing component JSON

---

src/components/editgrid/EditGrid.js

https://formio.atlassian.net/browse/FIO-8862
Redraw the the grid that has components with 'typeChangeEnabled' only when the type is really changed.
https://github.com/formio/premium/pull/361
Manually

FIO-8862: fixed unnecessary redrawings of the value component in conditional ui

---

src/formio.form.js

https://formio.atlassian.net/browse/FIO-9170
Previously, if a module (i.e. premium) had their own components, there was no fallback for the template in the case of  different template library usage (i.e. if 2 modules were registered and on of them is currently in use, then the components from the other were using defaultTemplate fallback, which was always just a bootstrap set of templates. I've added an ability to add extra components to the defaultTemplates when registering modules, so that for every module there is a fallback for their own components inside of the defaultTemplates
Tested locally

FIO-9170 Added a fix for default templates to include custom components

---

src/components/form/Form.js

https://formio.atlassian.net/browse/FIO-9480
Sometimes a deeply nested child needs state or data from a distant parent, and needs to crawl up the reference tree to get it. E.g. a calculated value that looks like 
```javascript
const myValue = instance?.root.parent?.root?.parent?.root?.parent?.data?.role;
``` 
Previously these references were not stable, because they were being instantiated _after_ subForm creation. This PR fixes this behavior so that they are passed along with the creation options, and those references will be stable from the start.
n/a
n/a

FIO-9480: ensure parent references are stable before subform creation

---

src/formio.embed.js

https://formio.atlassian.net/browse/FIO-9552
The "formio.embed.js" file on the CDN was throwing an error that the "Formio" class was undefined. Turns out, this was not getting exported and picked up on by Webpack so it was not getting defined as a global. This simply ensures that it is exported so that it will be defined globally.
None
None
Manual

Fixing the embed code to export the Formio construct.

---

src/components/datetime/DateTime.js
src/components/textfield/TextField.js
test/unit/DateTime.unit.js
test/unit/TextField.unit.js
test/unit/fixtures/datetime/index.js
test/unit/fixtures/datetime/requiredFieldLogicComp.js
test/unit/fixtures/textfield/index.js
test/unit/fixtures/textfield/requiredFieldLogicComp.js

- originalComponent in Component.js did not capture non-default widget settings since they were added after component initialization
- During field logic evaluation, the component was falling back to originalComponent and not preserving the widget settings
- Update originalComponent after applying widget settings in TextField and DateTime to maintain them after field logic eval
https://formio.atlassian.net/browse/FIO-9385
Set `this.originalComponent` in the `DateTime` and `TextField` components. Since `this.originalComponent` was only being set when the component was initialized and the non-default widget settings are applied after, none of those widget settings were preserved after field logic was evaluated (see …

FIO-9385 Preserve non-default widget settings after evaluating field logic

---

gulpfile.js
package.json

https://formio.atlassian.net/browse/FIO-9482
*Fixed setting the Formio.version property. Previously  the Formio.version property was set as 'FORMIO_VERSION' and was not overwritten according to the version installed in package.json during the build process. This meant that the grid library was loaded only from cdn.form.io (instead of cdn.test-form.io for testing), because 'FORMIO_VERSION' doesn't include 'rc'. It was fixed by adding a gulp task and replacing the static 'FORMIO_VERSION' with the appropriate FJS version.*
*n/a*
*n/a*

FIO-9482 fixed setting Formio version

---

src/sass/formio.form.scss

https://formio.atlassian.net/browse/FIO-9453
Select components in Bootstrap 5 had no static height - it turns out that Bootstrap 5 removed the static height declaration for the `.form-control` class. This PR adds it in the formio global styles for backwards compatibility.
A possible alternative involved adding this style, perhaps inline, to the select component's bootstrap5 template. However, this would not work - choicesjs masks the actual input, so nothing in the template would really have a visual effect. Furthermore, we need to modify the select's parent element, and it the [renderer handles adding the class in question](https://github.com/formio/formio.js/blob/3ff37eb652a83ecc88dac3e3788283d97e7cac27/src/components/_classes/component/Component.js#L3912).
n/a
n/a
n/a

fix select styling

---

src/widgets/CalendarWidget.js
test/unit/DateTime.unit.js

https://formio.atlassian.net/browse/FIO-8372
*Since flatpickr and fjs have been updated and now onChange method is triggered with every change, [these changes](https://github.com/formio/formio.js/pull/2723) are outdated and cause regression, when it is impossible to set a new date on the first attempt after erasing the previous one. The outdated code has been removed.*
*n/a*
*n/a*
*Automated test has been added. All tests pass locally*

FIO-8372 fixed setting date after selecting and erasing entire date

---

src/Wizard.js
src/components/form/Form.js
test/unit/Wizard.unit.js

https://formio.atlassian.net/browse/FIO-9517
The validation process of the wizard form with embedded forms using lazy loading has been fixed.
In the beforeSubmit method of the FormComponent class, the following changes were made:
• Added a check to verify whether all nested forms with lazyload = true have been loaded.
• If not, the missing forms are loaded.
These changes ensure that the submission data is validated correctly on the client side, meeting all requirements (including rules for all nested forms) without sending submission POST request to the server.
-
autotests,
manually

FIO-9517: nested forms with lazy load validation fix

---

src/components/_classes/component/Component.js

closely related, but not directly responsible for the initial bug. It was discovered while working on:
https://formio.atlassian.net/browse/FIO-9499
Updated check from `typeof ref === NodeList` to `ref instanceof NodeList` since the former returns `'object'` and not what we're checking for `'NodeList'`.
So that the result of this conditional is what we're expecting.  
n/a
n/a
Manual testing + automated test in `formio` repo https://github.com/formio/formio/pull/1885.

FIO-9499 Component: Check if ref is instance of NodeList on detach

---

src/components/file/File.js
src/providers/storage/googleDrive.js

https://formio.atlassian.net/browse/FIO-9207
Added new params in the URL construction to switch between weblink and webcontentlink using google drive endpoint.
As per Google Drive documentation in order to render the image in a img tag we need to use /thumbnail endpoint and to preview the image we need to use the weblink by default.
None
Change in Server: [PR](https://github.com/formio/formio-server/pull/1620)
Manually

FIO-9207: Fix image preview for file component when using google drive

---

src/components/_classes/nesteddata/NestedDataComponent.js
test/unit/Container.unit.js
test/unit/EditGrid.unit.js

https://formio.atlassian.net/browse/FIO-9548
The issue with calculations was caused by incorrect filling of form._data, which led to incorrect data in submission data and calculation errors when components related to form with noDefaults option is set to true. (loss of data structure information for Container component, loss of the first row for EditGrid component).
Adding method shouldAddDefaultValue  to NestedDataComponent prevents this problem.
-
autotests,
manually

FIO-9548:fixed setting of form._data for  NestedDataComponent into forms with noDefaults option

---

src/components/form/editForm/Form.edit.form.js
src/components/select/editForm/Select.edit.data.js
test/unit/Form.unit.js

https://formio.atlassian.net/browse/FIO-9504
Changes the copy around "Save as Reference" to "Submit as Reference"
n/a
n/a
n/a

update copy around save as reference

---

src/Webform.js
src/components/_classes/component/Component.js

https://formio.atlassian.net/browse/FIO-9020
Use _.once to make executeFormController to be called once only per Webform instance. We were constantly facing the issue where it was called multiple times even for the same form because of apps like our formio-app were calling setForm multiple times with the same form object, but we can't rely on the comparison between current this._form and the form being set since sometimes we will get minified form schema in, sometimes not, and the components indside this._form are getting hydrated after components creation proccess either way. 
*Use this section to list any dependent changes/PRs in other Form.io …

FIO-9020: Made executeFormController to be called once only for Webform instance

---

src/providers/storage/s3.js
src/providers/storage/xhr.js

https://formio.atlassian.net/browse/FIO-8208
The file upload requests were not using the x-remote-token. This is because the plugins to alter the request options is not swapping out the token to use the remote token if it is available.
None
N/A
N/A

FIO-8208: Ensure that all file uploads alter the request options before sending the fetch requests.

---

src/components/datetime/DateTime.js
src/utils/utils.js
test/unit/DateTime.unit.js

https://formio.atlassian.net/browse/FIO-9640
Added options passing to 'getValueAsString' of DateTime component, so to make sure timezone offset is applied for emailed submissions
formio/vm/pull/49
Automated test is added

FIO-9640: Fix date components have wrong timezone in email

---

src/Webform.js
src/Wizard.js

https://formio.atlassian.net/browse/FIO-9720
*Previously, there was an issue with rendering and verification captcha using cloudflare provider for wizard forms, if the captcha component was not on the first page. The reason for the issue was that the verification took place before the rendering of the component and, accordingly, the rendering of the captcha widget. The problem was fixed by adding a captcha cloudflare trigger when setPage for wizard forms.*
*n/a*
*https://github.com/formio/premium/pull/376*
*locally using cloudflare CAPTCHA provider*

FIO-9720 fixed triggering captcha for wizard

---

src/WizardBuilder.js

FIO-9569-wizard-page-copying
Before Wizard's builder pastComponents handler was performing a check weather the component parameter is a Wizard's page or not to either call addPage method or pass it to the parent's pastComponent method. But the issue was that it was passing the 'component' (which is actually a component on which 'Paste After' was clicked) parameter from pasteComponent method to the addPage method, so it was always adding a current page instead of the copied one.
Now we check if we are trying to paste after the existing Wizard's page, get the copied component's schema and check if it is a panel (since we can't paste anything else as a page) and only after that pass it to the addPage method.  
*Use this section to describe any potentially breaking changes this PR introduces …

FIO-9569: Fixes an issue where Wizard will paste a copy of the current page instead of the copied one

---

src/components/form/Form.js
test/forms/nestedFormWithContentComp.js
test/unit/Form.unit.js

https://formio.atlassian.net/browse/FIO-9758
When the submission is rendered is PDF format, the formio-viewer sets the submission and after that waits until the dataReady promise is resolved. It appears that the dataReady promise is resolved for nested forms before the data is actually set because the data is considered to be ready when the subFormReady promise is resolved.  Because of it, the pdf file can be generated before all submission data is correctly set and displayed.
This PR makes it so that the nested form data is considered to be ready when the subForm data is ready. This allows to wait until all nested form data is set and only after that the PDF is generated. 
Manually + tests

FIO-9758: fixed an issue where interpolated content data is not displayed in PDF download

---

src/WebformBuilder.js

https://formio.atlassian.net/browse/FIO-9811
*Fixed drag and drop for custom component. The reason for the issue was that the component with the custom type has an unknown key.*
*n/a*
*n/a*
*locally*

FIO-9811 fixed drag and drop for custom component

---

src/components/form/Form.js
test/unit/Form.unit.js

https://formio.atlassian.net/browse/FIO-9815
Do not load/recreate subForm in beforeSubmit if it has already been created. beforeSubmit does not call attach method of the subForm, it means that new subForm will not have refs where error classes can be set.
Also this PR refactored a bit then statement with submitSubForm call in order to make sure that it waits submitSubForm promise to be resolved.
Manually + tests

FIO-9815: fixed an issue where nested form inside wizard does not highlight validation errors

---

src/Wizard.js
src/components/_classes/component/Component.js
src/components/_classes/nested/NestedComponent.js
src/components/datagrid/DataGrid.js
src/components/editgrid/EditGrid.js
src/components/select/editForm/Select.edit.data.js
src/utils/utils.js
test/unit/Select.unit.js
test/unit/Wizard.unit.js

https://formio.atlassian.net/browse/FIO-9856
This changes multiple issues:
1.) Performance issues - It was identified that a major performance bottleneck was that clearOnHide was being called within the checkComponentConditions method. The issue is that clearOnHide for NestedComponents iterate through all the children to perform clearOnHide for those children. The problem presents itself within the checkData loop where it is already iterating through all of the children and performing these checks, so adding multiple tree iterations is a major performance drain. This solves the problem by implementing a clearComponentOnHide method which is not implemented by the NestedComponent class, and that method is what is called within the checkComponentConditions method.
2.) Data Map data model …

Fixing issues with the data map and unnecessary reset model functions.

---

src/WebformBuilder.js
test/unit/WebformBuilder.unit.js

https://formio.atlassian.net/browse/FIO-9838
hasEditTabs will return false if the component type does not exist
hasEditTabs should stop checking if a component has editTabs if the component does not exist
N/A
N/A
Manually and automated tests

FIO-9838: fix rendering an unknown component on the builder causing error

---

src/Wizard.js

https://formio.atlassian.net/browse/FIO-9721
*The Submit button is not displayed in the "Button Key" field for the CAPTCHA component with the "Button Click" event in wizard forms, because for the wizard form, the Submit button is not a component, but is part of the Wizard template. The problem of setting the CAPTCHA verification event by clicking on the Submit button was fixed by adding the appropriate option for Wizard forms and the CAPTCHA verification method trigger before submitting the Wizard form.*
*n/a*
*https://github.com/formio/premium/pull/373*

FIO-9721 Added Submit button as available trigger option of captcha inside Wizard

---

src/components/address/Address.js
src/components/address/editForm/Address.edit.provider.js

https://formio.atlassian.net/browse/FIO-9837
Removed nested keys via the providerOptions and providerOptions.params
Cleanup code to make sure that this change does not break other areas of code
providerOptions.params is conditionally hidden. Because providerOptions.params.key is displayed and providerOptions.params is conditionally hidden whenever you try to input into providerOptions.params.key it will immediately clear itself. To be honest I think this method of creating nested keys using dot (.) is wrong. If you want a component to be namespaced or have some kind of object like pathing then put it in a container component.
You will no longer be searching through component.providerOptions.[key] to find information about the …

FIO-9837: cant approve valid api key

---

src/components/address/Address.js

https://formio.atlassian.net/browse/FIO-9889
Added a backwards compatibility check that will populate the appropriate JSON properties for the address component. 
If someone's address JSON is using the legacy providerOptions object this will take the properties of that object and assign them to the new JSON properties. e.g. this.component.providerOptions.params.key would be assigned to this.component.apiKey
N/A
N/A
Manually tested

FIO-9889: added backwards compatibility checks for provider options

---

src/components/_classes/nested/NestedComponent.form.js
src/components/content/editForm/Content.edit.display.js
src/components/currency/editForm/Currency.edit.display.js
src/components/day/editForm/Day.edit.display.js
src/components/email/editForm/Email.edit.display.js
src/components/fieldset/editForm/Fieldset.edit.display.js
src/components/hidden/editForm/Hidden.edit.display.js
src/components/html/editForm/HTML.edit.display.js
src/components/number/editForm/Number.edit.display.js
src/components/password/editForm/Password.edit.display.js
src/components/phonenumber/PhoneNumber.form.js
src/components/tabs/editForm/Tabs.edit.display.js
src/components/textarea/editForm/TextArea.edit.display.js
src/components/url/editForm/Url.edit.display.js
src/components/well/editForm/Well.edit.display.js

https://formio.atlassian.net/browse/FIO-9842
*Extra options were removed from the Form Builder configurator:*
- *Widget and Widget Settings options for Number, Password, Text Area, Email, URL, Currency, Phone Number components. The conditions for the Widget property set that it is relevant only for a component with the textfield type, and the Widget Setting property depends on the Widget property, so it is also relevant only for the Text Field component.*
- *Input Masks option for Number, Password, Text Area, Email, URL, Currency components. The conditions for the InputMasks property set it to be relevant only for components with the allowMultipleMasks property set to true, but the allowMultipleMasks property is ignored for all of the above components, so the InputMasks property is also …

FIO-9842 removed extra options

---

src/components/file/File.js
test/forms/formWithFileComponent.js
test/unit/File.unit.js

https://formio.atlassian.net/browse/FIO-9866
The fileUploadingEnd and fielUploadingStart events were unintentionally removed after refactoring the file component logic by this PR: https://github.com/formio/formio.js/pull/5367. This PR moved the events back to provide compatibility with 4.x.
Manually + autotests

FIO-9866: added  fileUploadingEnd and fielUplaodingStart events back

---

src/components/select/editForm/Select.edit.data.js

https://formio.atlassian.net/browse/FIO-9855
*Since the `indexeddb` option was deleted according to [FIO-4103](https://formio.atlassian.net/browse/FIO-4103),the corresponding properties for `dataSrc ===' indexeddb'` condition were deleted from Data tab of Modal Edit window for Select Component. At the same time, all the functionality for  `dataSrc ===' indexeddb'` was remained unchanged.*
*n/a*
*n/a*
*locally. All tests pass locally*
[FIO-4103]: https://formio.atlassian.net/browse/FIO-4103?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIO-9855 removed deprecated settings

---

src/components/_classes/component/Component.js

https://formio.atlassian.net/browse/FIO-9888
Previously, we had a "noDefaults" flag, whose purpose is to not establish the default values for all components within a form when the form is initialized. The reason for this flag is to ensure that we "minify" the submission data when the form is established. This flag, however, should not skip over any calculated default values as well as any explicitly defined default values provided within the component settings. This change ensures that the defaults are still established if the calculated defaults are provided and the noDefaults flag is set in the form options.
None
None
The project settings form in the Developer Portal uses the "noDefaults" flag, but there are many calculated default values (such as API Keys) which need to still function …

FIO-9888: Fixed issue where the noDefaults flag would skip defaults even for calculations.

---

src/components/_classes/component/Component.js
src/components/form/Form.js

https://formio.atlassian.net/browse/FIO-9913
https://formio.atlassian.net/browse/FIO-9912
With the recent changes, all of the behavior for clearOnHide was correct except the case where your value is set to "clearOnHide", but your parent has the clearOnHide set to false. This was causing some erroneous clearing of values deeply nested within nested data components (datagrid, editgrid, etc).
None
None
Manual

FIO-9913: Fixed problems where conditionally hidden fields would reset when their parents are hidden but have clearOnHide set to false.

---

src/components/address/editForm/Address.edit.display.js

https://formio.atlassian.net/browse/FIO-9912
So, now that we have fixed the default value and the clear on hide functionality, this was a case where it was relying on a bug to work, and now that we fixed the bugs, the clear on hide is doing what it was supposed to do and reset the value of the "Switch to Manual Mode" text field.  
This field has "clearOnHide" set to "true", and when the checkbox is checked to enter manually, it hides the field clearing the value (as it should). This simply adds the default value to the field so that if you check the checkbox again, it sets the default of the field to what the value should be.
None
None
Manual

FIO-9912: Fixed issue where the default value of the address component would clear and not reset.

---

src/components/_classes/component/editForm/utils.js
src/components/_classes/component/editForm/utils.spec.js

https://formio.atlassian.net/browse/FIO-9851
https://formio.atlassian.net/browse/FIO-9856
*Previously, some component configuration fields in the modal Edit Form window could not be hidden when set in the Form Builder options `ignore: true` flag. This was fixed and now options can be hidden if necessary by setting the ignored flag to true.*
*n/a*
**
*Automated test was added/ all tests pass locally*

FIO-9851 fixed appearing configurable component options

---

src/WebformBuilder.js

https://formio.atlassian.net/browse/FIO-9872
*Fixed the opening of the Edit modal window when adding a new Custom component*
*n/a*
*n/a*

FIO-9872 fixed opening modal edit window for custom component

---

src/components/survey/Survey.js
test/renders/form-bootstrap-advanced.html
test/renders/form-bootstrap-defaults.html
test/renders/form-bootstrap-readOnly-advanced.html
test/renders/form-bootstrap-readOnly-defaults.html
test/unit/Survey.unit.js
test/unit/fixtures/survey/comp3.js
test/unit/fixtures/survey/index.js

https://formio.atlassian.net/browse/FIO-9510
**Issue**: When creating a wizard form and adding the same nested form with a survey component to every page, exporting the form to a PDF causes the wizard form to transform into a webform with panels instead of pages. As a result, all survey components are rendered in a single HTML structure.
The survey component internally uses a radio input, and the issue arises in the `getInputName` method of the survey component. This method generates the radio input name using the question value and option value. Consequently, all survey components from the nested form end up with the same input name. This causes a conflict where selecting a radio input in one survey component unchecks the radio input in another survey component.
**Solution**: To resolve …

FIO-9510: Fixed the issue with multiple survey components

---

src/components/unknown/Unknown.form.js

https://formio.atlassian.net/browse/FIO-9854
*Previously, the fields of the edit modal window for Custom Component settings were displayed even when the Form Builder options were set to ignore = true. This was fixed by adding extend argument to the EditForm Custom Component.*
*n/a*
*https://github.com/formio/enterprise-builder-core/pull/13*
*https://github.com/formio/premium/pull/387*
*locally using EFB and demo app*

FIO-9854 fixed appearance of the custom component edit fields

---

src/components/_classes/component/Component.js
src/components/editgrid/EditGrid.js
src/components/unknown/Unknown.form.js
test/unit/Tags.unit.js

https://formio.atlassian.net/browse/FIO-9921
Since we made changes to the way components' paths are stored and constructed, one crucial element of a correct path is the "local" flag, which determines whether or not a component should be pathed as "local" (i.e. to the current form context) or not (i.e. when it is participating in the process as a nested form). 
This PR fixes an issue in EditGrid in which the local option was not being passed to a specific validation step. What's odd is that EditGrid appears to be the _only_ component that calls the `invalidMessage` function and that validation step appears to be redundant, but for the sake of risk factor and incrementalism I've decided to just pass the option rather than taking the drastic step of removing the function call entirely.
n/a …

FIO-9921: fix issue with local paths not being propogated to edit grid

---

src/components/select/editForm/Select.edit.data.js

https://formio.atlassian.net/browse/FIO-9933
Now that the default value and clearOnHide work as expected, the default value of the Lazy Load option is clearing (as it should) when it is defaulted. The solution is to set the default value of the Lazy Load option to "true".
None
None
Manual

FIO-9933: Fixed the default value for the Lazy Load option for Select dropdowns.

---

src/components/datetime/editForm/DateTime.edit.validation.js
test/forms/formWithMergeComponentSchemaAndCustomLogic.js
test/unit/Webform.unit.js

https://formio.atlassian.net/browse/FIO-9931
When the min/max date is configured in datetime component settings in builder, the user can choose the mode for the value: calendar picker or just textfield where the user can use moment() function. Before we used two conditional components with the same key that become visible based on the mode. It worked more or less good until the clearOnHide and conditional checks in general were refactored (commits https://github.com/formio/formio.js/commit/d70fdbaf1306974d82600ba9ece25ab4379b21ce#diff-8795d5891ca105e3583ef74383eb1929aeec1fa888d641a0d7be8a91a0abd5f4 and https://github.com/formio/formio.js/pull/6048/files#diff-05d41a5d854049f92f62772ee82f295d614534d5f4f0717b3ec30c69dfc3a7f5). So, when the one component is hidden, it is …

FIO-9931: fixed an issue wehre min and max date settings are not saved in builder

---

src/components/_classes/list/ListComponent.js
test/forms/formWithHiddenComponents.js
test/unit/Webform.unit.js

https://formio.atlassian.net/browse/FIO-9902
https://formio.atlassian.net/browse/FIO-9878
When the formio-viewer renders submission on the pdf-server, it waits until dataReady is resolved. But the dataReady is not resolved for list components when they are hidden that courses the PDF not to be generated. This PR fixes it.
https://github.com/formio/premium/pull/389
manually + tests

FIO-9902-9878: fixed an issue where PDF is not loaded for the form with hidden/conditionally hidden select

---

src/providers/storage/uploadAdapter.js
test/unit/TextArea.unit.js

https://formio.atlassian.net/browse/FIO-9884
**Issue**: In CKEditor, any plugin should have a constructor. Currently, we have a `getFormioUploadAdapterPlugin` function that returns another function, which is intended to act as the plugin's constructor. However, this returned function is an arrow function, and arrow functions cannot be used as constructors.
Previously, when we used Babel as the transpiler, it converted arrow functions into function expressions, which worked as expected. However, since we switched to TypeScript for the build process, the arrow function remains unchanged, leading to issues with CKEditor.
**Solution**: Update the `getFormioUploadAdapterPlugin` function to return a function expression instead of an arrow function, ensuring compatibility with CKEditor.
Unit …

FIO-9884: Fixed file upload plugin for ckeditor

---

src/utils/utils.js

https://formio.atlassian.net/browse/FIO-9496
https://github.com/formio/angular/issues/1016
in utils fastCloneDeep now native API structuredClone is used instead of JSON.parse(JSON.stringify(obj))
Native browser API
And structuredClone allows to keep File object in event copy. More details in question link above https://github.com/formio/angular/issues/1016
allows to keep File object in event copy. More details in question link above https://github.com/formio/angular/issues/1016
*Use this section to describe any potentially breaking changes this PR introduces or any effects this PR might have on backwards …

Replace in utils fastCloneDeep func cloning with json.parse-stringiry to structuredClone api

---

src/WebformBuilder.js
src/components/_classes/component/Component.js
src/components/form/Form.js
test/unit/Form.unit.js
test/unit/clearOnHide.unit.js

https://formio.atlassian.net/browse/FIO-9937
There was previously a file that would perform all the tests for clearOnHide within the "test/unit" folder. This file was unfortunately not being executed because it did not have the "unit.js" extension. Once I enabled this file, it indicated a few edge cases where the clearOnHide functionality was not working within nested forms.
This also highlighted a few performance issues with the existing checks being made, as well as some legacy code that was checking the isEmpty() for nested forms, which caused major performance issues as it would iterate through all the children to check their emptiness... this was only being added to fix a bug with regards to customDefaultValues in nested forms.
None
None
New automated tests added.

Fixed edge cases for clearOnHide with nested forms + new test cases.

---

src/utils/utils.js

Reverts formio/formio.js#5942 because tests were failing

Revert "Replace in utils fastCloneDeep func cloning with json.parse-stringiry to structuredClone api"

---

src/components/textfield/TextField.js
src/utils/utils.js
src/widgets/CalendarWidget.js

https://formio.atlassian.net/browse/FIO-9847
Added encoded timezone checks to determine if setting a timezone value should use the plain text timezone
Trying to make changes without breaking anything
If a time does not have timezone information attached to it then it will be treated as plain text for textfields
N/A
manually tested

FIO-9847: time on textfield only changes when timezone included

---

src/Webform.js

https://formio.atlassian.net/browse/FIO-9992
We're still using @formio/js for email rendering on the server ([soon to change!](https://github.com/formio/vm/pull/57)) and it appears that the captcha trigger is causing problems, namely because the Captcha component appears to the server as a Hidden component. I'm not sure if this is because the vm library is not properly loading premium components or what, but because this is a blocker right before release and because presumably you shouldn't need to trigger the captcha component just to render an email, I've gone ahead and gated the captcha trigger to client-side stuff only.
n/a
n/a
n/a

FIO-9992: check for server when triggering the captcha

---

src/components/datagrid/DataGrid.js
test/unit/DataGrid.unit.js
test/unit/fixtures/datagrid/index.js
test/unit/fixtures/datagrid/wizardWithDataGridWithNestedForm.js

https://formio.atlassian.net/browse/FIO-10005
*Previously, for a Wizard form with DataGrid component with Nested Form component validation did not trigger when clicking on the Next Page button. This happened because after loading the nested form inside Data Grid component, the DataGrid component did not update the schema of the nested form component, which led to the fact that when iterating the components with `eachComponentData` method, the nested form did not include `components` object and the iterations stopped. This issue was fixed by checking changes of the Nested form component inside DataGrid using onChange method.*
*n/a*
*n/a*
*Automated tests were added. All tests pass locally*

FIO-10005 fixed next page validation for DataGrid with NestedForm

---

README.md

https://formio.atlassian.net/browse/FIO-9986
Change README for missing styles.
Discussed 
NA
NA
Manual

FIO-9986: Fix README example

---

src/Wizard.js
src/components/_classes/nested/NestedComponent.js
test/forms/wizardWithNestedWizardsAdvConditional.js
test/unit/Wizard.unit.js

https://formio.atlassian.net/browse/FIO-9241
I updated the `onChange()` method in the Wizard class to call `this.setPage()` if the number of total pages in the parent/root-level wizard changes, which updates the current page of the root wizard to be the current page/page (i.e. `this.currentPanel`. `this.setPage()` was not being called `onChange()` for wizards with sub-wizards. I also updated `render()` to set `this.currentPanel` based on `id` and not `key`.
I changed `onChange()` in the way that I did to simplify the logic for when to set the current page and to ensure that the correct page is selected based on a (more) unique `id` and not `key`, which could be easily duplicated between sub-wizard pages.
For the update to …

FIO-9241: Correctly set current page after conditionally hiding page in sibling nested wizard

---

src/components/_classes/component/Component.js
test/unit/TextArea.unit.js
test/unit/fixtures/textarea/comp5.js
test/unit/fixtures/textarea/index.js

https://formio.atlassian.net/browse/FIO-10096
The infinite loop happened because for the html mode **this.refs.input** does not contain elements ref = "input" in template and as a result the redraw method began to be called an infinite number of times. I added a check to get out of this loop
n/a
I added unit test

FIO-10096: Text Area causes infinite loop in html render mode

---

src/components/form/editForm/Form.edit.form.js

https://formio.atlassian.net/browse/FIO-10040
Improved the condition for lazyLoad option in the nested form component settings so that it does not show falsy checked value. 
Manually

FIO-10040: fixed an issue where lazyload option on form setting shows checked although it has the false value

---

src/utils/Evaluator.js
src/utils/index.js

https://formio.atlassian.net/browse/FIO-9783
In refactoring the evaluator, I accidentally removed a standalone `interpolate` utility that is derived from the Evaluator class. Since this could be used by customers and other downstream libraries, I've re-added it here.
n/a
n/a
n/a

FIO-9783: export a standalone interpolate fn

---

src/components/datamap/DataMap.js
test/unit/DataMap.unit.js
test/unit/fixtures/datamap/index.js
test/unit/fixtures/datamap/selectClearOnRefreshForDataMap.js

https://formio.atlassian.net/browse/FIO-10183
I did the same as Datagrid.
This solution allows us to clear "Select" when refreshOn = "Data Map" and clearOnRefresh = true. The problem is that when changing the Data map fields, the changed component itself (textField) is placed in the **changed** object, but in the form we specify refreshOn = dataMap and as a result different paths (dataMap and dataMap.textfield) do not allow us to clear the select value. In addition, in **Component.js** there is an **inContext** method that will not allow refresh to be executed if the contexts are different. And a  context for Select and dataMap.textfield will be different.
The Datagrid works on the same principle
n/a
n/a
I added test

FIO-10183: Value for select is not cleared on refresh options

---

src/utils/conditionOperators/DateGreaterThan.js
src/utils/conditionOperators/IsEmptyValue.js
src/utils/conditionOperators/IsEqualTo.js

https://formio.atlassian.net/browse/FIO-10245
The getComponent method for components within a DataGrid can return an array. It throws an error in the conditionals. 
None
Manual

Fixing issue with getComponent returning an array for DataGrid.

---

src/Wizard.js
src/components/_classes/nested/NestedComponent.js
src/components/_classes/nested/NestedComponent.unit.js
src/components/_classes/nested/fixtures/comp4.js
src/components/_classes/nested/fixtures/index.js
src/components/form/Form.js

https://formio.atlassian.net/browse/FIO-10425
This solves the wizard error navigation links by ensuring that all the promise resolutions occur after the attachment of the components within the nested form.
None
None
Manual

FIO-10425: Fixed issues where fields with errors in nested forms with in wizards are not properly highlighting when you click the error link.

---

src/WebformBuilder.js
test/unit/WebformBuilder.unit.js

https://formio.atlassian.net/browse/FIO-10525
*Previously, after adding the first Data Grid component, all nested components from the original Data Grid component were duplicated for all new added Data components. It was happened because when adding a new component, the `this.originalDefaultValue` property was overwritten only if the value was falsy, but it was not emptied after saving the component.*
*n/a*
*n/a*
*Automated test was added. All tests pass locally*

FIO-10525 fixed issue with duplicated nested components for new data components

---

src/formio.form.js

n/a
DefaultEvaluator is not included in the global Formio object, which the Developer Portal application (for whatever reason) uses instead of regular modules. This is a hotfix for that issue.
n/a
n/a
manually

Patch: include DefaultEvaluator in the Formio object
