circle.yml, package.json, test/qunit.html, test/qunit.js, test/test.js
Need to enable this project in CircleCI when this PR is merged.
=> Added mock tests for server requests

test/qunit.js
=> Added test for currentUser

src/formio.js, src/providers/storage/url.js
See related change in formio/ngFormio
=> Pass URL to upload

src/formio.js
Added the header parameter in Formio request method.
=> Addition of header parameter in request method.

src/formio.js
Uses: https://github.com/formio/formio/pull/221 and https://github.com/formio/formio-app/pull/419
=> FOR-251 - Adding getHeaders option to formio.request.

src/components/base/Base.js, src/components/checkbox/Checkbox.js, src/components/day/Day.js, src/components/signature/Signature.js, src/components/survey/Survey.js
Fixed the disabling action for those components: Checkbox, Day, Signature, Survey, and components which are flagged as multiple.
=> Fixed 'disable' for various components

src/components/file/File.js
For file components using 'url' storage send delete requests when uploaded files are removed from the list.
ngFormio does this.
=> Send request to delete when uploaded file is removed from list

src/components/columns/Column.js, src/components/columns/Columns.js
=> Support custom column width, offset, push and pull

bower.json, gulp/styles.js, package.json, src/components/resource/Resource.js, src/sass/formio.form.scss
Like ngFormio renderer.
Tried actual 'X' close button in top right but it was too big and ugly so used \<b\> tag.
=> Add Resource button and dialog

src/components/file/File.js
Borrowed code from ng-file-upload.
See related PRs in ngFormio and ngFormBuilder.
=> Add limitations for file component

src/components/select/Select.js
If applied, this PR will replace the original Select template and provide a translated version of the value inside it for each value.
=> Adding translations for Select Items

src/components/base/Base.js
If applied this PR will trigger an event every time a row is deleted from the Datagrid array.
=> Adding trigger on row remove

src/components/select/Select.js
- Added 'searchEnabled' option and defaulted it to false, user can enable it with component property
- Updated default value for 'removeItemButton' option to multi-select OR false, and if needed user can enable it with the component property
=> updated Select options

app/examples/stripeCheckout.md, src/contrib/index.js, src/contrib/stripeCheckout/StripeCheckout.js, src/contrib/stripeCheckout/StripeCheckout.spec.js, src/contrib/stripeCheckout/fixtures/comp1.js, src/contrib/stripeCheckout/fixtures/index.js
Hi,
This a new component to integrate a payment button using Stripe.
For context, Stripe will get the card and payment information and will return a token which will use on backend to made the payment.
So, the component is based on ButtonComponent and on click event, it will show the Stripe popup. After validation of information, Stripe send a request on their server and in response, the obtained token will be saved in the form data.
The component also manage the case where the button can submit the form after saving the token in the data. (action="submit" for this case)
=> Add StripeCheckout component

src/sass/formio.form.scss
Additional buttons did not stack vertically when rendered.
Angular 1 view
https://www.screencast.com/t/0BYS4BzUAGJW 
Current inconsistent view
https://www.screencast.com/t/7uiYf8mKSf5g
Corrected core view
https://www.screencast.com/t/M98U7XI8HDJ7
=> Button feature parody

src/components/button/Button.js, src/formio.form.js
FOR-980
Need to introduce a new "action" for buttons that will allow you to provide your own url, where it submits the data to that url. Add on submit button and optional URL to post the data to the url
FOR-981
Need to include in the submission which button was pressed
=> FOR-981 & FOR-980

src/components/button/Button.js
Inline with https://github.com/formio/ngFormio/pull/544/files for allowing the merger of the form's data object.
Outstanding: Refresh/render the updated form components once its data has updated.
=> Added lodash merge to replicate ng-formio feature

src/components/base/Base.js, src/components/button/Button.js
I also added the added the ability to prevent a component from being disabled.
Then in my custom code, i can do this:
```javascript
if (component.properties && component.properties.alwaysEnabled === 'true') {
component.alwaysEnabled = true;
}
```
=> Submit button was not disabled even if form was readonly

src/components/Components.js
Broken view:
https://www.screencast.com/t/f721qlmZi
Corrected view:
https://www.screencast.com/t/TtK8D4DbCr9
=> destroy method should clear form element

app/examples/yeti.md
=> updated language

app/examples/seamless.md
Docs for injecting styles into a Form.io PDF form.
=> Seamless.js integration

src/components/file/File.js
Check [this issue](https://github.com/formio/formio.js/issues/514) for more info.
=> Fix download file on [File] component when storage type has been set to [URL]

src/WebformBuilder.js
Configure dragula to check if a component can be dragged using the 'no-drag' class
=> Configure dragula to check if a component can be dragged using the 'no-drag' class

src/components/container/Container.js
`build` method now includes `createLabel` call.
=> FOR-1542: Update `build` method of `Container` component.

src/components/select/Select.js
Problem was not in comparison function, but in source of options.
=> FOR-1445: Fix addCurrentChoices method of SelectComponent.

src/Webform.js, src/components/nested/NestedComponent.js
Testing scenario:
1. Create a required hidden field
2. Make the field visible
3. Click Submit (Should see error)
4. Make field hidden
Error message remains when it should go away.
=> Clear errors when components are hidden.

src/components/form/Form.js
Add icons in options property of Nested forms.
=> Feature: add icons properties in nested form

app/examples/customendpoint.md
The submit button stays disabled and with spinner unless the submitDone event is emitted.
=> submitDone

src/components/base/Base.js, src/components/base/Base.spec.js, src/components/editgrid/EditGrid.js, src/sass/formio.form.scss
=> Revert "Bugfix/for 1595 multiple values component redesign"

src/components/select/Select.js
If Select is disabled, disable remove button in choices.js object.
=> FOR-1587: Update select component.

src/WebformBuilder.js
Don't assign 'disabled' property to defaultValueComponent schema, to avoid
implicit disabling, inherited from original component.
=> FOR-1636: Update WebformBuilder.

src/widgets/CalendarWidget.js
=> Revert "FOR-1567: Improved behavior."

src/components/base/Base.js
=> Fixing issue: Component was disabled while it shouldn't be

src/components/day/Day.js
Bug was in validateRequired method of Day component, because even in
HTML mode it attempted to read values from non-existing input elements.
=> FOR-1491: Fix bug with Day when form rendered as HTML

src/WizardBuilder.js, src/components/base/Base.js, src/components/content/Content.js, src/components/nested/NestedComponent.js
Prior the bugfix while editing content component in wizard builder,
it looses styled content when switching/adding/deleting pages.
Now all content stays the same.
=> FOR-1731: Fix bug with Content component in Wizard builder.

src/components/columns/Column.js
Addresses: https://github.com/formio/formio.js/issues/753
=> #753 add the 'hideOnChildrenHidden' component param

src/components/checkbox/Checkbox.js, src/components/nested/NestedComponent.js
This reverts parts of two changes that caused issues:
https://github.com/formio/formio.js/commit/f53f7c4fc4e9926aa5d56dd73b4b97d5aeab1922
https://github.com/formio/formio.js/commit/2fb62ee95170c7445f6f78a4bf64251ca956fcf2
=> Fix issues with inifinite refeshes with the datagid

src/components/base/editForm/Base.edit.display.js
=> Designer: added option to keep a component always enabled

src/sass/formio.form.scss
A couple of css fixes for RTL (to be used with bootstrap-rtl for bootstrap 3 / 4)
=> added-rtl-styles-for-formio-form

src/components/Validator.js
Added the field property (component error label) to Validator's custom error message.
=> added field for component custom validation

src/components/button/Button.js, test/forms/validationCalls.js
Now submit onchange event don't trigger second validation.
=> FOR-1336: Fix bug with double validation

src/components/container/Container.form.js, src/components/datagrid/DataGrid.form.js, src/components/datamap/DataMap.form.js, src/components/editgrid/EditGrid.form.js
Now for Container, DataGrid, DataMap and EditGrid components
defaultValue filed in editForm would be ignored.
=> Fix bug with editForm Data tab for container components

karma.conf.js, package.json
Mocha reporter provides better console output.
=> Proposal: switch reporter to karma-mocha-reporter

src/providers/storage/url.js
=> fix: check if ? exists in url

src/components/datagrid/DataGrid.js, src/components/datagrid/editForm/DataGrid.edit.display.js, src/sass/formio.form.scss
Added to DataGrid:
- New type of remove button (small);
- Remove Button placement configuration;
- Table layout configuration;
- New Row Groups Feature
=> Merge EditTable logic to DataGrid

src/components/html/HTML.js, src/components/html/editForm/HTML.edit.display.js
Add Translation to html component
=> Fix issue translation for html element HTML.js

src/components/html/HTML.js, src/components/html/editForm/HTML.edit.display.js
=> Revert "Fix issue translation for html element HTML.js"

package-lock.json, package.json, src/Component.js, src/WebformBuilder.js, src/components/columns/Columns.js, src/utils/formUtils.js
Still figuring out one event where I can't get all the information needed for the event.
=> Add merge utils

src/Webform.js, src/Webform.spec.js, src/components/form/Form.js, src/components/form/Form.spec.js, test/forms/index.js, test/forms/nested-event-bubbling.js, test/forms/nested-nosubmit.js
Now setting flag on root form reflects to child forms.
=> Fix bug with nosubmit flag for nested forms

src/utils/utils.js
CloneDeep component and form when evaluating content so that it can't be accidentally modified.
=> Isolate components and forms when running evaluate of custom code.

src/Webform.js
Fix bug when danger alert not disappear after all errors had resolved.
=> Fix bug with form danger alert

src/Webform.js
I would like to have some comments on my change on `Webform.onChange` handler as well as some question about button `set disable`.
=> Validation discussion

src/components/base/Base.js
Recently I faced an issue where I need to create a select component that must refresh based on 2 other inputs. So I modified the base Component to overcome this. Feel free to correct me if I am wrong.
=> Added option to use an array of refreshOn attributes for custom form components

gulpfile.js
Fix for: https://github.com/formio/formio.js/issues/1036
=> Fixed a bug with using gulp-watch, fixes issue #1036.

src/components/select/Select.js
Hotfix for https://github.com/formio/formio.js/issues/1058
=> fixed select component url parsing

src/components/base/Base.js, src/components/day/Day.js
=> Revert "Fixing the pristine flag to only set when a component has been direct…"

src/components/nested/NestedComponent.js, src/components/textarea/TextArea.js
1. Fixes the logic around when to display as a well
2. Lazy loads wysiwyg editors until they are visible.
=> Lazy load wysiwyg editors.

src/components/number/Number.js, src/components/select/Select.js
Similar change to the TextField Component - improve Accessibility by linking the label "for" attribute with the input's "id".
=> added id value for Number and Select component

src/WebformBuilder.js
Thanks for this awesome! extremely customisable library. In our use-case we want to present users with form-builder too and hence would want some additional texts to be included under translation.
=> include additional texts under translation

src/components/resource/editForm/Resource.edit.display.js
Just as they are already available on 'Select' components, filtering and sorting are useful on 'Resource' components, too.
As the effect already exists via inheritance from 'Select', we just need to add the configuration UI.
=> Add sort & filter on resource component.

src/components/file/File.js
In wizards, the submit button may be absent.
Thanks to @noman115pk for pointing this out.
=> Unbreak file uploads in wizards.

src/components/_classes/component/Component.js, src/templates/semantic/field/form.hbs
Refers to https://github.com/formio/formio.js/issues/1355
I'm expecting further changes especially in the component class.
=> semantic ui tooltip

src/components/checkbox/Checkbox.js, src/templates/semantic/checkbox/form.hbs
Haven't committed any tests...still working my way through
=> tooltip for checkbox

Changelog.md, src/Formio.js
fixed default headers being added to non-formio requests
=> FOR-2409: Fixed Sketchpad and Tagpad background images not loading

src/components/base/Base.js, test/forms/clearOnHide.js
=> Revert "Radio clear on hide fix"

src/components/textarea/TextArea.js
See #1429 for 3.x version.
Dependent on us tagging a new minor build (12.3) of existing `master`-branch code on our CKE fork.
=> 4.x - FOR-2379 - Add CKE image support

src/WebformBuilder.js, src/components/day/Day.js
Fixes the following:
Unable to Save Day Component when 'Day' field is required in builder mode
When Day component has the Day Field hidden, the Year field has a 0 prepopulated
=> Fix bugs with day component

src/components/select/Select.js
Related to FOR-2135 Mismatch on integer default value using select
=> handling number on default value for select component

src/components/_classes/component/Component.js, src/components/_classes/multivalue/Multivalue.js
=> Revert "Fix/default multiple value"

src/Webform.js
FOR-2455: Resolve issue with PDF generation on submissions tied to old revisions
Needs to be propagated to `formio-viewer` and `formio-files-core`.
=> Check for existence of this.formio before invoking

README.md
Fixes #1503 
For a list of rules refer: https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#rules
=> Conforming README.md to default markdownlint rules

src/components/editgrid/EditGrid.js, src/components/editgrid/editForm/EditGrid.edit.templates.js
Add an option to Edit Grid that allows the form to show up in a modal instead of below the grid.
EditGrid.js
EditGrid.edit.template.js
=> Edit Grid: Option to show up the form in Modal

src/components/html/HTML.js
=> Interpolate attribute value

src/components/select/Select.js, src/components/select/editForm/Select.edit.data.js
=> Revert "Fixed issues with search and infinite scroll in select component."

src/components/_classes/component/Component.js
Add Align Center control on Content Component for the Image editor.
Component.js
=> Add Align Center control

src/Form.js
Add Dompurify configuration to allow video/image tags, attr, and URLs.
Form.js
=> Allow Sanitize Config for Forms options

src/templates/semantic/datagrid/form.hbs, src/templates/semantic/iconClass.js
Minor semantic ui fixes for bulder
=> semantic fixes

src/components/editgrid/EditGrid.js, src/components/editgrid/editForm/EditGrid.edit.templates.js
Open a modal when 'Add another' is clicked to add or edit data.
EditGrid.js 
EditGrid.edit.templates.js
=> Edit Grid Modal

src/components/number/Number.js
fix bug with unsettable empty string
=> Number component fix

src/components/Validator.js, src/components/_classes/input/Input.js, src/utils/utils.js, src/widgets/CalendarWidget.js
=> Revert "Add validation for incomplete and invalide data for date\time component"

src/WebformBuilder.js, src/components/_classes/input/Input.js, src/components/_classes/widgetcomponent/WidgetComponent.form.js, src/components/_classes/widgetcomponent/WidgetComponent.js, src/components/_classes/widgetcomponent/editForm/WidgetComponent.edit.display.js, src/components/_classes/widgetcomponent/editForm/WidgetComponent.edit.validation.js, src/components/textfield/editForm/TextField.edit.display.js, src/widgets/CalendarWidget.js
1. https://trello.com/c/5QMC1gyd/412-textfield-calendar-when-calendar-widget-is-picked-the-widget-type-reverts-back-to-input-field
2. https://github.com/formio/formio.js/issues/1764
3. https://trello.com/c/SKDiB6PP/404-botw-flatpicker-infinite-loop-continues-to-create-within-dom-until-browser-crashes
=> Fix datetime issues 4x

src/components/select/editForm/Select.edit.data.js
For this issue: https://github.com/formio/formio.js/issues/1753
=> Fix auto updating of item template

src/components/_classes/multivalue/Multivalue.js
Should fix all 3 of them:
- https://trello.com/c/SnvUKJCI/395-email-email-data-is-not-saving
- https://trello.com/c/UNnagGu1/346-email-email-field-is-not-forcing-email-mask
- https://github.com/formio/formio.js/issues/1662
=> Add check of component type because of selection properties of input

src/components/_classes/widgetcomponent/WidgetComponent.js
=> Add check for this.widget before destroy()

src/sass/formio.form.scss
Add Default CSS to the content component to handle the preview.
=> Content Component Default CSS

src/components/file/File.js
=> Fix event casing error in File.js

app/examples/pdf.md
Closing element does not match
=> Closing element does not match

src/components/radio/Radio.js
=> Revert "[BUG] 1717 Fixed issue where Radio control would not initialize with a value if …"

src/utils/formUtils.js
This reverts commit 402ecf327140c2631a75112e35aa81b0ad76256d.
=> Revert "extend eachComponent and flattenComponent functions"

src/providers/storage/url.js
=> Fix aggressive option parsing in url.js

src/WebformBuilder.js
Fix the timing of emitting the removeComponent event.
Similar issue to https://github.com/formio/formio.js/pull/1838
=> Fix emit event on removeComponent

src/components/radio/Radio.js
=> Revert "Added ability to deselect radio value."

src/Formio.js, src/components/file/File.js, src/components/file/editForm/File.edit.file.js, src/components/textarea/TextArea.js, src/components/textarea/editForm/TextArea.edit.display.js, src/providers/storage/url.js
Feature:
1. Added configuration to change fileKey name in form-data for file upload URL.
2. Added configuration to change fileKey name in form-data for textarea component.
=> Feature/for-1740 : Upload FILE to URL- key 'file' in formData to be customizable

src/components/_classes/component/Component.js
=> Revert "Fix Text Area component is not visible in read only"

src/WebformBuilder.js
=> [#1920] Fix unchecked deep access in WebformBuilder

src/components/columns/Columns.js
=> Avoid JS errors when using autoAdjust columns.

src/components/_classes/component/Component.js
=> Fix issue with Field Logic events accumulating.

src/components/select/Select.js
=> Revert "Fixed placeholder on initial render in select component."

src/Wizard.js, src/utils/formUtils.js
Fixes issue https://github.com/formio/formio.js/issues/2130
=> Fixed FormioUtils.getStrings failing for Edit Grid component

src/components/file/File.js
Fixes issue https://github.com/formio/formio.js/issues/2132
=> Fixed File component webcam issues

src/components/checkbox/Checkbox.js
Fixes #2067  .  Supersedes #2116 .
=> Fix issue with hidden checkbox values not being updated correctly, take 2.

src/Form.js
This loads the submission first so that if it has a fvid we load the correct version of the form.
=> Submission fvid

src/WebformBuilder.js, src/sass/formio.form.builder.scss
Requires https://github.com/formio/bootstrap3/pull/6
https://i.imgur.com/cC1fPcv.mp4
=> Update component settings CSS to flow a little more nicely

src/components/datetime/DateTime.js, src/components/datetime/editForm/DateTime.edit.data.js
As requested in https://github.com/formio/formio.js/issues/2212, added customOptions for Date / Time component (flatpickr).
=> Added custom options for flatpickr widget

src/WebformBuilder.js, src/utils/formUtils.js
=> Revert "Update logic to get namespace"

src/utils/utils.js
in simpe condition.
I think it will be more user-friendly for creating simple conditions.
=> Fixed confusion with multiple components with the same label

src/utils/utils.js
=> vpat: 135 Form | Validation messages list | Panel focus

src/templates/bootstrap/file/form.ejs
=> #2275 Fileuploader component does not render the progress percentage

src/Form.js
=> Show load errors during form and submission load.

src/components/time/Time.js, src/validator/Validator.js
Added rawData field for keeping not formatted input to use it for validation and for displaying in inputs to prevent auto calculating
=> Time component raw data

src/components/_classes/component/Component.js
Actually, I forgot to add this changes to my previous fix for defaultValue
It made multiple components always keep at least one row
=> Fixed restoreValue to make multiple components delete the last value if the user want do so

src/components/_classes/component/Component.js
Set multiple and unique validate fields to false by default to make it be present in the originalComponent and prevent causing redrawing each time the component is compared with the originalComponent
=> Fix (Thomson Reuter/CHG) Text Field loses focus on each character input

src/PDF.js
Reverts formio/formio.js#2410
The reason is described @ https://github.com/formio/ngFormio/pull/667
=> Revert "Add local iframe src configuration"

src/components/file/File.js
Here are some screens proving that it works.
=> fixed url interpolation in file upload

src/PDF.js
=> Revert "Update iframe src building"

src/Webform.js
Made form send a full submission instead of only submission's data when the form's action specified.
=> Fixed payment error

src/components/form/Form.js
=> Revert "Fix github #1953: Override .defaultValue of subcomponents."

src/components/_classes/component/Component.js, src/components/textarea/TextArea.js
This also fix not shown textArea's placeholders 
I'm not sure how to test it
=> Fix ace editor error

src/PDFBuilder.js
This reverts commit 1b1e41021e255cfbfcf5613aeb0af51b4eef7879.
=> Revert "updated schema for custom fields"

src/utils/fixtures/components4.json, src/utils/formUtils.js, src/utils/utils.unit.js
Added some small tests for the findComponent method.
Also added some comments to the function.
=> Feat(Utils) : add tests for the findComponent method, comment code

src/Webform.js, src/Wizard.js
=> [formio.js-2630] : Add context object while emit render event

src/utils/utils.js
=> FJS-844 implement basic fix for checkbox type radio submit values in tableView

src/components/_classes/multivalue/Multivalue.js
Sending pull request as @travist suggested in #2597. :grinning:
=> 'Add Another' button isn't translated with leading space

src/components/select/Select.js
The problem was that it didn't check cases when data was empty object.
=> Fix(SelectComponent): improve itemTemplate check

src/components/select/Select.js
Fix for issue https://github.com/formio/formio.js/issues/2673
=> Fixed select component empty value when set to multiple

src/components/time/Time.js
Prevents submission data to be overriden by default data
=> FJS-859: removed raw data value check 

Changelog.md, src/components/_classes/component/Component.js, src/components/file/File.js, src/components/textarea/TextArea.js
@travist could you please merge this PR to 4.9.x and release new formio.js and angular-formio with this change?
=> Fixed WYSIWYG image upload not working without form URL provided

src/components/form/Form.js
Inherit the custom fileService from the parent form options
=> BUG 2686 - Nested form should inherit the fileService from the parent form

src/components/currency/Currency.js, src/components/currency/Currency.unit.js, src/components/number/Number.js, src/components/number/Number.unit.js
(bug found doing ticket FJS 903)
=> fixed number/currency formatting in tableView according localization

src/Webform.js
Don't merge until next uswds/vpat release
=> VPAT-362 Fixed axe issues for error section links 

src/components/editgrid/EditGrid.js
Please merge it into 4.9.x branch
=> Fixed setting value by logic in edit grid (ticket - FJS-905)

src/components/_classes/input/Input.js, src/components/textarea/TextArea.js, src/templates/bootstrap/input/form.ejs
FJS - 919
The reason why I added regular expression is that lodash ``words`` function is not working well for the cases with tags inside of the string.
=> Fix(TextArea, Input): word count is not working with editors

src/Webform.unit.js, src/components/_classes/component/Component.js, src/components/_classes/nested/NestedComponent.js, src/components/button/Button.js, test/formtest/index.js, test/formtest/validationOnBlur.json
Checking validity inside 'change' event to disable button have broken onBlur validation, so I added silentCheck flag to specify if we should show any error after checking validity or we just wonder to know if the component is valid
=> Fix validate on blur

src/components/select/Select.js, src/components/select/editForm/Select.edit.data.js
=> Revert "Added entire object option in value property for select with resource (ticket FJS-723)"

src/components/button/Button.js
=> Revert "VPAT-363 Fixed issue with custom validation on blur"

src/Webform.js, src/Wizard.js, src/components/_classes/component/Component.js, src/components/_classes/nested/NestedComponent.js, src/components/datagrid/DataGrid.js, src/components/datamap/DataMap.js, src/components/editgrid/EditGrid.js, src/components/form/Form.js, src/utils/utils.js, src/validator/Validator.js
Not yet ready for merge, I'm keep on writing tests.
=> Fix components path

src/providers/address/GoogleAddressProvider.js
Fixes an error in angluar-formio: https://github.com/formio/angular-formio/issues/552
=> Fixed issue where Promise collides with Angular ZoneAwarePromise

src/components/file/File.js
Fix for uploading photos to S3 from mobile devices.
=> S3 photo upload - update File.js

src/components/file/File.js
=> Revert "S3 photo upload - update File.js"

src/components/_classes/component/Component.js, src/components/_classes/component/Component.unit.js, src/components/_classes/component/fixtures/comp3.js, src/components/_classes/component/fixtures/index.js, src/components/_classes/componentModal/ComponentModal.js
=> Fix (Modal Edit): added isOpen to open modal window again after it was redrawn

src/components/select/Select.js
This fixes issue https://github.com/formio/formio.js/issues/2858
=> Fix for Select component Add Resource

src/Webform.unit.js, src/components/_classes/component/Component.js, src/components/_classes/nestedarray/NestedArrayComponent.js, src/components/datagrid/DataGrid.js, src/components/editgrid/EditGrid.js, test/forms/dataGridOnBlurValidation.js, test/formtest/validationOnBlur.json
=> Fix onblur validation

src/components/form/Form.js, src/components/form/Form.unit.js, src/components/form/fixtures/formModalEdit.js, src/components/form/fixtures/index.js
=> Fix (NestedForm is not shown when modalEdit)

src/components/select/Select.js
=> Fix (Select): made values such as "01", "02", etc. not be converted to 1, 2

src/Webform.js, src/Wizard.js, src/WizardBuilder.js
=> Fix (WizardBuilder): prevented emitting change in the schema getter

src/utils/utils.js
https://github.com/formio/formio.js/issues/2898
=> Fix (Utils): replaced unsupported in Safari expressions

src/components/_classes/component/Component.js
=> Fix (SelectBoxes): not able to manually override calculated value

src/WebformBuilder.js
=> Fix (WebformBuilder): components inside Columns are not able to save

src/widgets/CalendarWidget.js
=> Revert "fixed dateTime manual input (ticket - FJS-997)"

src/components/_classes/multivalue/Multivalue.js
FJS-855.
Also I think that the best solution would be for hidden component to be inherited from field component directly (without multivalue) and  override render method in hidden component, but I'm afraid that it could break some logic in code.
=> Fix(Multivalue): render hidden component without dataValue

src/Webform.js, src/components/_classes/component/Component.js, src/components/_classes/nested/NestedComponent.js
Does not require tests.
I've returned a bit of code as it was before my previous PR on validation, so this actually only contains one check for 'validateOnInit' flag passed.
Not supposed to influence any formiojs logic.
=> refactor validateOnInit flag logic

src/Wizard.js
=> Fix (Wizard): display panel navigation buttons according to page options

src/WebformBuilder.js
=> Revert "PDF 10 - search and removal of the component on all nesting levels"

src/Webform.unit.js, src/components/_classes/component/Component.js, test/formtest/calculateZeroValue.json, test/formtest/index.js
Replace 'var' by 'let' and a '||' condition by tha lodash method
Also added a test
=> Fix calculated value

src/components/_classes/nested/NestedComponent.unit.js, src/components/_classes/nested/fixtures/comp3.js, src/components/_classes/nested/fixtures/index.js, src/components/select/Select.js
=> Fixes an issue when a Select's value is not rendered inside EditGrid  

src/components/_classes/nested/NestedComponent.js
No trello card, noticed when was working on GCFund tasks.
=> Fixes an issue where component was not found in few cases with deep nesting

src/components/textarea/TextArea.js
=> Fixes an issue where values are not always set to the quill editor

src/components/signature/Signature.js
=> fixed signature display inside dataGrid in readOnly

src/components/signature/Signature.js
=> Fixed signature field dimensions inside data grid

src/components/file/editForm/File.edit.file.js
This adds config for upload only in file component - #3084
=> Adding config upload only option to file.edit

src/Webform.unit.js, src/components/_classes/component/Component.js, test/formtest/calculatedNotPersistentValue.json, test/formtest/index.js, test/renders/form-bootstrap-calculatedNotPersistentValue.html, test/renders/form-bootstrap-modalEditComponents.html, test/renders/form-bootstrap3-calculatedNotPersistentValue.html, test/renders/form-bootstrap3-modalEditComponents.html, test/renders/form-semantic-calculatedNotPersistentValue.html, test/renders/form-semantic-modalEditComponents.html
No Trello card, found during testing the PAP
=> Fixes an issue where value of non-persistent component is not calculated and shown in the View/Edit mode

src/WebformBuilder.js
=> Do not override the defaultValue field for hidden components

src/components/textarea/TextArea.js, src/sass/formio.form.scss
=> Fix (TextArea): Fixes an issue where images do not fit the editor's box in readOnly mode

src/components/textarea/TextArea.js
=> Fix (TextArea): Fixes an issue where images are not uploaded to the storage provider in the Quill editor and then an error occures

src/components/_classes/component/Component.js, src/components/_classes/component/editForm/Component.edit.display.js, src/components/panel/editForm/Panel.edit.display.js, src/templates/bootstrap/panel/form.ejs, test/renders/component-bootstrap-panel-multiple.html, test/renders/component-bootstrap-panel-required.html, test/renders/component-bootstrap-panel.html, test/renders/form-bootstrap-defaults.html, test/renders/form-bootstrap-formWithBlurValidationInsidePanel.html, test/renders/form-bootstrap-layout.html, test/renders/form-bootstrap-settingErrors.html, test/renders/form-bootstrap-uniqueApiKeysLayout.html
=> Revert "FJS-1050: added hide label option for panel component"

src/components/datagrid/DataGrid.js
No Trello card, found an issue by myself
=> (!) Fixed an issue where components inside DataGrid are not removable and impossible to save their settings

src/PDFBuilder.js, src/WebformBuilder.js, src/sass/formio.form.builder.scss, src/templates/bootstrap/builderSidebar/form.ejs, src/templates/bootstrap/builderSidebarGroup/form.ejs
Related to https://github.com/formio/bootstrap3/pull/29
=> FIN-007: Add an Intuitive/dynamic search box in the Custom Fields List

src/components/file/File.js
No Trello card, found by myself.
=> (!) Regression: fixes an issue where File is not working inside Wizard

src/components/textarea/TextArea.js
It is a regression issue, no Trello card
=> Fixed an issue where Required Error is not triggered for Quill

src/components/day/Day.js, src/components/day/Day.unit.js, src/components/day/fixtures/comp4.js, src/components/day/fixtures/index.js
=> Disable Day component if parent component is disabled

src/Webform.js, src/components/editgrid/EditGrid.js
No Trello card, found by myself.
=> Fixed an issue where "modified" is false when saving a row of the EditGrid

src/components/file/File.js
=> Fixes Formtype when File component is disabled with advanced logic

src/WebformBuilder.js
Caused issues when removed one of two fields with keys duplication.
=> Changed property by which the origin comp is found to remove

src/WebformBuilder.js, src/components/_classes/component/Component.js, src/components/_classes/input/Input.js, src/components/_classes/nested/NestedComponent.js
No Trello card. Found by myself
=> Fixed an issue where WebformBuilder's components/widgets are not detached

src/WebformBuilder.js
related to https://github.com/formio/bootstrap3/pull/31
=> WebformBuilder: add check for sidebar id attr for bootstrap3 compatibility

src/components/_classes/nested/NestedComponent.js
Not for a ticket, just fixing a bug I did not notice previously.
=> Nested: fix untouched panel collapse and then open triggered validation

src/utils/utils.js
=> Fixed an issue where conditions do not work for components inside EditGrid

src/utils/utils.js
No Trello card, found by Dmitry
=> Fixes an issue where values of conditionally visible components inside EditGrid are not saved on the 6.x server

src/components/_classes/component/Component.js, src/components/textarea/TextArea.js
In relation to https://github.com/formio/formio.js/issues/3392
Not sure if this causes problems but opened this to jump start the discussion.
=> Fix Ace in webpack environments

_layouts/default.md, app/examples/embed.md, src/formio.embed.js
=> FJS-1301 & FJS-1302 Regressions on examples of github (Problem with Formio global object)

src/components/select/Select.js
Fixed an issue where it shows 'no items' when Network is slow and loading is not finished
Fixed an issue where lazyLoading Select with refreshOn is fetched twice: on the refresh event and on the showDropdown event
Only add triggerUpdate on the hideDropdown event when Select has a searchField
=> FJS-1306: Fixes small issues with Select and improves its performance

src/WebformBuilder.js
* Added debounce for search
* When searching, the components are grouped in a grouped named `searchFields`, so this group was not being searched
=> WebFormBuilder Search Enhancements

src/components/_classes/component/Component.js, src/components/textarea/editForm/TextArea.edit.display.js, src/providers/storage/uploadAdapter.js, src/sass/formio.form.scss
=> [Feat]: Adds an ability to upload images from CKEditor to storage providers

src/sass/formio.form.scss
Fix textarea endlines in read-only mode
=> Issue 2471 - Update formio.form.scss (Fix textarea endlines in read-only mode)

src/templates/bootstrap/wizardHeader/form.ejs
=> FMG-109 | Change OnHover cursor style to the Hand pointer for the Wizard navigation buttons

src/components/_classes/component/Component.js
Found by myself while testing PAP app
=> Fixed an issue where forms which have some logic get stuck in infinite loop

src/components/_classes/component/editForm/utils.js
related to [Fix Ace in webpack environments #3417](https://github.com/formio/formio.js/pull/3417)
=> FOR-2882: fix the mode path in ace

src/components/editgrid/EditGrid.js
Related to: [PR](https://github.com/formio/premium/pull/74)
=> Moving the condition into function for overwriting

src/components/editgrid/EditGrid.js
Hi @travist 
This should solve #3357 . It would be cool if you could review it. The way I implemented is totally OK for our use case (talked to @krixerx ). But maybe you would rather have it handled differently?
=> FJS-3357 enable selection of closed EditGrid rows

src/formio.form.js
=> Allow multiple plugins to provide global options

src/Wizard.js
Related to: [PR](https://github.com/formio/premium/pull/75)
=> Fix: add a method to override

package.json, src/Webform.unit.js, src/components/_classes/component/Component.js, src/components/datetime/DateTime.unit.js, src/components/datetime/editForm/DateTime.edit.display.js, src/components/datetime/fixtures/comp2.js, src/widgets/CalendarWidget.js
=> FJS-1239: Adds ability to create shortcut buttons for flatpickr

src/components/_classes/component/Component.js
=> FIO-1160: Fixes errors when there is an undefined value in the inputs array

src/WizardBuilder.js
=> FMG-55: Create a from | Copying a root panel on the page of a Wizard, it pasts below the copied panel

src/components/_classes/component/Component.js, src/components/_classes/component/editForm/Component.edit.logic.js
=> FEATURE REQUEST - Variables exposed in Logic Tab of a component configuration #3653

gulpfile.js, src/formio.embed.js, src/sass/formio.embed.scss, src/sass/formio.form.scss
Here is an active demo. https://codepen.io/travist/pen/VwKRoEP
There is an issue with text-masks, but here is an active pull request that resolves it. 
https://github.com/text-mask/text-mask/pull/982/files
We will work on getting that either in a fork or pulled through to create a build with that fix.
=> Refactoring the inline embed code to enhance its usage and allow shadow dom.

src/components/datagrid/DataGrid.js, src/templates/bootstrap/datagrid/form.ejs, test/renders/component-bootstrap-datagrid-multiple.html, test/renders/component-bootstrap-datagrid-required.html, test/renders/component-bootstrap-datagrid.html, test/renders/component-bootstrap-datamap-multiple.html, test/renders/component-bootstrap-datamap-required.html, test/renders/component-bootstrap-datamap.html, test/renders/form-bootstrap-calculateValueWithManualOverride.html, test/renders/form-bootstrap-data.html, test/renders/form-bootstrap-defaults.html, test/renders/form-bootstrap-formWithCustomFormatDate.html
Also PR for bootstrap3 templates https://github.com/formio/bootstrap3/pull/37
=> FJS-1328: Fixes an issue where it is impossible to reorder rows of a child DataGrid

src/components/checkbox/Checkbox.js, src/components/radio/Radio.js
=> FIO-3530: update input attribute when value changes

src/components/editgrid/EditGrid.js
I have created new branch and created pull request to 4.12.x. please review the changes. This change is a fix to the translation issue when when saving the edit grid
=> Fixed the translation issues while saving edit grid

src/components/editgrid/EditGrid.js
Related to: https://github.com/formio/premium/pull/79
=> FIO-1258: remove the function used for overwriting

src/components/select/Select.js
Here was introduces a fix for that issue https://github.com/jshjohnson/Choices/commit/68313da4122ec7f76274b22926e762914c96723d#diff-4ead2dbcfd0aa20fd2fb5fdcd7ba7735df92a2db9a0d5113c6f77e647796efdcR141-R146
but there is no release including that yet
=> FIO-1383: Fixes an issue where IE11 throws an error when trying to destroy choicesjs

src/sass/formio.form.scss
=> FIO-1490: Fixes an issue where font size does not affect CKEditor content in read-only mode

src/components/selectboxes/SelectBoxes.js
This is also fixes an issue where Selectboxes have maxCount and logic that should set them to disabled state, but it does not, because Selectboxes component during validation makes inputs enabled again.
=> FIO-1501: Fixes an issue where some inputs remain disabled after the maxCount was exceeded

src/components/_classes/component/Component.js, src/components/select/Select.js
=> FIO-1524: Fixes an issue where EditGrid and Select are not hidden using event-triggered logic

src/Wizard.js
=> Revert "FJS-1461: Fixes an issue where it is possible to Cancel Wizard form in readOnly mode"

src/Wizard.js
Related to: [PR](https://github.com/formio/premium/pull/90)
=> add method to overwrite

src/WebformBuilder.js
=> Fixed an issue where default value field is not updated for custom components in builder

src/components/editgrid/EditGrid.js, src/components/editgrid/EditGrid.unit.js, src/components/editgrid/fixtures/comp-with-conditions-and-openWhenEmpty.js, src/components/editgrid/fixtures/index.js
Also fixes an issue where after the first row is saved and then the EditGrid is hidden (Clear on Hide is checked) and shown again, it has no rows.
=> FIO-2468: Fixes an issue where data in the first row is not saved when the EditGrid is shown conditionally and Open when Empty is checked

src/Element.js, src/Wizard.js
=> FJS-1461: Fixes an issue where it is possible to Cancel Wizard form in readOnly mode

gulpfile.js, package.json, src/Element.js, src/components/_classes/component/Component.js, src/components/currency/Currency.js, src/components/number/Number.js, src/components/tags/Tags.js, src/components/textfield/TextField.js, src/utils/ChoicesWrapper.js
=> FIO-2787: Fixing the choices.js and text-mask dependency so that it can be installed without Github.

index.md
=> fix Formio being undefined on example template

src/Embed.js
=> Embed: get rid of formio logo at the bottom

src/sass/formio.form.scss
No tests since this is a browser-specific issue
=> FIO-346 | FJS-1051: Fixes an issue where multiple select shows "..." in Firefox

src/components/editgrid/EditGrid.js, src/components/editgrid/EditGrid.unit.js, src/components/editgrid/fixtures/comp-with-basic-components.js, src/components/panel/Panel.js, src/components/tabs/Tabs.js
Waiting for response from the customer to confirm how it should behave in few cases to finish this and fix tests
=> FIO-2848, FIO-2831: Fixes some issues with setting error classes inside EditGrid

src/templates/bootstrap/input/form.ejs, test/renders/component-bootstrap-datetime-multiple.html, test/renders/component-bootstrap-datetime-readOnly-value0.html, test/renders/component-bootstrap-datetime-readOnly-value1.html, test/renders/component-bootstrap-datetime-readOnly-value2.html, test/renders/component-bootstrap-datetime-readOnly.html, test/renders/component-bootstrap-datetime-required.html, test/renders/component-bootstrap-datetime.html, test/renders/form-bootstrap-advanced.html, test/renders/form-bootstrap-basic.html, test/renders/form-bootstrap-defaults.html, test/renders/form-bootstrap-formWithCustomFormatDate.html, test/renders/form-bootstrap-formWithDateTimeComponents.html, test/renders/form-bootstrap-readOnly-advanced.html, test/renders/form-bootstrap-readOnly-basic.html, test/renders/form-bootstrap-readOnly-defaults.html, test/renders/form-bootstrap-readOnly-formWithCustomFormatDate.html, test/renders/form-bootstrap-readOnly-formWithDateTimeComponents.html, test/renders/form-bootstrap-readOnly-settingErrors.html, test/renders/form-bootstrap-settingErrors.html
=> FIO-1288: Fixesan issue where Prefix/Suffix is rendered inaccurately when words/chars counter is shown

src/sass/formio.form.scss
=> FIO-1488: Fixes an issue where unordered list created in Quill is rendered as an ordered one in read-only mode

src/components/checkbox/Checkbox.js, src/components/radio/Radio.js, src/templates/bootstrap/checkbox/form.ejs, src/templates/bootstrap/radio/form.ejs
=> Revert "custom styling support for checkbox and select box"

src/components/_classes/component/Component.js, src/components/columns/Columns.js, src/components/radio/Radio.js, src/components/radio/Radio.unit.js, src/components/radio/fixtures/comp6.js, src/components/radio/fixtures/index.js, src/components/select/Select.js, src/components/select/Select.unit.js, src/components/select/fixtures/comp14.js, src/components/select/fixtures/index.js
@travist FYU I changed the getModifiedSchema method so that it works also for objects inside arrays. Therefore, now the columns field in the Columns component is also removed from the minified schema, if the initial value of the field does not change
=> FIO-2554: add properties to the default schemas

src/widgets/CalendarWidget.js
I am not sure how to test it because it is a bug inside Flatpickr library and it is not constantly reproducible
.
=> FIO-3187: Fixes an issue where  after you click on the time input it closes and time is visible, but not actually persist within submission

src/components/_classes/component/Component.js, src/components/_classes/input/Input.js, src/widgets/CalendarWidget.js, src/widgets/InputWidget.js
I am not sure how to test it since the issue does not replicate constantly
=> FIO-2880: Fixes an issue where time is converted multiple times and the result is wrong

src/components/datagrid/DataGrid.js, src/templates/bootstrap/datagrid/form.ejs
Also need to take
- https://github.com/formio/bootstrap3/pull/53
- https://github.com/formio/semantic/pull/35
=> FIO-3323: Fixing the datagrid spacing.

src/sass/formio.form.scss
Just styling fix, no tests needed
=> FIO-3303: Fixes an issue where CKEditor tables do not render properly in the View mode

src/components/select/Select.js, src/components/select/Select.unit.js
=> FIO-1310: fixed an issue where select search not always shows all available options

app/examples/language.md
No tests needed since translations work properly, this message was just missed in the example config
=> FIO-258: Fixes an issue where "Submission Complete" message is not translated in the Examples page

src/components/file/File.js, src/components/file/File.unit.js
=> FIO-3305: fixed an issue where pattern validation does not allow to add a file that complies with the pattern

src/components/button/Button.js
Cherry-pick of the https://github.com/formio/formio.js/pull/4228
=> fix(Button): disableOnInvalid does not work when have multiple nested forms and make one of them valid forms and make one of them valid

src/components/_classes/component/Component.js
Fix for issue https://github.com/formio/formio.js/issues/4225
=> Fixed HTML being rendered when inputFormat is plain

src/WebformBuilder.js
Fix for issue https://github.com/formio/formio.js/issues/4048
=> Fixed builder missing projectId promise rejection

src/components/_classes/nested/NestedComponent.js
This is a fix for issue https://github.com/formio/formio.js/issues/4213.
=> Fixes inputs non-unique id

src/components/_classes/component/Component.js
=> Revert "Fixed HTML being rendered when inputFormat is plain"

src/components/_classes/nested/NestedComponent.js
=> Revert "Fixes inputs non-unique id"

src/components/_classes/component/Component.js
This change does not fix any logical or behavioral issue, it just reverts the behavior back to the one which we had in formiojs 3.x to fix some customer's cases which were broken because the logic has changed.
=> (!!!Customer specific fix) Fix: fields set manually inside calculate value are submitted to the server

src/components/_classes/component/editForm/Component.edit.data.js, src/components/datagrid/DataGrid.unit.js, src/components/datagrid/fixtures/comp-with-logic.js, src/components/datagrid/fixtures/index.js, src/components/form/editForm/Form.edit.data.js
Haven't understood why the test fails. It was failing before my changes too. I've made an exact setup as described in it and in manual testing it works fine.
=> make clearOnHide false and hide it when hidden is checked

src/components/_classes/component/Component.js, src/components/_classes/nested/NestedComponent.js, test/forms/helpers/testBasicComponentSettings/tests.js
…rror message doesn't disappear in modal window
=> FJS | Address: Address that has Modal Edit checked is not shown in error list. Error message doesn't disappear in modal window

src/components/_classes/component/Component.js, src/components/_classes/component/Component.unit.js
Hi @travist / @heather-formio 
This is ECB.
I am creating this fix for issue [4322](https://github.com/formio/formio.js/issues/4322) that we discussed in a call last week.
cc @elibus
=> fix - FIO-3875 | FJS - Calculated fields that are invalid are not marked as such

src/Webform.js
No tests need. Looks like an incorrectly called function in some rare cases
=> FJS | Validation not triggered when change "required" option in Logic tab

src/components/_classes/nested/NestedComponent.js
=> Revert "FIO-3890: instance row issue fix"

src/Webform.js
Need this in SignRequest component
=> emit an event when form is deleted

app/examples/customendpoint.md, app/examples/externalload.md, app/examples/fieldLogic.md, app/examples/hosted.md, app/examples/htmlview.md, app/examples/index.md, app/examples/stripe.md, app/examples/stripeCheckout.md, app/examples/submissions.md, app/examples/thanyou.md
Updated all occurances of the formio tag to div tag
=> Fixed div tag typo on the example docs

src/components/checkbox/Checkbox.js
=> 13x fio 4412 fixed checkbox value not return after submission when checkbox is shown conditionally

src/components/tabs/Tabs.js
Seems like my linter has fixed some style issues in this file. The actual fix is on L195-198
=> Fixed an issue where submission of the form with Tabs component fails

src/components/editgrid/EditGrid.js, src/components/radio/Radio.js
EditGrid memory leak.
Fix Radio.js handling of undefined.
=> EditGrid memory leak.  Fix Radio.js handling of undefined.

src/displays/webform/Webform.js
Store `this` into a local variable and clean it up, so not bound to callback context.
Before:
After:
=> `this` getting bound when initializing i18next

src/Formio.js, src/components/button/Button.js, types/formio.d.ts
Depends:
server FIO-5042
angular FIO-5042
app FIO-5042
=> FIO-5042: Logout feature for OIDC

src/Webform.unit.js, src/components/_classes/component/Component.js, test/formtest/calculateValueWithSubmissionMetadata.json, test/formtest/index.js
To work with _Calculate value on server_ option requires **formio** package with [this changes](https://github.com/formio/formio/pull/1465/commits/0b75097bd8a2638c5fa81da26adbb349fee0b1fa)
=> FIO-6100: Provide submission object to value calculation (eg. To relate to submission metadata in calculation)

src/components/button/Button.js
related PR: https://github.com/formio/formio-server/pull/1145
=> FIO-6001: fixed an issue where oauth action does not work for buttons inside layout/data components

src/Wizard.js
https://formio.atlassian.net/browse/FIO-5811
=> FIO-5811: added scroll up if got error

src/Formio.js, src/components/button/Button.js, src/components/select/Select.js
=> fixed eslint errors and warnings

src/CDN.js
https://formio.atlassian.net/browse/FIO-5992
*Added fprmio/core library for  implementing CDN updates for formio/premium*
https://github.com/formio/cdn.form.io/pull/7
https://github.com/formio/premium/pull/215
*manually*
=> FIO-5992 added formio/core library

src/components/select/Select.js, src/components/tags/Tags.js
related to https://github.com/formio/Choices/pull/1
=> FIO-6029: update choices.js

src/addons/PasswordStrength/PasswordStrengthAddon.form.js, src/components/_classes/component/Component.js
https://formio.atlassian.net/browse/FIO-6191
=> FIO-6191: Fixed an issue where addons are not created

src/components/radio/Radio.js
=> Fixing the updateValue routine for the radio component.

src/components/_classes/component/editForm/Component.edit.data.js
https://formio.atlassian.net/browse/FIO-6193
Moved plan info into tooltips for encrypted fields
Tested on local environment
=> FIO-6193 Moved plan info into tooltips for encrypted fields

src/components/datamap/DataMap.js, src/components/datamap/DataMap.unit.js, src/components/datamap/fixtures/formWithConditionalPanel.js, src/components/datamap/fixtures/index.js
https://formio.atlassian.net/browse/FIO-358
https://formio.atlassian.net/browse/FIO-3957
=> FIO-3957: Fixes an issue where Data Map inside conditionally shown Panel does not show its values in the view mode

src/widgets/CalendarWidget.js
https://formio.atlassian.net/browse/FIO-6164
Basically reapplying https://github.com/formio/formio.js/pull/4873, some of the changes were lost since it was merged
All tests pass locally
=> FIO-6164 Fixed an issue with date/time component localization

src/components/_classes/component/editForm/Component.edit.data.js
https://formio.atlassian.net/browse/FIO-6193
Changed tooltip copy for encrypted fields.
Tested locally.
=> FIO-6193 Changed tooltip copy for encrypted fields

src/CDN.js
https://formio.atlassian.net/browse/FIO-6323
*updated version of the quill library*
*https://github.com/formio/cdn.form.io/pull/10*
*manually*
=> FIO-6323 updated version of the quill library

test/renders/component-bootstrap-signature-required.html, test/renders/component-bootstrap5-signature-required.html, test/renders/form-bootstrap-advanced.html, test/renders/form-bootstrap-readOnly-advanced.html, test/renders/form-bootstrap5-advanced.html, test/renders/form-bootstrap5-readOnly-advanced.html
=> fixed render tests

src/WebformBuilder.js, src/components/_classes/component/Component.js, src/components/_classes/input/Input.js
https://formio.atlassian.net/jira/software/c/projects/FIO/issues/FIO-6469
Fixed issue with double quotes (") turned to single quotes (') in placeholder text.
Tested locally
=> FIO-6469-Double quotes (") turned to single quotes (') in placeholder text

src/PDFBuilder.js
Reverts formio/formio.js#5097 
Changing CSP headers to attempt to resolve the drag/drop issue
=> Revert "Fio 6512 cannot drag and drop components on to pdf first forms using mac"

src/components/_classes/list/ListComponent.js, src/components/select/Select.js
=> FIO-5967: Fixing issues with selectData saving correctly for pdf download and save as reference.

src/components/file/File.js
https://formio.atlassian.net/jira/software/c/projects/FIO/issues/FIO-6533
Added condition for hashing and message during hashing.
Tested locally.
=> FIO-6533: fixed an issue where file upload hash causing delays in file uploads

src/components/select/Select.unit.js, src/components/select/fixtures/comp17.js, src/components/select/fixtures/index.js
https://formio.atlassian.net/browse/FIO-6407
*Updated tests for the Select Component. Added a case for checking the value of metadata.selectData *
*no*
*added automated tests *
=> FIO-6407 Updated tests for Select Component

src/components/select/Select.js, src/components/select/Select.unit.js
https://formio.atlassian.net/browse/FIO-5967
Changed logic to set correct value to the html 5 select options instead of plain object
Added unit test
=> FIO-5967: fixed issue with setting [object Object] to html options

src/components/form/Form.js
https://formio.atlassian.net/browse/FIO-4876
*Fixed submission display for pdf download page. After the changes the submission displays in the original form revision of the nested form on pdf download page.*
*no*
*manually. Tests passed locally*
=> FIO-4876 fixed the display of current submission for pdf download

src/components/select/Select.js
=> FIO-5967: fixed getting option value for html5 options

src/Webform.js, src/WizardBuilder.unit.js
https://formio.atlassian.net/browse/FIO-6766
Reverted one change from this PR https://github.com/formio/formio.js/pull/5101 as it cause issue with default value and tests failures.
A lot of tests are failing on master branch but with this fix some of them started passing.
=> FIO-6766: Removed from submission flag check

src/CDN.js, src/Webform.unit.js, src/WizardBuilder.unit.js, src/components/datagrid/DataGrid.unit.js
https://formio.atlassian.net/browse/FIO-2088
Updated flatpickr-formio to a newer version that includes fixes that need to be tested.
Manually
=> FIO-2088: updated formio-flatpickr version and fixed eslint warnings

src/PDFBuilder.js
https://formio.atlassian.net/browse/FIO-6711
*Replaced global with globalThis to determine the user's platform*
*no*
*Manually using the chrome browser on Windows and Mac*
=> FIO-6711: FormIo-angular can edit PDF form in Chrome

.vscode/launch.json, src/Webform.js, src/Webform.unit.js, test/forms/fieldLogic.js, test/forms/helpers/testBasicComponentSettings/tests.js
https://formio.atlassian.net/browse/FIO-6608
The renderer test suite has been failing on CircleCI and locally. We have to be disciplined about not trying to merge code that does not pass the test suite.
n/a
n/a
=> FIO 6608: hotfix for renderer tests

src/components/_classes/component/Component.js, src/components/select/Select.js, src/components/select/Select.unit.js, src/components/select/fixtures/comp18.js, src/components/select/fixtures/index.js
https://formio.atlassian.net/jira/software/c/projects/FIO/issues/FIO-6760
Fixed issue, when use resource with multiple values, data isn't rendered correctly
I tested locally and added automated tests to cover this case
=> FIO-6760:fixed an issue where in select component when use resource multiple values data isn't rendered correctly

src/WebformBuilder.js, src/sass/formio.form.builder.scss, src/templates/bootstrap/builderSidebarGroup/form.ejs
https://formio.atlassian.net/browse/FIO-5263
Fixed indication of component which is currently selected for 'Move'
Fixed an issue when components weren't having unique API names when added by keyboard
Fixed an issue when components where disappearing from the form when moved in some cases
Added a way to enable keyboard actions through form settings
Tested locally due to the changes being UI only
=> FIO-5263 Fixed issues with keyboard controls for formbuilder

src/components/radio/Radio.js, src/components/radio/Radio.unit.js, src/components/radio/fixtures/comp9.js, src/components/selectboxes/SelectBoxes.js, src/components/selectboxes/SelectBoxes.unit.js, src/components/selectboxes/fixtures/comp5.js, src/validator/Validator.js
https://formio.atlassian.net/browse/FIO-6762
*Added Validation for Value Property for Radio and SelectBoxes components if dataSrc type is url. If Value Property is Undefined, Object or Boolean (for SelectBoxes) the User will see a warning message*
*no*
*Automated tests have been added. All tests passed locally*
=> FIO-6762 added ValueProperty validation

.vscode/launch.json, _config.dev.yml, src/Element.js, src/Form.js, src/PDF.js, src/PDFBuilder.js, src/Webform.js, src/Webform.unit.js, src/WebformBuilder.js, src/WebformBuilder.unit.js, src/Wizard.js, src/components/_classes/component/Component.js, src/components/_classes/input/Input.js, src/components/_classes/nested/NestedComponent.js, src/components/columns/Columns.js, src/components/editgrid/EditGrid.js, src/components/file/File.js, src/components/form/Form.js, src/components/select/Select.js, src/components/table/Table.js, src/components/tags/Tags.js, src/components/tree/Tree.js, src/utils/utils.js, src/widgets/CalendarWidget.js
https://formio.atlassian.net/browse/FIO-5954
A customer was having memory leak issues with their version of the renderer, which we call "orphaned" because it had began as a rewrite of the renderer but was never finished, and unfortunately this customer was transitioned to this version and uses it to this day. Travis made a number of changes to fix these memory leaks, so this PR attempts to backport those changes into the master branch. 
n/a
Because the memory leak issues are murky at best to me here (they're not described in the ticket and seem to have been enumerated to Travis over a series of customer support calls), it's very difficult if not impossible to write specific test cases. I'm counting on the fact that the automated test suite successfully passes to indicate that these …
=> FIO 5954: Backport Travis' memory leak fixes from `m` release to master

src/PDFBuilder.js
https://formio.atlassian.net/browse/FIO-6965
*When uploading a file via formmanager, a pdf-proxy is used. Added a check and fixed an error when uploading a file via formmanager*
*no*
=> FIO-6965 fixed file upload via pdf proxy

package.json, src/components/textarea/TextArea.unit.js
n/a
tests were failing in 4.15.x and 4.16.x release branches due to a problematic cherry pick, here's the fix
n/a
n/a
=> Fix build 4.15.x

src/CDN.js
https://formio.atlassian.net/browse/FIO-5857
Updating flatpickr to include latest fixes from https://github.com/formio/flatpickr/pull/18
CDN needs to be updated to include the flatpickr-formio@4.6.13-formio.3
=> FIO-5857 Update flatpickr to a version with the latest changes

src/validator/Validator.js
https://formio.atlassian.net/browse/FIO-6840
A performance bottleneck in the user registration process was due to inefficient case-insensitive regex queries being used throughout the codebase. This PR updates the renderer's unique validation to allow for usage of the new efficient indexing scheme for email components and textfield components with a ASCII-centric regex validation.
https://github.com/formio/formio.js/pull/5244
https://github.com/formio/formio/pull/1590
https://github.com/formio/formio-app/pull/1470
https://github.com/formio/formio-server/pull/1278
This is a high priority and something of a hotfix, so I was unable to write automated tests for this.
=> change unique validation for email comps and certain textfield comps

src/Wizard.js, src/components/_classes/component/Component.js, src/components/_classes/nested/NestedComponent.js
=> FIO-7002: Fixing hide and show options to change visibility of components.

src/components/select/Select.js
https://formio.atlassian.net/browse/FIO-5730
*Fixed template for Select Component on PDF when the Data Source Type is API*
*no*
=> FIO-5730 fixed template for Select on PDF download

src/components/editgrid/EditGrid.js
https://formio.atlassian.net/browse/FIO-5303
*Removed the Edit and Delete Buttons for the EditGrid on PDF download page*
*no*
=> FIO-5303 fixed Edit and Delete buttons

src/components/form/Form.js
Reverts formio/formio.js#5134
Caused regression https://formio.atlassian.net/browse/FIO-7102
=> Revert "FIO-4876 fixed the display of current submission for pdf download"

src/WebformBuilder.js, src/components/columns/Columns.js, src/components/container/Container.js, src/components/datagrid/DataGrid.js, src/components/datamap/DataMap.js, src/components/editgrid/EditGrid.js, src/components/fieldset/Fieldset.js, src/components/hidden/Hidden.js, src/components/html/HTML.js, src/components/table/Table.js, src/components/tabs/Tabs.js, src/components/tree/Tree.js, src/components/well/Well.js
https://formio.atlassian.net/browse/FIO-5748
=> FIO-5748 Collapsible preview for Form Builder

src/Webform.js
fix issue: when submission.data doesn't exist, the submission.metadata is removed
=> fix issue: when submission.data doesn't exist, the submission.metadata is removed

src/Webform.js, src/Webform.unit.js
I couldn't actually get the test to run.  Too many failing tests, but this works in a jsfiddle for at least the use cases I'm aware of.
Solves: https://github.com/formio/formio.js/issues/3687
~~Fixes: https://github.com/formio/formio.js/issues/3684~~. It addresses this issue, but this issue is still broken if you're using the submission in the regular fashion of setting it in the `then`
=> Add submission as form creation option

src/utils/utils.js
prevent clashing of `$` as seen in #4851
=> use jQuery instead of $

src/components/file/File.js, src/components/file/File.unit.js
=> Revert "Multi upload: abort the correct file when clicking the cancel upload button"

src/sass/formio.form.scss
https://formio.atlassian.net/jira/software/c/projects/FIO/issues/FIO-6785
Added style to "ol" and "ul" tag
I studied ckEditor [documentation](https://ckeditor.com/docs/ckeditor5/latest/features/indent.html#demo) and chose this solution so they use this solution in their demo
Tested Locally 
video https://formio.atlassian.net/browse/FIO-6785?focusedCommentId=46113
=> added style to ol and ul tag

src/components/_classes/component/Component.js, src/components/checkbox/Checkbox.js, src/components/datetime/DateTime.js, src/components/day/Day.js, src/components/file/File.js, src/components/number/Number.js, src/components/select/Select.js, src/components/selectboxes/SelectBoxes.js, src/components/signature/Signature.js, src/components/survey/Survey.js, src/components/tags/Tags.js, src/components/textfield/TextField.js, src/components/time/Time.js
https://formio.atlassian.net/browse/FIO-6630
It's a dependency PR for https://github.com/formio/formio/pull/1596
=> FIO-6630: Expanded Actions Logic UI

src/PDFBuilder.js
https://formio.atlassian.net/browse/FIO-7096
*Fixed adding components with drag and drop in the Microsoft Edge browser with Mac for pdf forms*
*no.*
*all tests passed locally*
=> FIO-7096 fixed adding components for PDF in the Microsoft Edge browser with Mac

src/components/selectboxes/SelectBoxes.js, src/components/selectboxes/fixtures/comp4.js
https://formio.atlassian.net/browse/FIO-6841
*Fixed hidden Select Boxes Component validation preventing submission*
*no*
*All tests pass locally. One of the automated tests has been updated*
=> FIO-6841 fixed validation for hidden selectBoxes

src/Webform.js
https://formio.atlassian.net/browse/FIO-5918
*Fixed display of note on child form submission revision, when "Save as Reference" is checked for parent form. Now notes for submission revision are displayed for the child form on the PDF download page*
*no*
=> FIO-5918 fixed display of note on child form submission revision

src/Element.js, src/utils/Evaluator.js
https://formio.atlassian.net/browse/FIO-4782
*Added encodeURIComponent method for filter query*
*no*
=> FIO-4782 added encodeURIComponent for filter query

src/sass/formio.form.scss
=> Fixed issue with overflow of datagrid in the vertical direction.

src/sass/formio.form.scss, src/utils/utils.js
=> Fix special c char

package.json, src/WebformBuilder.js, src/components/radio/Radio.js, src/components/radio/Radio.unit.js, src/components/select/Select.js, src/utils/ChoicesWrapper.js, yarn.lock
https://formio.atlassian.net/browse/FIO-7128
Fixed issue with deleted values showing up when using Select with URL data type.
Fixed issue when changing to Multiple select and back (default value field wasn't updating correctly)
Fixed issue with keyboard not appearing on iPhone when tapping outside of visible input field
All tests pass locally
=> FIO-7128 Fixed issues with multiple select

src/components/_classes/list/ListComponent.js, src/components/radio/Radio.js, src/components/radio/Radio.unit.js
https://formio.atlassian.net/browse/FIO-7209
*Fixed ListData object for Radio Component without ValueProperty.*
*no*
=> Fio 7209 radio don't work without value property set when data source url

package.json, src/components/_classes/list/ListComponent.js, src/components/signature/Signature.js
=> Removing unnecessary resize observer polyfill.

src/components/number/Number.js
https://formio.atlassian.net/browse/FIO-5429 failed QA.
Reverting formio/formio.js#5115 and reassigning.
=> Revert "FI0-5429: added a condition to remove the decimal separator when the decimal digits are set to 0"

src/components/file/File.js, src/providers/storage/azure.js, src/providers/storage/googleDrive.js, src/providers/storage/s3.js
https://formio.atlassian.net/browse/FIO-7310
Reverts https://github.com/formio/formio.js/pull/5187 
We needed to revert the PRs that were attached https://formio.atlassian.net/browse/FIO-7310
and get it pulled completely out of the 8.3.0 release.
=> FIO-7310: Revert formio.js/pull/5187

src/formio.form.js
https://formio.atlassian.net/browse/FIO-6493
Library License should be taken from the options that a user provides. 
=> FIO-6493: fixed reporting license validation

package.json, src/components/_classes/component/Component.js, src/components/_classes/component/Component.unit.js, yarn.lock
https://formio.atlassian.net/browse/FIO-7246
Add HTML sanitization even if options.pdf is set
n/a
Added an automated test
=> FIO 7246: DOMPurify when PDF option is set

src/Wizard.js, src/Wizard.unit.js
=> Revert "FIO-7074: Fixes an issue where setting submission to the Wizard from the form controller will not set values for all the pages"

src/components/content/Content.js
=> Fixing issue where content component would not save in the form.

src/WebformBuilder.js, src/WebformBuilder.unit.js
https://formio.atlassian.net/browse/FIO-7206
An automated test was added, also performed manual testing
=> FIO-7206: Fixes an issue where removed components keys stay in the DataGrid defaultValue property

src/Wizard.js, src/Wizard.unit.js
https://formio.atlassian.net/browse/FIO-7074
Original PR https://github.com/formio/formio.js/pull/5306 was reverted becuase one test in formio lib was failing. During server side validation Wizard's suffix/prefix components values were removed, becuase I accidentiallly removed the fix for it while fixing the issue with setting default values to Wizard form in form controller. 
All tests on formio.js and formio are passing for me with this fix
=> Fio 7074 setting submission on wizard does not update data

src/Embed.js
=> Adding shadow dom for lib inclusion

src/components/_classes/component/Component.js, src/components/_classes/component/Component.unit.js, src/components/_classes/component/fixtures/comp5.js, src/components/_classes/component/fixtures/index.js
https://formio.atlassian.net/browse/FIO-7466
Sanitize tooltipe text to prevent executing scripts inserted inside its HTML
=> FIO-7466: Fixed an issue where code inside tolltips will be executed

src/components/columns/editForm/Columns.edit.display.js
https://formio.atlassian.net/browse/FIO-7553
Tooltip text change
Tested locally
=> FIO-7553 Changed tooltip text for the Column Properties setting

package.json, test/renders/component-bootstrap-columns-multiple.html, test/renders/component-bootstrap-columns-readOnly.html, test/renders/component-bootstrap-columns-required.html, test/renders/component-bootstrap-columns.html, test/renders/component-bootstrap-datagrid-readOnly.html, test/renders/component-bootstrap-datamap-readOnly.html, test/renders/component-bootstrap-file-readOnly.html, test/renders/form-bootstrap-columnsForm.html, test/renders/form-bootstrap-defaults.html, test/renders/form-bootstrap-formWithCollapsedPanel.html, test/renders/form-bootstrap-formWithDateTimeComponents.html, test/renders/form-bootstrap-initiallyCollapsedPanel.html, test/renders/form-bootstrap-layout.html, test/renders/form-bootstrap-multipleTextareaInsideConditionalComponent.html, test/renders/form-bootstrap-readOnly-calculateValueWithManualOverride.html, test/renders/form-bootstrap-readOnly-columnsForm.html, test/renders/form-bootstrap-readOnly-data.html, test/renders/form-bootstrap-readOnly-defaults.html, test/renders/form-bootstrap-readOnly-formWithCollapsedPanel.html, test/renders/form-bootstrap-readOnly-formWithCustomFormatDate.html, test/renders/form-bootstrap-readOnly-formWithDateTimeComponents.html, test/renders/form-bootstrap-readOnly-initiallyCollapsedPanel.html, test/renders/form-bootstrap-readOnly-layout.html, test/renders/form-bootstrap-readOnly-multipleTextareaInsideConditionalComponent.html, test/renders/form-bootstrap-readOnly-premium.html, test/renders/form-bootstrap-readOnly-settingErrors.html, test/renders/form-bootstrap-settingErrors.html, yarn.lock
https://formio.atlassian.net/browse/FIO-7640
=> FIO-7640: Fixed tests

test/renders/component-bootstrap3-survey-string-value1.html, test/renders/component-bootstrap3-survey-string-value2.html, test/renders/component-bootstrap5-survey-string-value1.html, test/renders/component-bootstrap5-survey-string-value2.html, test/renders/component-semantic-survey-string-value1.html, test/renders/component-semantic-survey-string-value2.html, test/renders/form-bootstrap-formWithObjectValueSelect.html, test/renders/form-bootstrap3-formWithObjectValueSelect.html, test/renders/form-bootstrap3-readOnly-formWithObjectValueSelect.html, test/renders/form-bootstrap5-formWithObjectValueSelect.html, test/renders/form-bootstrap5-readOnly-formWithObjectValueSelect.html, test/renders/form-semantic-formWithObjectValueSelect.html, test/renders/form-semantic-readOnly-formWithObjectValueSelect.html, test/updateRenders.js
https://formio.atlassian.net/browse/FIO-7709
fixed renders update and added updated renders
=> 4.18.x - FIO-7709: fixed failing tests

src/components/radio/Radio.js
https://formio.atlassian.net/browse/FIO-7710
Fixed the check that causes error for undefined value
=> FIO-7710: fixed the radio component check that causes an error

types/formio.d.ts
=> FIO-7717: Adding license to the Formio types.

src/templates/bootstrap/field/align.ejs
https://formio.atlassian.net/browse/FIO-7224
Adding changes from https://github.com/formio/bootstrap/pull/78 into the bootstrap template for the 4.19.x renderer.
https://github.com/formio/formio.js/pull/5355
=> FIO-7224: Changed alignment for PDF condensed mode

src/Webform.unit.js, test/forms/fieldLogic.js
N/A
https://github.com/formio/formio.js/commit/30029bb00f64ba3fca7056919d038e5eba4a4f69 looks to have resolved tests in the master branch, while breaking some of the tests in the 4.19.x branch. I've reverted most of the changes in this commit to resolve the failures.
locally run formiojs tests
=> fix-4.19.x-tests

src/components/select/fixtures/comp19.js
N/A
It was necessary to cherry-pick this fixture into the 4.19.x branch from https://github.com/formio/formio.js/pull/5294 as https://github.com/formio/formio.js/pull/5453 makes use of it in the tests.
N/A
=> Add comp 19 from select fixtures

src/components/_classes/component/Component.js, src/components/_classes/component/fixtures/comp5.js, src/utils/utils.js
Reverts formio/formio.js#5409
Decided to continue rendering the HTML and just leave it properly sanitized.
=> Revert "FIO-7466: Make tooltips show non-rendered HTML"

src/components/_classes/component/Component.js
https://formio.atlassian.net/browse/FIO-7800
Improved the check for refs so that it works in server env.
Manually
=> FIO-7800: fixed an issue where server returns an error when submitting form with editgrid

src/components/_classes/component/Component.js
Reverts formio/formio.js#5471 in preparation to revert https://github.com/formio/formio.js/pull/5206
Relevant Jira Tickets:
https://formio.atlassian.net/browse/FIO-5954
https://formio.atlassian.net/browse/FIO-7800
=> Revert "FIO-7800: fixed an issue where server returns an error when submitting form with editgrid"

.vscode/launch.json, _config.dev.yml, src/Element.js, src/Form.js, src/PDF.js, src/PDFBuilder.js, src/Webform.js, src/Webform.unit.js, src/WebformBuilder.js, src/WebformBuilder.unit.js, src/Wizard.js, src/components/_classes/component/Component.js, src/components/_classes/input/Input.js, src/components/_classes/nested/NestedComponent.js, src/components/columns/Columns.js, src/components/editgrid/EditGrid.js, src/components/file/File.js, src/components/form/Form.js, src/components/select/Select.js, src/components/table/Table.js, src/components/tags/Tags.js, src/components/tree/Tree.js, src/widgets/CalendarWidget.js
https://formio.atlassian.net/browse/FIO-7826
https://formio.atlassian.net/browse/FIO-7827
https://formio.atlassian.net/browse/FIO-7800
Reverts https://github.com/formio/formio.js/pull/5206 from the 4.19.x branch
This reverts from 4.19.x only as the effort to remove it from master will take a little longer and I would like start here and unblock this next release.
N/A
N/A
N/A
=> Revert FIO-5954 - 4.19.x

src/components/form/Form.js
https://formio.atlassian.net/browse/FIO-7823
Improved the check inside the isEmpty method of the nested form to work with undefined values.
Manually
=> FIO-7823: fixed an issue where the submission of dataGrid with nested form returns server error

src/components/editgrid/EditGrid.js
=> Fixing issues with the EditGrid tests.

src/components/select/Select.js, src/components/select/Select.unit.js, src/components/select/fixtures/comp21.js, src/components/select/fixtures/index.js
https://formio.atlassian.net/browse/FIO-7632
=> FIO-7632: Fixes an issue where HTML tags are added to the HTML5 Select metadata

src/components/recaptcha/ReCaptcha.js, src/translations/en.js
https://formio.atlassian.net/browse/FIO-7421
Pass ReCaptcha error messages through the translate function and added them to i18n config
-
Manually
=> FIO-7421: Adds ReCaptcha error messages to the translations config

src/components/button/Button.js
https://formio.atlassian.net/browse/FIO-7804
*Added support PKCE method for OIDC. Now, when using the PKCE method, there is no need to use a client secret. On the server side, code_verifier and code_challenge are generated and the request is verified*
*https://github.com/formio/formio-server/pull/1434*
*https://github.com/formio/formio-app/pull/1545*
*Manually with using onelogin app*
=> FIO-7804 Added PKCE method for OIDC

src/components/recaptcha/ReCaptcha.js
https://formio.atlassian.net/browse/FIO-7998
Remove references to server side validation (they will be handled by @formio/core) 
* [@formio/core#46](https://github.com/formio/core/pull/46)
* [formio#1712](https://github.com/formio/formio/pull/1712)
n/a
=> FIO-7998: refactor recaptcha validation

.github/workflows/config.yml, .github/workflows/release.yml, package.json
https://formio.atlassian.net/browse/FIO-6632
Add `release.yml` for releasing to formiojs.test-form.io
Minimizes redundant jobs by only running release during the tag. Runs build & test every push and release on new tags.
n/a
Passes pipeline tests and succeeds in build and release steps.
https://formiojs.test-form.io/5.0.0-testci.28/
=> FIO-6632: update-formiojs-test-env-on-tag

src/components/form/Form.js
https://formio.atlassian.net/browse/FIO-8111
*The triggering of saveDraft events for nested forms has been fixed*
*no*
*manually with using jsfiddle*
=> FIO-8111 fixed saveDraft Trigger for nested forms

src/components/form/Form.js
https://formio.atlassian.net/browse/FIO-8146
*Previously, saveDraft was triggered for the nested form after submitting the form. This was fixed by canceling triggerSaveDraft for the subForm*
*no*
*tested locally with using jsfiddle*
=> FIO-8146 fixed saveDraft triggering for nested forms after submitting

src/components/html/HTML.js
https://formio.atlassian.net/browse/FIO-7445
=> FIO-7445: fixed an issue with interpolated data in HTML

src/Formio.js
=> made Formio available globally

src/sass/formio.form.scss
n/a
Applying this contribution [7d6a3b7e2b5937fbf9153e62ad14810a0f460c8b](https://github.com/timneutkens/formio.js/blob/7d6a3b7e2b5937fbf9153e62ad14810a0f460c8b/src/sass/formio.form.scss) from @timneutkens to the master branch
=> Remove *zoom (IE7 hack)

src/Webform.js, src/components/form/Form.js, src/components/form/Form.unit.js
https://formio.atlassian.net/browse/FIO-8433
*Fixed the issue of restoring a draft of a nested form*
*n/a*
*Automated tests have been added. All tests pass locally*
=> FIO-8433 fixed restore draft for nested forms

package.json, src/utils/utils.js
=> Removing fetch ponyfill since it is no longer needed.

.circleci/config.yml
=> Update Circle CI config to use lts node and yarn package manager

src/components/datagrid/DataGrid.js, src/components/datamap/DataMap.js
https://formio.atlassian.net/browse/FIO-8710
Changed import of Components
Manually
=> FIO-8710: fixed incorrect Components import that causes errors when interacting with form components

src/Wizard.unit.js, src/components/_classes/nested/NestedComponent.js, test/forms/wizardWithRequiredFields.js
https://formio.atlassian.net/browse/FIO-8719
*Validation before going to the next page for fields inside Nested Wizard form has been fixed*
*n/a*
*n/a*
*Automated test have been added. All tests pass locally*
=> FIO-8719 fixed validation for nested wizard fields

src/components/datamap/DataMap.js
https://formio.atlassian.net/browse/FIO-8765
Fixed wrong method name
=> FIO-8765: fixed an issue where dataMap thows an error

src/components/file/File.js, src/components/file/File.unit.js
https://formio.atlassian.net/browse/FIO-8621
‘fileUploadError’ event was added. Event contain information about the upload error received from a file storage provider.
-
-
Autotests
- [х] I have completed the above PR template
=> FIO-8621: error event on file upload adding

src/Wizard.unit.js, src/components/_classes/nested/NestedComponent.js, test/forms/wizardWithRequiredFields.js
https://formio.atlassian.net/browse/FIO-8719
*Fixed validation before going to the next page for fields inside Data Grid component in Nested Wizard form*
*n/a*
*n/a*
*Automated tests have been updated. All tests pass locally*
=> FIO-8719 fixed validation for Data Grid component inside nested wizard

src/components/file/File.js, src/components/file/File.unit.js
https://formio.atlassian.net/browse/FIO-8621
‘fileUploadError’ event was added. Event contain information about the upload error received from a file storage provider.
Autotests
=> FIO-8621: added error event on file upload

src/components/time/Time.form.js
https://formio.atlassian.net/browse/FIO-8799
*Updated conditional tab for Time component with the latest simple conditions*
*n/a*
*n/a*
=> FIO-8799 updated conditional tab for Time Component

src/components/file/File.js
https://formio.atlassian.net/browse/FIO-8771
*Added support for File component as Reviewing Field of Review Page component. Reviewing data  for File component is presented as links with the ability to open uploaded file in a new tab. Similarly, links work for edit/data grid with a file component is added to the review page component*
*n/a*
*https://github.com/formio/premium/pull/318*
=> FIO-8771 Included File Component in Review Page Component

src/components/radio/Radio.js, src/components/selectboxes/SelectBoxes.js
https://formio.atlassian.net/browse/FIO-8849
Use select with URL type to display selectboxes/radio values in simple conditions
https://github.com/formio/formio/pull/1789
Manually
=> FIO-8849: fixed an issue where value of the selctboxes/radio with URL data source are not available in simple conditons UI

src/components/file/File.js, src/components/file/editForm/File.edit.display.js
https://formio.atlassian.net/browse/FIO-8931
Disable the file synchronization feature
=> FIO-8931: Disable file synchronization feature

src/components/datagrid/DataGrid.js, src/components/datagrid/DataGrid.unit.js
https://formio.atlassian.net/browse/FIO-8458
*Removing a row from a datagrid triggers the savedraft action*
*n/a*
*n/a*
*Automated tests have been added*
=> FIO-8458 removing row from data grid triggers save draft action

src/components/recaptcha/ReCaptcha.js
https://formio.atlassian.net/browse/FIO-8866
https://formio.atlassian.net/browse/FIO-8864
made only 2 operators (isEmpty and isNotEmpty) available for recaptcha in simple conditional ui
https://github.com/formio/premium/pull/325
Manually
=> FIO-8866-8864: fixed simple conditions operators for recaptcha

src/WebformBuilder.unit.js
https://formio.atlassian.net/browse/FIO-8970
*resolved failing test on master branch*
*n/a*
*n/a*
*locally*
=> FIO-8970 resolved failing test

package.json, src/WebformBuilder.unit.js, src/components/_classes/multivalue/Multivalue.js, yarn.lock
https://formio.atlassian.net/browse/FIO-8912
When a `multiple: true` component's value is normalized (see #5777) there is a desynchronization between the component instance value and the submission value. This PR adds the normalization routine to when getting and setting `dataValue`. 
n/a
* https://github.com/formio/core/pull/145
Automated tests are passing + the previous normalization tests
=> FIO-8912: fix normalization in submission

src/components/select/Select.js, src/components/select/Select.unit.js, src/components/select/fixtures/comp27.js, src/components/select/fixtures/index.js
https://formio.atlassian.net/browse/FIO-8972
*Fixed displaying the data of the select component  with dataSrc set as custom on Data Tab. An error occurred previously. The error has been fixed and the value is displayed as expected*
*n/a*
*n/a*
*automated test has been added. All tests pass locally*
=> FIO-8972 fixed display of select componet with custom dataSrc on Data Tab

src/components/radio/Radio.js, src/components/select/Select.js, src/components/select/editForm/Select.edit.validation.js, src/components/selectboxes/SelectBoxes.js
https://formio.atlassian.net/browse/FIO-8954
Made "Allow only available values” available for Select component. Made adjustments for validateValueAvailability method to make sure list of available values to compare is correct for data source = url.
n/a
n/a
tested manually
=> FIO-8954 previously selected option is displayed in metadata with data source = url

src/components/select/Select.js, src/components/select/Select.unit.js, src/components/select/fixtures/comp4.js
https://formio.atlassian.net/browse/FIO-8991
Fixed incorrect use of the array mapping function that courses the number values to be undefined
https://github.com/formio/reporting/pull/44
Manually + test
=> FIO-8991: fixed an issue where select  value (when it is array with numbers) does not display in submission grid

Changelog.md
=> 4.21.4-rc.2 changelog

src/WebformBuilder.js, test/forms/simpleWebform.js, test/unit/WebformBuilder.unit.js
https://formio.atlassian.net/browse/FIO-9034
*Fixed a behavior where an additional submit button was added after changing the API key of an existing submit button*
*n/a*
*n/a*
*Automated test have been added. All tests pass locally*
=> FIO-9034 fixed creating extra submit button

_layouts/default.md
https://formio.atlassian.net/browse/FIO-8569
SDK Link was broken
NA
NA
NA
Manually
=> FIO-8569: Fix sdk link

src/Wizard.unit.js, src/components/panel/Panel.js
https://formio.atlassian.net/browse/FIO-8944
*Fixed focusing of invalid elements when clicking on a link from the error list for Nested Wizard form*
*n/a*
*n/a*
=> FIO-8944 fixed navigation through the errors list

src/components/_classes/component/Component.js, test/forms/formWithConditionalEmail.js, test/unit/Webform.unit.js
https://formio.atlassian.net/browse/FIO-9147
Added a form schema to the component validation context. It requires for simple conditions in the core to get the condition base component and identify correctly if component is conditionally visible.
Manually + test
=> FIO-9147: fixed an issue where the simple conditionally visible component is not validated on change

src/components/_classes/component/Component.js
https://formio.atlassian.net/browse/FIO-9153
https://formio.atlassian.net/browse/FIO-9154
Improved check for index definition when focusing the component
https://github.com/formio/premium/pull/337
Manually
=> FIO-9153-9154: fixed console errors when navigating tagpad validation errors

src/components/_classes/component/Component.js
https://formio.atlassian.net/browse/FIO-9158
fixed mistake in https://github.com/formio/formio.js/pull/5840
n/a
n/a
tested manually, test were added in https://github.com/formio/formio.js/pull/5840
=> FIO-9158: fixed password component error in Edit page

package.json, yarn.lock
=> Update text-mask-addons to formio.3

src/components/_classes/field/Field.js
https://formio.atlassian.net/browse/FIO-9506
fixed type
=> FIO-9506: fixed the return type of the render function

package.json, yarn.lock
https://formio.atlassian.net/browse/FIO-9507
Update version
Generate a fresh dev tag to filter up the dependency tree
n/a
https://github.com/formio/core/pull/205
https://github.com/formio/bootstrap/pull/120
n/a
=> CHORE - update master version and dependencies

package.json, yarn.lock
https://formio.atlassian.net/browse/FIO-9507
Update version
Generate a fresh dev tag to filter up the dependency tree
n/a
https://github.com/formio/core/commit/49ab979f5f041fb26ce43d264a843177a5465bb2
https://github.com/formio/bootstrap/pull/120
n/a
=> FIO-9507 update core dev tag again

src/Form.js
https://formio.atlassian.net/browse/FIO-9592
Added event for form display type change (needed in @formio/react to subscribe and update form json, so to not copy submit button adding/removing logic when switching to Wizard and back)
formio/react/pull/593
Manually
=> FIO-9592: Add emitting form display change event

src/Webform.js
https://formio.atlassian.net/browse/FIO-9156
*Fixed the CAPTCHA component display on the preview*
*n/a*
*https://github.com/formio/premium/pull/366*
*locally using cloudflare Provider. All tests pass locally*
=> FIO-9156 fixed the display of Captcha component for nested forms

src/components/day/Day.js
https://formio.atlassian.net/browse/FIO-9614
Do not transform user min/max validation input in builder for day component
=> FIO-9614: fixed an issue where min and max day builder setting changes its value after saving

src/components/_classes/component/editForm/Component.edit.conditional.js, src/components/_classes/component/editForm/Component.edit.data.js, src/components/_classes/component/editForm/utils.js
https://formio.atlassian.net/browse/FIO-9669
added token to the list of the available variables for advanced conditions
=> FIO-9669: added token to the list of the available variables for advanced conditions

src/components/form/editForm/Form.edit.data.js
https://formio.atlassian.net/browse/FIO-9620
Updates `clearOnHide` copy for the Nested Form component.
n/a
n/a
n/a
=> FIO-9620: update copy on Form component editForm

src/Webform.js
https://formio.atlassian.net/browse/FIO-9720
*Fixed an issue where the captcha component is not triggered if it is located inside layout component.*
*n/a*
*n/a*
*locally. All tests pass locally*
=> FIO-9720 fixet trigger captcha component inside layout component

test/forms/formWithSimpleController.js, test/unit/Webform.unit.js
https://formio.atlassian.net/browse/FIO-9020
Added test for my fix merged earlier https://github.com/formio/formio.js/pull/6007
=> Addded test for FIO-9020

src/Wizard.js
https://formio.atlassian.net/browse/FIO-9720
*fixed typo*
*n/a*
*https://github.com/formio/formio.js/pull/6025*
*locally*
=> FIO-9720 fixed typo

src/Form.js
i18n had an incorrect type definition. Changed it to the correct type definition
Credit: https://github.com/Oaciqihz
https://github.com/formio/react/issues/601
=> updated i18n typedef

src/components/_classes/component/Component.js, src/components/_classes/nested/NestedComponent.js, src/components/datamap/DataMap.js, src/components/form/Form.js, src/components/html/HTML.js, src/components/radio/Radio.js, test/forms/helpers/testBasicComponentSettings/tests.js, test/unit/Wizard.unit.js
=> FIO-9807: Refactor the conditionally hidden check to be performed at runtime.

src/Wizard.js
https://formio.atlassian.net/browse/FIO-9830
*Fixed an issue where the captcha would not trigger on any page except the first one and an error appeared in the console.*
*n/a*
*n/a*
*locally using Cloudflare captcha provider*
=> FIO-9830 fixed captcha trigger for wizard

src/components/select/Select.js
https://formio.atlassian.net/browse/FIO-9532
Added condition for emails.
n/a
https://github.com/formio/vm/pull/54
tests added in https://github.com/formio/formio/pull/1947
=> FIO-9532: fixed an issue where select components shows values instead of labels in email

src/components/_classes/component/editForm/Component.edit.data.js
https://formio.atlassian.net/browse/FIO-9846
*Added logic hiding Encrypted option for the EFB module*
*n/a*
*https://github.com/formio/formio-app/pull/1682*
*locally using EFB demo app*
=> FIO-9846 removed encrypted option for EFB

package.json, src/utils/utils.js, test/forms/formWithShowAsString.js, test/unit/Webform.unit.js, yarn.lock
https://formio.atlassian.net/browse/FIO-9908
If the 'show' setting of conditionals is a string, we need to parse it and convert to boolean so that it works as expected.
https://github.com/formio/core/pull/232
https://github.com/formio/premium/pull/386
Manually + autotests
=> FIO-9908: fixed an issue where condition does not work properly if 'show' setting is a string

.github/workflows/sync-monorepo.mjs, .github/workflows/sync-pr-to-monorepo.yml, package.json, yarn.lock
Added a gh action that syncs prs to the monorepo
=> gh action to sync prs to monorepo

README.md
=> Testing monorepo-sync

src/components/day/Day.js, test/unit/Day.unit.js
https://formio.atlassian.net/browse/FIO-10163
Added check for undefined options parameter when creating Day component.
-
-
manually
autotests
=> FIO-10163: fix csv export for day component

src/utils/utils.js, src/widgets/CalendarWidget.js
https://formio.atlassian.net/browse/FIO-10214
fixed types
=> FIO-10214: fixed types

src/components/_classes/component/Component.js, src/components/textarea/TextArea.js
https://formio.atlassian.net/browse/FIO-5508
Upgraded CKEditor to the latest version and made corresponding changes in formio.js
https://github.com/formio/ckeditor5-build-classic/pull/4
https://github.com/formio/cdn.form.io/pull/25
Manual testing of used features in formio.js
=> FIO-5508: Upgraded CKEditor to the latest version

src/widgets/CalendarWidget.js, test/unit/TextArea.unit.js
https://formio.atlassian.net/browse/FIO-10299
Removed redundant code that was added by sync PR https://github.com/formio/formio.js/pull/6173 and was not a part of my initial PR https://github.com/formio/formio-monorepo/pull/243.
=> FIO-10299: fixed tests

src/Element.js, src/formio.form.js, src/utils/index.js
=> 5.2.x-specific PR for FIO-9942

src/components/form/Form.js, test/forms/nestedFormWithContentComp.js, test/unit/Form.unit.js
=> sync nirvana pr #44 / master_old pr #6035 to nirvana

src/components/number/Number.js
See [here](https://github.com/formio/nirvana/pull/50)
=> FIO-10305: Fixes an issue where Number component return NaN as a default value
